//! Marker-based Perl dependency-manager include-path detection.

use std::path::Path;

/// Carton and rolled-out Carmel share one install-base layout: a standard
/// ExtUtils::InstallPaths `local/` tree whose single include root is
/// `local/lib/perl5` (#13642 plan S8 receipt §1/§3).
const LOCAL_INSTALL_INCLUDE_PATH: &str = "local/lib/perl5";

/// `carmel rollout` touches `local/.carmel` to mark the `local/` tree as
/// Carmel rollout output rather than a plain local::lib/Carton tree. Without
/// this sentinel a `local/` tree is ambiguous with Carton/local::lib and this
/// detector makes no Carmel claim — the shared `local/lib/perl5` root is
/// attributed through the Carton/ambiguous origin instead.
const CARMEL_ROLLOUT_SENTINEL: &str = "local/.carmel";

/// Discriminating Carmel dev-state marker generated by `carmel install`.
///
/// Dev-mode Carmel installs nothing project-local: its artifact roots are
/// out-of-workspace, interpreter-keyed absolute paths under the central
/// repository. They must never flow through this relative-literal detector
/// (#4998 gate; #13642 §3(2)) — they enter the environment snapshot through
/// `perl_workspace_core::carmel` as Ambient-authority candidates or explicit
/// limitations, never as project `@INC` authority without explicit trust.
#[cfg(test)]
const CARMEL_DEV_STATE: &str = ".carmel/MySetup.pm";

/// Detect include paths produced by Carton and Carmel in a workspace root.
///
/// The project is the directory holding `cpanfile` (the declaration; never
/// installed-root evidence by itself). One relative root is produced:
/// `local/lib/perl5` — when Carton markers (`carton.lock`, `cpanfile.snapshot`)
/// are present, or when the `local/.carmel` rollout sentinel marks the tree
/// as Carmel rollout output. A `cpanfile.snapshot` alone cannot identify its
/// producer (the Carton-format header carries no producer field), so this
/// detector attributes no separate Carmel root and adds nothing for Carmel
/// dev-mode state (`.carmel/MySetup.pm`), which has no project-local root.
///
/// These are runtime-derived roots (#4998): their safety class is "bounded,
/// hard-coded, workspace-relative literals" and must stay that way. They are
/// appended to the effective include-path projection only after
/// resource-scope validation conventions; a future metadata-derived absolute
/// root must enter through an explicitly classified source instead
/// (configuration observation train, #10817).
#[must_use]
pub fn detect_dependency_include_paths(workspace_root: &Path) -> Vec<String> {
    if !workspace_root.join("cpanfile").is_file() {
        return Vec::new();
    }

    let carton_locked = workspace_root.join("carton.lock").is_file()
        || workspace_root.join("cpanfile.snapshot").is_file();
    let carmel_rolled_out = workspace_root.join(CARMEL_ROLLOUT_SENTINEL).exists();

    if carton_locked || carmel_rolled_out {
        vec![LOCAL_INSTALL_INCLUDE_PATH.to_string()]
    } else {
        Vec::new()
    }
}

#[cfg(test)]
mod tests {
    use super::detect_dependency_include_paths;
    use super::{CARMEL_DEV_STATE, CARMEL_ROLLOUT_SENTINEL, LOCAL_INSTALL_INCLUDE_PATH};

    #[test]
    fn detects_carton_from_lockfile() -> Result<(), Box<dyn std::error::Error>> {
        let workspace = tempfile::tempdir()?;
        std::fs::write(workspace.path().join("cpanfile"), "requires 'JSON';\n")?;
        std::fs::write(workspace.path().join("carton.lock"), "snapshot\n")?;

        assert_eq!(
            detect_dependency_include_paths(workspace.path()),
            vec![LOCAL_INSTALL_INCLUDE_PATH]
        );
        Ok(())
    }

    #[test]
    fn detects_carton_from_cpanfile_snapshot() -> Result<(), Box<dyn std::error::Error>> {
        let workspace = tempfile::tempdir()?;
        std::fs::write(workspace.path().join("cpanfile"), "requires 'JSON';\n")?;
        std::fs::write(workspace.path().join("cpanfile.snapshot"), "snapshot\n")?;

        assert_eq!(
            detect_dependency_include_paths(workspace.path()),
            vec![LOCAL_INSTALL_INCLUDE_PATH]
        );
        Ok(())
    }

    /// Migrated Carmel detection (#13642 §2/§3): the post-rollout root is the
    /// shared install-base literal, admitted only through the `local/.carmel`
    /// sentinel that `carmel rollout` touches.
    #[test]
    fn detects_carmel_rollout_from_sentinel() -> Result<(), Box<dyn std::error::Error>> {
        let workspace = tempfile::tempdir()?;
        std::fs::write(workspace.path().join("cpanfile"), "requires 'JSON';\n")?;
        std::fs::create_dir_all(workspace.path().join("local"))?;
        std::fs::write(workspace.path().join(CARMEL_ROLLOUT_SENTINEL), "")?;
        std::fs::create_dir_all(workspace.path().join(LOCAL_INSTALL_INCLUDE_PATH))?;

        assert_eq!(
            detect_dependency_include_paths(workspace.path()),
            vec![LOCAL_INSTALL_INCLUDE_PATH]
        );
        Ok(())
    }

    /// Dev-mode Carmel has no project-local root: the detector must return
    /// nothing, and the out-of-workspace artifact roots are owned by the
    /// environment detection seam, never by this relative-literal detector.
    #[test]
    fn carmel_dev_mode_has_no_project_local_root() -> Result<(), Box<dyn std::error::Error>> {
        let workspace = tempfile::tempdir()?;
        std::fs::write(workspace.path().join("cpanfile"), "requires 'JSON';\n")?;
        std::fs::create_dir_all(workspace.path().join(".carmel"))?;
        std::fs::write(
            workspace.path().join(CARMEL_DEV_STATE),
            "our %environment = ('inc' => [], 'base' => '/x');\n",
        )?;

        assert!(detect_dependency_include_paths(workspace.path()).is_empty());
        Ok(())
    }

    /// Migrated mislabel (#13642 §2): Carmel's source has no `vendor/lib/perl5`
    /// anywhere (`vendor/cache` is a tarball dir), so an unrelated vendor tree
    /// no longer claims Carmel.
    #[test]
    fn vendor_root_no_longer_claims_carmel() -> Result<(), Box<dyn std::error::Error>> {
        let workspace = tempfile::tempdir()?;
        std::fs::write(workspace.path().join("cpanfile"), "requires 'JSON';\n")?;
        std::fs::create_dir_all(workspace.path().join("vendor/lib/perl5"))?;

        assert!(detect_dependency_include_paths(workspace.path()).is_empty());
        Ok(())
    }

    /// Both managers present: one shared install root, never duplicated, and
    /// no second Carmel-specific path.
    #[test]
    fn both_managers_yield_single_install_root() -> Result<(), Box<dyn std::error::Error>> {
        let workspace = tempfile::tempdir()?;
        std::fs::write(workspace.path().join("cpanfile"), "requires 'JSON';\n")?;
        std::fs::write(workspace.path().join("carton.lock"), "snapshot\n")?;
        std::fs::create_dir_all(workspace.path().join(".carmel"))?;
        std::fs::write(workspace.path().join(CARMEL_DEV_STATE), "1;\n")?;

        assert_eq!(
            detect_dependency_include_paths(workspace.path()),
            vec![LOCAL_INSTALL_INCLUDE_PATH]
        );
        Ok(())
    }

    #[test]
    fn requires_expected_markers() -> Result<(), Box<dyn std::error::Error>> {
        let workspace = tempfile::tempdir()?;
        std::fs::write(workspace.path().join("carton.lock"), "snapshot\n")?;
        assert!(detect_dependency_include_paths(workspace.path()).is_empty());

        std::fs::write(workspace.path().join("cpanfile"), "requires 'JSON';\n")?;
        std::fs::write(workspace.path().join("carton.lock"), "snapshot\n")?;
        assert_eq!(
            detect_dependency_include_paths(workspace.path()),
            vec![LOCAL_INSTALL_INCLUDE_PATH]
        );

        std::fs::remove_file(workspace.path().join("carton.lock"))?;
        assert!(detect_dependency_include_paths(workspace.path()).is_empty());

        std::fs::create_dir_all(workspace.path().join("local"))?;
        std::fs::write(workspace.path().join(CARMEL_ROLLOUT_SENTINEL), "")?;
        assert_eq!(
            detect_dependency_include_paths(workspace.path()),
            vec![LOCAL_INSTALL_INCLUDE_PATH]
        );
        Ok(())
    }

    /// Recurrence gate (#4998): runtime-derived dependency roots must stay
    /// relative workspace-contained literals. If a future change makes this
    /// detector return absolute or traversal-capable paths from project
    /// metadata (such as Carmel's embedded out-of-workspace artifact roots),
    /// they would inherit resource-scope validation by convention;
    /// that writer must instead be explicitly classified first.
    #[test]
    fn detected_roots_stay_relative_and_workspace_contained()
    -> Result<(), Box<dyn std::error::Error>> {
        let workspace = tempfile::tempdir()?;
        std::fs::write(workspace.path().join("cpanfile"), "requires 'JSON';\n")?;
        std::fs::write(workspace.path().join("carton.lock"), "snapshot\n")?;
        std::fs::create_dir_all(workspace.path().join("local"))?;
        std::fs::write(workspace.path().join(CARMEL_ROLLOUT_SENTINEL), "")?;

        for path in detect_dependency_include_paths(workspace.path()) {
            let candidate = std::path::Path::new(&path);
            assert!(!candidate.is_absolute(), "runtime-derived root must not be absolute: {path}");
            assert!(
                !candidate.components().any(|c| c == std::path::Component::ParentDir),
                "runtime-derived root must not traverse: {path}"
            );
            assert!(
                workspace.path().join(&path).starts_with(workspace.path()),
                "runtime-derived root must stay inside the workspace: {path}"
            );
        }
        Ok(())
    }
}
