//! Project metadata path classification (#13640).
//!
//! The runtime watches every workspace path (`**/*`, #13308/#14186) and
//! classifies each delivered event from the shared admission authority. That
//! authority answers one question: *is this Perl source?* Project metadata
//! feeds a different family of facts — declared dependencies
//! ([`super::detect_declared_dependencies`]) and dependency-manager include
//! roots ([`super::detect_dependency_include_paths`]) — whose owner is never
//! reached by source classification alone.
//!
//! This module is the single place that answers *does this path feed those
//! facts?* The filename sets below are bound to the detectors themselves
//! rather than restated: [`DeclaredDependencySource::ALL`] is the exact list
//! `detect_declared_dependencies` reads, and the environment markers are the
//! same constants `detect_dependency_include_paths` probes. A new metadata
//! source therefore cannot be detected without also becoming watchable.
//!
//! # Claim boundary
//!
//! Classification mirrors the detectors' `workspace_root.join(..)`: only
//! workspace-root-relative paths match, so a nested `t/cpanfile` is not
//! project metadata. Comparison is ASCII case-insensitive because the
//! detectors' `join` resolves differently-cased names on a case-insensitive
//! filesystem; see `relative_matches` for why matching too eagerly is the
//! safe direction and missing an event is not.

use std::path::{Component, Path};

use super::metadata_dependencies::DeclaredDependencySource;

/// `carmel rollout` touches `local/.carmel` to mark the `local/` tree as
/// Carmel rollout output rather than a plain local::lib/Carton tree. Without
/// this sentinel a `local/` tree is ambiguous with Carton/local::lib and the
/// detector makes no Carmel claim — the shared `local/lib/perl5` root is
/// attributed through the Carton/ambiguous origin instead.
pub(crate) const CARMEL_ROLLOUT_SENTINEL: &str = "local/.carmel";

/// Discriminating Carmel dev-state marker generated by `carmel install`.
///
/// Dev-mode Carmel installs nothing project-local: its artifact roots are
/// out-of-workspace, interpreter-keyed absolute paths under the central
/// repository. They must never flow through the relative-literal detector
/// (#4998 gate; #13642 §3(2)) — they enter the environment snapshot through
/// `perl_workspace_core::carmel` as Ambient-authority candidates or explicit
/// limitations, never as project `@INC` authority without explicit trust.
///
/// The marker also discriminates the lock: `carmel install` writes
/// `cpanfile.snapshot` itself (receipt §1, support since v0.1.29), so the
/// canonical dev-mode workspace is cpanfile + `cpanfile.snapshot` +
/// `.carmel/MySetup.pm` with no `local/.carmel`. Contract §2(b): that shape
/// is dev mode and must not yield the project-local root.
pub(crate) const CARMEL_DEV_STATE: &str = ".carmel/MySetup.pm";

/// Carton lock marker.
pub(crate) const CARTON_LOCK: &str = "carton.lock";

/// The `cpanfile` declaration that gates include-root detection.
///
/// Same spelling as [`DeclaredDependencySource::Cpanfile`]'s file name; the
/// equality is asserted by a test below so the two cannot drift.
pub(crate) const CPANFILE_DECLARATION: &str = "cpanfile";

/// Shared Carton/Carmel snapshot lock.
pub(crate) const CPANFILE_SNAPSHOT: &str = "cpanfile.snapshot";

/// Workspace-root-relative paths that feed dependency-manager include roots.
///
/// These are exactly the paths [`super::detect_dependency_include_paths`]
/// probes. `cpanfile` is the declaration gate for that detector and also a
/// declared-dependency source, so it is classified through
/// [`DeclaredDependencySource`] and reported as [`ProjectMetadataKind::Both`].
const ENVIRONMENT_MARKER_PATHS: &[&str] =
    &[CPANFILE_SNAPSHOT, CARTON_LOCK, CARMEL_DEV_STATE, CARMEL_ROLLOUT_SENTINEL];

/// Which family of cached facts a project metadata path feeds.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectMetadataKind {
    /// Feeds declared-dependency facts only.
    DeclaredDependencies,
    /// Feeds dependency-manager include-root facts only.
    EnvironmentRoots,
    /// Feeds both families.
    Both,
}

/// Every workspace-root-relative path that feeds dependency or environment
/// facts, in a deterministic order.
///
/// Callers that must decide whether a filesystem *subtree* contains project
/// metadata (a directory delete or rename) use this rather than re-deriving
/// the set, so subtree matching cannot drift from exact classification.
pub fn project_metadata_relative_paths() -> impl Iterator<Item = &'static str> {
    DeclaredDependencySource::ALL
        .into_iter()
        .map(DeclaredDependencySource::file_name)
        .chain(ENVIRONMENT_MARKER_PATHS.iter().copied())
}

/// Returns the metadata family `path` feeds for `workspace_root`, if any.
///
/// `path` must be an absolute filesystem path. A path outside `workspace_root`
/// never classifies, so events from unrelated trees cannot trigger a refresh.
#[must_use]
pub fn classify_project_metadata_path(
    workspace_root: &Path,
    path: &Path,
) -> Option<ProjectMetadataKind> {
    let relative = path.strip_prefix(workspace_root).ok()?;

    let declared = DeclaredDependencySource::ALL
        .iter()
        .any(|source| relative_matches(relative, source.file_name()));
    let environment =
        ENVIRONMENT_MARKER_PATHS.iter().any(|marker| relative_matches(relative, marker));

    match (declared, environment) {
        // `cpanfile` is both the declared-dependency source and the gate that
        // enables include-root detection at all.
        (true, _) if relative_matches(relative, DeclaredDependencySource::Cpanfile.file_name()) => {
            Some(ProjectMetadataKind::Both)
        }
        (true, true) => Some(ProjectMetadataKind::Both),
        (true, false) => Some(ProjectMetadataKind::DeclaredDependencies),
        (false, true) => Some(ProjectMetadataKind::EnvironmentRoots),
        (false, false) => None,
    }
}

/// Compare a workspace-relative path against a `/`-separated literal.
///
/// Component-wise, so the literal stays platform-neutral.
///
/// ASCII case-insensitive, deliberately. The detectors address metadata by
/// `workspace_root.join("cpanfile")`, and on a case-insensitive filesystem
/// (Windows, and macOS by default) that call resolves `CPANFILE` too. A
/// byte-exact classifier would therefore refuse to classify a watcher event
/// the detector *would* read, leaving facts stale until an unrelated metadata
/// event arrived.
///
/// The asymmetry favors matching: on a case-sensitive filesystem a `CPANFILE`
/// event that is genuinely a different file triggers one extra refresh, which
/// recomputes from actual disk state and is therefore correct and idempotent —
/// wasted work at worst. Missing an event is a real staleness bug. Matching
/// only ASCII case keeps the comparison locale-independent, since all governed
/// literals are ASCII.
fn relative_matches(relative: &Path, expected: &str) -> bool {
    let mut expected_components = expected.split('/');
    let mut actual_components = relative.components();
    loop {
        match (expected_components.next(), actual_components.next()) {
            (Some(expected), Some(Component::Normal(actual))) => {
                let Some(actual) = actual.to_str() else {
                    return false;
                };
                if !actual.eq_ignore_ascii_case(expected) {
                    return false;
                }
            }
            (None, None) => return true,
            _ => return false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{ProjectMetadataKind, classify_project_metadata_path};
    use std::path::{Path, PathBuf};

    fn root() -> PathBuf {
        PathBuf::from(if cfg!(windows) { r"C:\ws" } else { "/ws" })
    }

    fn classify(relative: &str) -> Option<ProjectMetadataKind> {
        let root = root();
        let mut path = root.clone();
        for component in relative.split('/') {
            path.push(component);
        }
        classify_project_metadata_path(&root, &path)
    }

    #[test]
    fn declared_dependency_sources_classify() {
        for name in ["Makefile.PL", "Build.PL", "dist.ini", "META.json", "META.yml"] {
            assert_eq!(
                classify(name),
                Some(ProjectMetadataKind::DeclaredDependencies),
                "{name} must feed declared-dependency facts"
            );
        }
    }

    #[test]
    fn cpanfile_declaration_constant_matches_the_declared_source() {
        assert_eq!(
            super::CPANFILE_DECLARATION,
            super::DeclaredDependencySource::Cpanfile.file_name()
        );
    }

    #[test]
    fn cpanfile_feeds_both_families() {
        assert_eq!(classify("cpanfile"), Some(ProjectMetadataKind::Both));
    }

    #[test]
    fn environment_markers_classify() {
        for name in ["cpanfile.snapshot", "carton.lock", ".carmel/MySetup.pm", "local/.carmel"] {
            assert_eq!(
                classify(name),
                Some(ProjectMetadataKind::EnvironmentRoots),
                "{name} must feed dependency include-root facts"
            );
        }
    }

    /// The detectors only ever `join` at the workspace root, so a nested
    /// file with a metadata name is ordinary project content.
    #[test]
    fn nested_metadata_names_are_not_project_metadata() {
        for name in ["t/cpanfile", "lib/META.json", "vendor/local/.carmel", "sub/dist.ini"] {
            assert_eq!(classify(name), None, "{name} must not be project metadata");
        }
    }

    #[test]
    fn ordinary_perl_sources_are_not_project_metadata() {
        for name in ["lib/App.pm", "bin/tool.pl", "t/basic.t", "README.md"] {
            assert_eq!(classify(name), None, "{name} must not be project metadata");
        }
    }

    #[test]
    fn paths_outside_the_workspace_never_classify() {
        let outside = if cfg!(windows) { r"C:\other\cpanfile" } else { "/other/cpanfile" };
        assert_eq!(classify_project_metadata_path(&root(), Path::new(outside)), None);
    }

    /// The subtree path set must cover exactly what classification accepts.
    #[test]
    fn relative_path_set_matches_classification() {
        for relative in super::project_metadata_relative_paths() {
            assert!(
                classify(relative).is_some(),
                "{relative} is listed as governed metadata but does not classify"
            );
        }
    }

    /// A differently-cased spelling classifies, because the detectors' `join`
    /// resolves it on a case-insensitive filesystem and a missed event leaves
    /// facts stale. The extra refresh this can cause on a case-sensitive
    /// filesystem recomputes from disk and is harmless.
    #[test]
    fn classification_is_ascii_case_insensitive() {
        assert_eq!(classify("CPANFILE"), Some(ProjectMetadataKind::Both));
        assert_eq!(classify("makefile.pl"), Some(ProjectMetadataKind::DeclaredDependencies));
        assert_eq!(classify("Local/.Carmel"), Some(ProjectMetadataKind::EnvironmentRoots));
    }

    /// Case-insensitivity must not widen *which* names count.
    #[test]
    fn case_insensitivity_does_not_admit_unrelated_names() {
        for name in ["cpanfile2", "cpan", "META.jsonx", "distx.ini"] {
            assert_eq!(classify(name), None, "{name} must not classify");
        }
    }
}
