//! Deterministic human-readable status for the critic rule-proof pilot.

use perl_lsp_rs_core::tooling::perl_critic::{NativeCriticProfile, NativeCriticRegistry};
use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use super::error::ProofError;
use super::model::{EvidenceClass, RuleProofManifest, STATUS_PATH};

/// Per-class proof disposition shown in generated status.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ClassStatus {
    Present,
    Missing,
    NotApplicable,
}

impl ClassStatus {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Present => "present",
            Self::Missing => "MISSING",
            Self::NotApplicable => "n/a",
        }
    }
}

/// Render the committed status markdown from a validated manifest.
#[must_use]
pub fn render_status(manifest: &RuleProofManifest) -> String {
    let mut markdown = String::from("# Critic Rule-Proof Status\n\n");
    markdown.push_str("> Generated by `cargo xtask critic-rule-proof check` / `write-status`.\n\n");
    markdown.push_str(&format!(
        "Pilot issue #{} (`{}`). Missing evidence stays missing and is not inherited from aggregate native-critic transport coverage.\n\n",
        manifest.issue, manifest.status
    ));
    markdown.push_str(&format!("{}\n\n", manifest.claim_boundary));
    markdown.push_str("## Pilot rules\n\n");
    markdown.push_str("| Rule | Canonical | Remediation |");
    for class in EvidenceClass::all() {
        markdown.push(' ');
        markdown.push_str(class.as_str());
        markdown.push_str(" |");
    }
    markdown.push('\n');
    markdown.push_str("| --- | --- | --- |");
    for _ in EvidenceClass::all() {
        markdown.push_str(" --- |");
    }
    markdown.push('\n');

    for rule in &manifest.rules {
        let present = classes_for_rule(manifest, &rule.rule_id);
        markdown.push_str(&format!(
            "| `{}` | `{}` | `{}` |",
            rule.rule_id,
            rule.canonical_id,
            rule.declared_remediation.as_str()
        ));
        for class in EvidenceClass::all() {
            let status = class_status(
                *class,
                present.contains(class),
                rule.declared_remediation.automatic_round_trip_applicable(),
            );
            markdown.push(' ');
            markdown.push_str(status.as_str());
            markdown.push_str(" |");
        }
        markdown.push('\n');
    }

    markdown.push_str("\n## Catalog remainder\n\n");
    let catalog_count = NativeCriticRegistry::for_profile(NativeCriticProfile::Strict).len();
    let ungoverned = catalog_count.saturating_sub(manifest.rules.len());
    markdown.push_str(&format!(
        "{ungoverned} catalog native rules are outside this pilot. Their evidence classes remain MISSING; they do not inherit proof from transport coverage, false-positive corpus counts, or recommended/strict rule-count totals.\n",
    ));
    markdown
}

/// Byte-compare generated status against the committed file.
pub fn check_status(root: &Path, manifest: &RuleProofManifest) -> Result<(), ProofError> {
    let expected = render_status(manifest);
    let path = root.join(STATUS_PATH);
    let existing = fs::read_to_string(&path).map_err(|error| {
        ProofError::new(format!("{STATUS_PATH}: cannot read generated status: {error}"))
    })?;
    if existing != expected {
        return Err(ProofError::new(format!(
            "{STATUS_PATH} is out of date; run `cargo xtask critic-rule-proof write-status`"
        )));
    }
    Ok(())
}

/// Write generated status markdown.
pub fn write_status(root: &Path, manifest: &RuleProofManifest) -> Result<(), ProofError> {
    let markdown = render_status(manifest);
    let path = root.join(STATUS_PATH);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            ProofError::new(format!("{}: cannot create parent: {error}", parent.display()))
        })?;
    }
    fs::write(&path, markdown)
        .map_err(|error| ProofError::new(format!("{STATUS_PATH}: cannot write: {error}")))
}

fn classes_for_rule(manifest: &RuleProofManifest, rule_id: &str) -> BTreeSet<EvidenceClass> {
    manifest
        .cases
        .iter()
        .filter(|case| case.rule_id == rule_id)
        .flat_map(|case| case.evidence_classes.iter().copied())
        .collect()
}

fn class_status(class: EvidenceClass, present: bool, automatic_applicable: bool) -> ClassStatus {
    if class == EvidenceClass::AutomaticFixRoundTrip && !automatic_applicable {
        return if present { ClassStatus::Present } else { ClassStatus::NotApplicable };
    }
    if present { ClassStatus::Present } else { ClassStatus::Missing }
}
