//! Carmel build-system marker, root, and dev-state detection.
//!
//! Source receipt: plan S8 / Lane D research contract on #13642, pinned to
//! Carmel master `v0.9.2` (`lib/Carmel/{App,Environment,Setup}.pm` plus
//! Carton's `Carton::Snapshot`/`Emitter`), fetched 2026-08-30 (UTC).
//!
//! Detection is bounded and non-executing: marker existence checks plus one
//! bounded read of the generated dev-state file `.carmel/MySetup.pm`. No
//! process is run, no directory is enumerated, and the ambient central
//! artifact repository (`$HOME/.carmel/{version}-{archname}` or
//! `PERL_CARMEL_REPO`) is never walked: dev-mode artifact roots come only
//! from the already-serialized `inc` list embedded in `MySetup.pm`, in
//! producer order.
//!
//! Authority mapping (contract §3, aligned to [`crate::environment`]
//! enums):
//!
//! - Post-rollout `local/lib/perl5` is a [`ProjectRootRole::Local`] /
//!   [`IncludeEntryRole::LocalLib`] candidate at
//!   [`EnvironmentInputAuthority::WorkspaceConvention`] — and only when the
//!   `local/.carmel` sentinel marks the tree as Carmel rollout output.
//!   Without the sentinel a `local/` tree is ambiguous with
//!   Carton/local::lib and must never claim Carmel.
//! - Dev-mode artifact roots are out-of-workspace, interpreter-keyed
//!   absolute paths. They ride [`IncludeEntryRole::BlibLib`],
//!   [`IncludeEntryRole::BlibArch`], or [`IncludeEntryRole::Other`] (the
//!   contract's open question 2 resolves to reviewed shape roles plus a
//!   Carmel explanation code, inside additive v1) at
//!   [`EnvironmentInputAuthority::Ambient`] — or become
//!   [`EnvironmentLimitation`] entries when untrusted. They must never flow
//!   through a workspace-relative literal detector (#4998 gate).
//! - The central repository directory itself is never a root; only
//!   per-artifact leaf directories are.

use std::path::{Path, PathBuf};

use crate::environment::{EnvironmentLimitation, IncludeEntryRole};

/// Explanation code for dev-mode artifact include candidates.
pub const CARMEL_ARTIFACT_EXPLANATION_CODE: &str = "carmel_artifact";

/// Explanation code for the Carton/Carmel lock-ambiguity window: a
/// `cpanfile.snapshot` is present but no marker identifies its producer
/// (the Carton-format header has no producer field), so no root candidate
/// may be attributed to Carmel; resolution requires explicit configuration.
pub const MANAGER_AMBIGUOUS_EXPLANATION_CODE: &str = "manager_ambiguous";

/// Limitation code for an embedded dev-mode artifact path that no longer
/// exists on the host.
pub const CARMEL_ARTIFACT_MISSING_LIMITATION: &str = "carmel_artifact_missing";

/// Limitation code for an embedded install-time `base` that no longer
/// matches the current project root (relocated project).
pub const CARMEL_BASE_MISMATCH_LIMITATION: &str = "carmel_base_mismatch";

/// Limitation code for a `.carmel/MySetup.pm` marker that exists but whose
/// embedded environment could not be parsed within the bounded read.
pub const CARMEL_DEV_STATE_UNPARSABLE_LIMITATION: &str = "carmel_dev_state_unparsable";

/// Declaration marker. Never installed-root evidence by itself (contract §1,
/// inherited from #2530).
pub const CPANFILE_MARKER: &str = "cpanfile";

/// Lock marker written by `carmel install` next to the located cpanfile.
/// Format is Carton snapshot v1.0 even when Carmel wrote it; there is no
/// producer field, so content alone cannot distinguish Carton from Carmel.
pub const CPANFILE_SNAPSHOT_MARKER: &str = "cpanfile.snapshot";

/// Discriminating Carmel dev-state marker generated by `carmel install`.
pub const DEV_STATE_MARKER: &str = ".carmel/MySetup.pm";

/// Post-rollout sentinel touched by `carmel rollout`; marks `local/` as
/// Carmel rollout output rather than a plain local::lib/Carton tree.
pub const ROLLOUT_SENTINEL_MARKER: &str = "local/.carmel";

/// Post-rollout include root: the single include root of the standard
/// ExtUtils::InstallPaths `local/` install-base tree.
pub const ROLLOUT_INCLUDE_PATH: &str = "local/lib/perl5";

/// Authority class for the post-rollout root candidate.
pub const ROLLOUT_ROOT_AUTHORITY: crate::environment::EnvironmentInputAuthority =
    crate::environment::EnvironmentInputAuthority::WorkspaceConvention;

/// Authority class for dev-mode artifact candidates: ambient central
/// repository state that must never become project authority without
/// explicit trust.
pub const DEV_ARTIFACT_AUTHORITY: crate::environment::EnvironmentInputAuthority =
    crate::environment::EnvironmentInputAuthority::Ambient;

/// Watcher inputs for metadata invalidation (#13640): the five
/// workspace-relative invalidation inputs. The selected interpreter identity
/// is also an invalidation input (the central repo is
/// `{version}-{archname}` keyed) but is an interpreter-selection event, not
/// a watcher glob; the out-of-workspace ambient repository is deliberately
/// not watched (contract §4, §7(5)).
pub const WATCHER_INPUTS: &[&str] = &[
    CPANFILE_MARKER,
    CPANFILE_SNAPSHOT_MARKER,
    DEV_STATE_MARKER,
    ROLLOUT_SENTINEL_MARKER,
    ROLLOUT_INCLUDE_PATH,
];

/// Upper bound for the bounded read of `.carmel/MySetup.pm`. The embedded
/// `inc`/`base` fields are serialized before the potentially large
/// `modules`/`prereqs` maps (Carmel's `quote` sorts hash keys, so `base` and
/// `inc` precede them), so a bounded prefix carries everything this module
/// parses.
const DEV_STATE_READ_LIMIT: u64 = 1024 * 1024;

/// One dev-mode artifact include-root candidate parsed from
/// `.carmel/MySetup.pm`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CarmelArtifactRoot {
    /// Absolute artifact path (typically under the central repository), in
    /// embedded producer order.
    pub path: String,
    /// Reviewed include role by artifact shape.
    pub role: IncludeEntryRole,
    /// Producer-local stable order; never recomputed (contract §3).
    pub source_order: u32,
    /// Whether the path currently exists on the host.
    pub exists: bool,
}

/// Facts parsed from a `.carmel/MySetup.pm` environment block.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct MySetupFacts {
    /// Embedded `inc` artifact roots, producer order preserved. `None` means
    /// the field could not be parsed within the bounded read — an explicit
    /// unknown, never an assumed-empty list.
    pub inc: Option<Vec<String>>,
    /// Embedded absolute install-time cwd (`base`), when parsed.
    pub base: Option<String>,
}

/// Attribution of a present `cpanfile.snapshot` lock.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CarmelLockAttribution {
    /// No `cpanfile.snapshot` in this project.
    Absent,
    /// The lock's producer is identified by a discriminating Carmel marker
    /// (dev state or rollout sentinel).
    CarmelMarker,
    /// The lock is present but its producer cannot be identified from
    /// content (Carton-format header, no producer field) or from any
    /// discriminating marker. This is the Carton/Carmel ambiguity window:
    /// record [`MANAGER_AMBIGUOUS_EXPLANATION_CODE`] and no Carmel root
    /// candidates.
    Ambiguous,
}

/// Bounded, deterministic Carmel detection for one workspace root.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CarmelDetection {
    /// `cpanfile` declaration marker present.
    pub cpanfile_present: bool,
    /// `cpanfile.snapshot` lock marker present.
    pub snapshot_present: bool,
    /// `.carmel/MySetup.pm` dev-state marker present.
    pub dev_state_present: bool,
    /// `local/.carmel` rollout sentinel present.
    pub rollout_sentinel_present: bool,
    /// A discriminating Carmel marker (dev state or rollout sentinel) is
    /// present, so Carmel identity holds.
    pub is_carmel: bool,
    /// Attribution of the `cpanfile.snapshot` lock.
    pub lock: CarmelLockAttribution,
    /// Post-rollout root candidate (`local/lib/perl5`). Present only with
    /// the `local/.carmel` sentinel; a workspace-relative literal at
    /// [`ROLLOUT_ROOT_AUTHORITY`].
    pub rollout_root: Option<&'static str>,
    /// Parsed dev-state facts. `None` when the marker is absent or could not
    /// be parsed (see `limitations`).
    pub dev_state: Option<MySetupFacts>,
    /// Dev-mode artifact candidates in producer order, with host existence.
    /// Empty unless dev state parsed.
    pub artifact_roots: Vec<CarmelArtifactRoot>,
    /// Explicit limitations: unparsable dev state, missing artifacts,
    /// relocated `base`.
    pub limitations: Vec<EnvironmentLimitation>,
}

/// Detect Carmel markers, roots, and dev state for `workspace_root`.
///
/// Bounded and non-executing: marker existence checks plus one bounded read
/// of `.carmel/MySetup.pm`. Deterministic for a fixed filesystem view: the
/// artifact candidate list is the embedded serialized list in producer
/// order, never recomputed, and the post-rollout root is one fixed relative
/// literal.
#[must_use]
pub fn detect_carmel(workspace_root: &Path) -> CarmelDetection {
    let cpanfile_present = workspace_root.join(CPANFILE_MARKER).is_file();
    let snapshot_present = workspace_root.join(CPANFILE_SNAPSHOT_MARKER).is_file();
    let dev_state_present = workspace_root.join(DEV_STATE_MARKER).is_file();
    let rollout_sentinel_present = workspace_root.join(ROLLOUT_SENTINEL_MARKER).exists();

    let is_carmel = dev_state_present || rollout_sentinel_present;

    let lock = if !snapshot_present {
        CarmelLockAttribution::Absent
    } else if is_carmel {
        CarmelLockAttribution::CarmelMarker
    } else {
        // Ambiguity window (contract §7(1)): the lock alone — written in the
        // shared Carton format with no producer field — cannot identify its
        // producer. No Carmel root candidates are attributed; resolution
        // requires explicit configuration.
        CarmelLockAttribution::Ambiguous
    };

    let rollout_root = if rollout_sentinel_present { Some(ROLLOUT_INCLUDE_PATH) } else { None };

    let mut limitations = Vec::new();
    let mut dev_state = None;
    let mut artifact_roots = Vec::new();

    if dev_state_present {
        match read_bounded(&workspace_root.join(DEV_STATE_MARKER)) {
            Some(source) => match parse_mysetup_environment(&source) {
                Some(facts) => {
                    match &facts.inc {
                        Some(inc) => {
                            for (source_order, path) in inc.iter().enumerate() {
                                let exists = Path::new(path).exists();
                                if !exists {
                                    limitations.push(EnvironmentLimitation {
                                        code: CARMEL_ARTIFACT_MISSING_LIMITATION.to_string(),
                                        detail: format!(
                                            "embedded dev artifact path does not exist: {path}"
                                        ),
                                        input_id: None,
                                    });
                                }
                                artifact_roots.push(CarmelArtifactRoot {
                                    path: path.clone(),
                                    role: artifact_role(path),
                                    source_order: source_order as u32,
                                    exists,
                                });
                            }
                        }
                        None => limitations.push(EnvironmentLimitation {
                            code: CARMEL_DEV_STATE_UNPARSABLE_LIMITATION.to_string(),
                            detail: "dev-state marker exists but its embedded 'inc' \
                                     list could not be parsed within the bounded read"
                                .to_string(),
                            input_id: None,
                        }),
                    }
                    if let Some(base) = facts
                        .base
                        .as_deref()
                        .filter(|base| is_relocated_base(workspace_root, base))
                    {
                        limitations.push(EnvironmentLimitation {
                            code: CARMEL_BASE_MISMATCH_LIMITATION.to_string(),
                            detail: format!(
                                "embedded install-time base does not match the current \
                                 project root: {base}"
                            ),
                            input_id: None,
                        });
                    }
                    dev_state = Some(facts);
                }
                None => limitations.push(EnvironmentLimitation {
                    code: CARMEL_DEV_STATE_UNPARSABLE_LIMITATION.to_string(),
                    detail: "dev-state marker exists but no MySetup environment block \
                             was found within the bounded read"
                        .to_string(),
                    input_id: None,
                }),
            },
            None => limitations.push(EnvironmentLimitation {
                code: CARMEL_DEV_STATE_UNPARSABLE_LIMITATION.to_string(),
                detail: "dev-state marker exists but could not be read within the \
                         bounded read"
                    .to_string(),
                input_id: None,
            }),
        }
    }

    CarmelDetection {
        cpanfile_present,
        snapshot_present,
        dev_state_present,
        rollout_sentinel_present,
        is_carmel,
        lock,
        rollout_root,
        dev_state,
        artifact_roots,
        limitations,
    }
}

/// Map one embedded artifact path to its reviewed include role by shape:
/// `…/blib/arch` → [`IncludeEntryRole::BlibArch`], `…/blib/lib` →
/// [`IncludeEntryRole::BlibLib`], anything else → [`IncludeEntryRole::Other`].
fn artifact_role(path: &str) -> IncludeEntryRole {
    let path = Path::new(path);
    let leaf = path.file_name().and_then(|name| name.to_str());
    let parent = path.parent().and_then(Path::file_name).and_then(|name| name.to_str());
    match (leaf, parent) {
        (Some("arch"), Some("blib")) => IncludeEntryRole::BlibArch,
        (Some("lib"), Some("blib")) => IncludeEntryRole::BlibLib,
        _ => IncludeEntryRole::Other,
    }
}

/// Whether the embedded install-time `base` no longer matches the current
/// project root. Canonical comparison when the host resolves both sides,
/// lexical otherwise.
fn is_relocated_base(workspace_root: &Path, base: &str) -> bool {
    let base = PathBuf::from(base);
    match (std::fs::canonicalize(workspace_root), std::fs::canonicalize(&base)) {
        (Ok(current), Ok(base)) => current != base,
        _ => workspace_root != base,
    }
}

/// Read at most [`DEV_STATE_READ_LIMIT`] bytes of `path` as UTF-8.
fn read_bounded(path: &Path) -> Option<String> {
    use std::io::Read;

    let metadata = std::fs::metadata(path).ok()?;
    if !metadata.is_file() {
        return None;
    }
    let bound = metadata.len().min(DEV_STATE_READ_LIMIT) as usize;
    let mut file = std::fs::File::open(path).ok()?;
    let mut buffer = vec![0u8; bound];
    let mut total = 0;
    while total < bound {
        match file.read(&mut buffer[total..]) {
            Ok(0) => break,
            Ok(read) => total += read,
            Err(_) => return None,
        }
    }
    String::from_utf8(buffer[..total].to_vec()).ok()
}

/// Parse the embedded environment of a generated `.carmel/MySetup.pm`.
///
/// The file is generated by `Carmel::App::dump_bootstrap` as valid Perl:
///
/// ```text
/// our %environment = (
///   'inc' => [ '<artifact>', … ],
///   'base' => '<absolute cwd>',
///   …
/// );
/// ```
///
/// where values are serialized by `Data::Dumper` (`Sortkeys(1)->Terse(1)->
/// Indent(1)`), re-indented by Carmel's `quote`: single-quoted strings with
/// `\'`/`\\` escapes, order-preserving arrays, sorted hash keys. Parsing is
/// a bounded structural scan of that shape — never Perl evaluation.
///
/// Returns `None` when the `%environment` anchor is absent (the marker is
/// then not usable as dev-state evidence). Individual fields that fail to
/// scan are reported as `None` instead of an assumed-empty value.
#[must_use]
pub fn parse_mysetup_environment(source: &str) -> Option<MySetupFacts> {
    let mut scanner = Scanner::new(source);
    scanner.find_anchor("%environment")?;
    scanner.skip_until('(')?;

    let mut facts = MySetupFacts::default();
    loop {
        scanner.skip_separators();
        match scanner.peek() {
            Some(')') | None => break,
            Some('\'') => {}
            Some(_) => return Some(facts),
        }
        let Some(key) = scanner.read_single_quoted() else { break };
        scanner.skip_separators();
        if !scanner.consume_pair('=', '>') {
            return Some(facts);
        }
        scanner.skip_separators();
        match scanner.peek() {
            Some('[') => {
                let start = scanner.pos;
                let items = scanner.read_string_array();
                if items.is_none() {
                    // Malformed array: the field stays an explicit unknown,
                    // but later top-level entries still parse.
                    scanner.pos = start;
                    if scanner.skip_balanced('[', ']').is_none() {
                        return Some(facts);
                    }
                } else if key == "inc" {
                    facts.inc = items;
                }
            }
            Some('\'') => {
                let value = scanner.read_single_quoted();
                if key == "base" {
                    facts.base = value;
                }
            }
            Some('{') => {
                if scanner.skip_balanced('{', '}').is_none() {
                    return Some(facts);
                }
            }
            _ => return Some(facts),
        }
    }
    Some(facts)
}

/// Bounded structural scanner over generated-Perl text.
struct Scanner<'a> {
    source: &'a str,
    bytes: &'a [u8],
    pos: usize,
}

impl<'a> Scanner<'a> {
    fn new(source: &'a str) -> Self {
        Self { source, bytes: source.as_bytes(), pos: 0 }
    }

    fn peek(&self) -> Option<char> {
        self.source[self.pos..].chars().next()
    }

    /// Advance past one ASCII char if present.
    fn bump(&mut self) {
        if self.pos < self.bytes.len() {
            let mut next = self.pos + 1;
            while next < self.bytes.len() && (self.bytes[next] & 0xC0) == 0x80 {
                next += 1;
            }
            self.pos = next;
        }
    }

    /// Find a literal needle from the current position; park behind it.
    fn find_anchor(&mut self, needle: &str) -> Option<()> {
        let from = self.source[self.pos..].find(needle)?;
        self.pos += from + needle.len();
        Some(())
    }

    /// Advance to just after the next occurrence of `target`.
    fn skip_until(&mut self, target: char) -> Option<()> {
        let from = self.source[self.pos..].find(target)?;
        self.pos += from + target.len_utf8();
        Some(())
    }

    /// Skip whitespace, newlines, and commas.
    fn skip_separators(&mut self) {
        while let Some(ch) = self.peek() {
            if ch.is_whitespace() || ch == ',' {
                self.bump();
            } else {
                break;
            }
        }
    }

    /// Consume a two-char token such as `=>`.
    fn consume_pair(&mut self, first: char, second: char) -> bool {
        if self.peek() != Some(first) {
            return false;
        }
        let after_first = self.pos + first.len_utf8();
        if self.source[after_first..].starts_with(second) {
            self.pos = after_first + second.len_utf8();
            true
        } else {
            false
        }
    }

    /// Read a single-quoted Perl string with `\'` and `\\` unescaping.
    fn read_single_quoted(&mut self) -> Option<String> {
        if self.peek() != Some('\'') {
            return None;
        }
        self.bump();
        let mut value = String::new();
        loop {
            let ch = self.peek()?;
            self.bump();
            match ch {
                '\'' => return Some(value),
                '\\' => {
                    let escaped = self.peek()?;
                    self.bump();
                    value.push(escaped);
                }
                _ => value.push(ch),
            }
        }
    }

    /// Read a `[ 'a', 'b', … ]` array of single-quoted strings. Returns
    /// `None` when the array or any element fails to scan.
    fn read_string_array(&mut self) -> Option<Vec<String>> {
        if self.peek() != Some('[') {
            return None;
        }
        self.bump();
        let mut items = Vec::new();
        loop {
            self.skip_separators();
            match self.peek()? {
                ']' => {
                    self.bump();
                    return Some(items);
                }
                '\'' => {
                    items.push(self.read_single_quoted()?);
                }
                _ => return None,
            }
        }
    }

    /// Skip a balanced `{…}` or `[…]` block, honoring single-quoted strings.
    fn skip_balanced(&mut self, open: char, close: char) -> Option<()> {
        if self.peek() != Some(open) {
            return None;
        }
        self.bump();
        let mut depth = 1usize;
        while depth > 0 {
            let ch = self.peek()?;
            self.bump();
            if ch == '\'' {
                // Skip the string body without counting structural chars.
                loop {
                    let inner = self.peek()?;
                    self.bump();
                    if inner == '\'' {
                        break;
                    }
                    if inner == '\\' {
                        let escaped = self.peek()?;
                        self.bump();
                        let _ = escaped;
                    }
                }
            } else if ch == open {
                depth += 1;
            } else if ch == close {
                depth = depth.saturating_sub(1);
            }
        }
        Some(())
    }
}

#[cfg(test)]
mod tests {
    #![expect(
        clippy::expect_used,
        reason = "fixture setup may fail loudly; same tracked conversion debt as builder.rs: \
                  https://github.com/EffortlessMetrics/perl-lsp-swarm/issues/3021"
    )]
    use super::*;
    use crate::environment::{BuildSystemFactRef, BuildSystemKind, EnvironmentInputAuthority};

    /// Digest-compatible fingerprint material for fact refs in tests.
    fn fixture_fingerprint(tag: &str) -> crate::Digest {
        crate::Digest::of(tag)
    }

    fn fixture_input(tag: &str) -> crate::environment::EnvironmentInputId {
        crate::environment::EnvironmentInput::new(
            format!("test.{tag}"),
            EnvironmentInputAuthority::WorkspaceConvention,
            crate::environment::EnvironmentInputState::Accepted,
            "carmel-fixture",
            Some(crate::Digest::of(tag)),
            CARMEL_ARTIFACT_EXPLANATION_CODE,
        )
        .id
    }

    /// Fixture fixture list per contract §6 R1: dev-mode, rolled-out,
    /// snapshot-without-`.carmel`, `.carmel`-without-snapshot, partial
    /// artifacts, relocated `base`, both-managers-present, untrusted
    /// workspace, and bare declaration.
    struct Fixture {
        root: PathBuf,
    }

    impl Fixture {
        fn new(tag: &str) -> Self {
            let root = std::env::temp_dir().join(format!("pwc-carmel-{tag}"));
            let _ = std::fs::remove_dir_all(&root);
            std::fs::create_dir_all(&root).expect("test fixture root");
            Self { root }
        }

        fn write(&self, rel: &str, content: &str) {
            let path = self.root.join(rel);
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent).expect("test fixture dir");
            }
            std::fs::write(path, content).expect("test fixture file");
        }

        fn dir(&self, rel: &str) {
            std::fs::create_dir_all(self.root.join(rel)).expect("test fixture dir");
        }
    }

    impl Drop for Fixture {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.root);
        }
    }

    /// Generated MySetup shape per Carmel::App::dump_bootstrap with
    /// Data::Dumper `Sortkeys(1)->Terse(1)->Indent(1)` + Carmel `quote`
    /// re-indentation: sorted top-level keys, single-quoted strings.
    const MYSETUP: &str = r#"# DO NOT EDIT! Auto-generated via carmel install.
package Carmel::MySetup;

use strict;

our %environment = (
  'base' => '/home/dev/project',
  'execs' => {},
  'inc' => [
    '/home/dev/.carmel/5.38.0-x86_64-linux/builds/JSON-PP-4.16/blib/arch',
    '/home/dev/.carmel/5.38.0-x86_64-linux/builds/JSON-PP-4.16/blib/lib'
  ],
  'modules' => {
    'JSON::PP' => '/home/dev/.carmel/5.38.0-x86_64-linux/builds/JSON-PP-4.16/blib/lib/JSON/PP.pm'
  },
  'path' => [
    '/home/dev/.carmel/5.38.0-x86_64-linux/builds/JSON-PP-4.16/blib/script',
    '/home/dev/.carmel/5.38.0-x86_64-linux/builds/JSON-PP-4.16/blib/bin'
  ],
  'prereqs' => {
    'runtime' => {
      'requires' => {
        'JSON::PP' => '4.16'
      }
    }
  }
);

1;
"#;

    #[test]
    fn build_system_kind_carmel_has_distinct_stable_identity() {
        let fingerprint = fixture_fingerprint("fixture");
        let input = fixture_input("input");
        let carmel =
            BuildSystemFactRef::new(BuildSystemKind::Carmel, fingerprint.clone(), input.clone());
        let carton = BuildSystemFactRef::new(BuildSystemKind::Carton, fingerprint, input);
        assert_ne!(carmel.id, carton.id, "Carmel must not share Carton's build-system identity");
    }

    #[test]
    fn parses_embedded_inc_in_producer_order_with_base() {
        let facts = parse_mysetup_environment(MYSETUP).expect("generated shape parses");
        let inc = facts.inc.expect("inc present");
        assert_eq!(
            inc,
            vec![
                "/home/dev/.carmel/5.38.0-x86_64-linux/builds/JSON-PP-4.16/blib/arch",
                "/home/dev/.carmel/5.38.0-x86_64-linux/builds/JSON-PP-4.16/blib/lib"
            ]
        );
        assert_eq!(facts.base.as_deref(), Some("/home/dev/project"));
    }

    #[test]
    fn parses_escaped_and_empty_artifact_entries() {
        // Perl single-quote escapes: `\\` is one backslash, `\'` is one quote
        // (Data::Dumper emits exactly these inside single-quoted strings).
        let source = concat!(
            "our %environment = (\n",
            "  'inc' => [\n",
            "    'C:\\\\repo\\\\blib\\\\arch',\n",
            "    'it\\'s/blib/lib'\n",
            "  ],\n",
            "  'base' => '',\n",
            ");\n",
            "1;\n"
        );
        let facts = parse_mysetup_environment(source).expect("parses");
        assert_eq!(
            facts.inc.as_deref(),
            Some(&["C:\\repo\\blib\\arch".to_string(), "it's/blib/lib".to_string()][..])
        );
        assert_eq!(facts.base.as_deref(), Some(""));
    }

    #[test]
    fn missing_anchor_is_explicit_none() {
        assert!(parse_mysetup_environment("package Other; 1;").is_none());
    }

    #[test]
    fn malformed_inc_is_none_not_assumed_empty() {
        let source =
            "our %environment = (\n  'inc' => [\n    'ok',\n    42,\n  ],\n  'base' => '/x',\n);\n";
        let facts = parse_mysetup_environment(source).expect("anchor found");
        assert!(facts.inc.is_none(), "malformed array must not read as empty");
        assert_eq!(facts.base.as_deref(), Some("/x"));
    }

    #[test]
    fn dev_mode_fixture_yields_ambient_artifact_candidates() {
        let fixture = Fixture::new("dev-mode");
        fixture.write("cpanfile", "requires 'JSON::PP';\n");
        fixture.write("cpanfile.snapshot", "# carton snapshot format: version 1.0\n");
        fixture.write(".carmel/MySetup.pm", MYSETUP);

        let detection = detect_carmel(&fixture.root);
        assert!(detection.cpanfile_present);
        assert!(detection.snapshot_present);
        assert!(detection.dev_state_present);
        assert!(!detection.rollout_sentinel_present);
        assert!(detection.is_carmel, "dev state is the discriminating marker");
        assert_eq!(detection.lock, CarmelLockAttribution::CarmelMarker);
        assert!(detection.rollout_root.is_none(), "dev mode has no project-local root");
        let roots: Vec<&str> =
            detection.artifact_roots.iter().map(|root| root.path.as_str()).collect();
        assert_eq!(
            roots,
            [
                "/home/dev/.carmel/5.38.0-x86_64-linux/builds/JSON-PP-4.16/blib/arch",
                "/home/dev/.carmel/5.38.0-x86_64-linux/builds/JSON-PP-4.16/blib/lib"
            ]
        );
        assert!(
            detection.artifact_roots.iter().all(|root| !root.exists),
            "fixture artifact paths are host-external"
        );
        assert_eq!(
            detection.artifact_roots.iter().map(|root| root.role).collect::<Vec<_>>(),
            vec![IncludeEntryRole::BlibArch, IncludeEntryRole::BlibLib]
        );
        assert!(
            detection
                .limitations
                .iter()
                .any(|item| item.code == CARMEL_ARTIFACT_MISSING_LIMITATION),
            "host-external fixture paths report missing-artifact limitations"
        );
        assert!(
            detection.limitations.iter().all(|item| {
                item.code == CARMEL_ARTIFACT_MISSING_LIMITATION
                    || item.code == CARMEL_BASE_MISMATCH_LIMITATION
            }),
            "no unexpected limitation codes: {:?}",
            detection.limitations
        );
        // The embedded base never matches the temp fixture root.
        assert!(
            detection.limitations.iter().any(|item| item.code == CARMEL_BASE_MISMATCH_LIMITATION)
        );
    }

    #[test]
    fn rolled_out_fixture_yields_sentinel_root_only() {
        let fixture = Fixture::new("rolled-out");
        fixture.write("cpanfile", "requires 'JSON::PP';\n");
        fixture.write("cpanfile.snapshot", "# carton snapshot format: version 1.0\n");
        fixture.write("local/.carmel", "");
        fixture.dir("local/lib/perl5");

        let detection = detect_carmel(&fixture.root);
        assert!(detection.is_carmel);
        assert!(!detection.dev_state_present);
        assert_eq!(detection.lock, CarmelLockAttribution::CarmelMarker);
        assert_eq!(detection.rollout_root, Some(ROLLOUT_INCLUDE_PATH));
        assert!(detection.artifact_roots.is_empty());
        assert_eq!(ROLLOUT_ROOT_AUTHORITY, EnvironmentInputAuthority::WorkspaceConvention);
    }

    #[test]
    fn snapshot_without_carmel_markers_is_manager_ambiguous_with_no_roots() {
        let fixture = Fixture::new("snapshot-ambiguous");
        fixture.write("cpanfile", "requires 'JSON::PP';\n");
        fixture.write("cpanfile.snapshot", "# carton snapshot format: version 1.0\n");

        let detection = detect_carmel(&fixture.root);
        assert!(!detection.is_carmel, "lock content cannot claim Carmel");
        assert_eq!(detection.lock, CarmelLockAttribution::Ambiguous);
        assert_eq!(MANAGER_AMBIGUOUS_EXPLANATION_CODE, "manager_ambiguous");
        assert!(detection.rollout_root.is_none(), "ambiguity attributes no Carmel root");
        assert!(detection.artifact_roots.is_empty());
    }

    #[test]
    fn dev_state_without_snapshot_is_identified_without_ambiguity() {
        let fixture = Fixture::new("devstate-no-snapshot");
        fixture.write("cpanfile", "requires 'JSON::PP';\n");
        fixture.write(".carmel/MySetup.pm", MYSETUP);

        let detection = detect_carmel(&fixture.root);
        assert!(detection.is_carmel);
        assert!(!detection.snapshot_present);
        assert_eq!(detection.lock, CarmelLockAttribution::Absent);
        assert_eq!(
            detection.dev_state.as_ref().and_then(|facts| facts.inc.as_ref()).map(Vec::len),
            Some(2)
        );
    }

    #[test]
    fn unparsable_dev_state_is_an_explicit_limitation() {
        let fixture = Fixture::new("devstate-corrupt");
        fixture.write("cpanfile", "requires 'JSON::PP';\n");
        fixture.write(".carmel/MySetup.pm", "package NotMySetup; 1;\n");

        let detection = detect_carmel(&fixture.root);
        assert!(detection.dev_state_present);
        assert!(detection.dev_state.is_none());
        assert!(detection.artifact_roots.is_empty());
        assert!(
            detection
                .limitations
                .iter()
                .any(|item| item.code == CARMEL_DEV_STATE_UNPARSABLE_LIMITATION)
        );
    }

    #[test]
    fn both_managers_present_keeps_carmel_identity() {
        let fixture = Fixture::new("both-managers");
        fixture.write("cpanfile", "requires 'JSON::PP';\n");
        fixture.write("carton.lock", "snapshot\n");
        fixture.write("cpanfile.snapshot", "# carton snapshot format: version 1.0\n");
        fixture.write(".carmel/MySetup.pm", MYSETUP);

        let detection = detect_carmel(&fixture.root);
        assert!(detection.is_carmel);
        assert_eq!(detection.lock, CarmelLockAttribution::CarmelMarker);
        assert!(!detection.artifact_roots.is_empty());
    }

    #[test]
    fn bare_cpanfile_declaration_is_not_carmel_and_never_a_root() {
        let fixture = Fixture::new("bare-cpanfile");
        fixture.write("cpanfile", "requires 'JSON::PP';\n");

        let detection = detect_carmel(&fixture.root);
        assert!(!detection.is_carmel);
        assert_eq!(detection.lock, CarmelLockAttribution::Absent);
        assert!(detection.rollout_root.is_none());
        assert!(detection.artifact_roots.is_empty());
        assert!(detection.limitations.is_empty());
    }

    #[test]
    fn watcher_inputs_are_the_five_relative_globs() {
        assert_eq!(
            WATCHER_INPUTS,
            [
                "cpanfile",
                "cpanfile.snapshot",
                ".carmel/MySetup.pm",
                "local/.carmel",
                "local/lib/perl5"
            ]
        );
        for input in WATCHER_INPUTS {
            let path = Path::new(input);
            assert!(!path.is_absolute(), "watcher input must stay relative: {input}");
        }
        assert_eq!(DEV_ARTIFACT_AUTHORITY, EnvironmentInputAuthority::Ambient);
    }

    #[test]
    fn authority_constants_match_contract_mapping() {
        assert_eq!(ROLLOUT_ROOT_AUTHORITY, EnvironmentInputAuthority::WorkspaceConvention);
        assert_eq!(DEV_ARTIFACT_AUTHORITY, EnvironmentInputAuthority::Ambient);
        assert_eq!(CARMEL_ARTIFACT_EXPLANATION_CODE, "carmel_artifact");
    }
}
