//! BDD tests for textDocument/inlayHint config enforcement and hint correctness.
//!
//! Covers:
//! - Default (enabled) behaviour: parameter and type hints are generated
//! - `inlayHints.enabled = false` returns an empty array
//! - `inlayHints.parameterHints = false` suppresses parameter-kind hints
//! - `inlayHints.typeHints = false` suppresses type-kind hints
//! - `inlayHints.maxLength` truncates long hint labels
//! - Mixed config: type hints on, parameter hints off
//! - substr smoke: parameter hints are generated by default

mod support;
use serde_json::json;
use serial_test::serial;
use support::lsp_harness::LspHarness;

type TestResult = Result<(), Box<dyn std::error::Error>>;
type HintResult = Result<serde_json::Value, Box<dyn std::error::Error>>;

/// Inlay-hint capability block sent during initialization.
fn inlay_hint_caps() -> serde_json::Value {
    json!({
        "textDocument": {
            "inlayHint": {
                "dynamicRegistration": true,
                "resolveSupport": { "properties": ["tooltip"] }
            }
        }
    })
}

/// Send `workspace/didChangeConfiguration` with the given inlayHints sub-object.
fn configure_inlay_hints(harness: &mut LspHarness, inlay_settings: serde_json::Value) {
    harness.notify(
        "workspace/didChangeConfiguration",
        json!({ "settings": { "perl": { "inlayHints": inlay_settings } } }),
    );
}

/// Request inlay hints for the full first 20 lines of `uri`.
fn request_hints(harness: &mut LspHarness, uri: &str) -> HintResult {
    harness
        .request(
            "textDocument/inlayHint",
            json!({
                "textDocument": { "uri": uri },
                "range": {
                    "start": { "line": 0, "character": 0 },
                    "end":   { "line": 20, "character": 0 }
                }
            }),
        )
        .map_err(|e| e.into())
}

// ---------------------------------------------------------------------------
// Smoke: default config produces hints
// ---------------------------------------------------------------------------

#[test]
#[serial]
fn inlay_hints_for_substr_and_types() -> TestResult {
    let mut harness = LspHarness::new();
    harness.initialize(Some(inlay_hint_caps()))?;

    let uri = "file:///hints_smoke.pl";
    let text = r#"my $s = "abcd"; my $x = substr($s, 1, 2);"#;
    harness.open(uri, text)?;

    let result = request_hints(&mut harness, uri)?;
    let hints = result.as_array().ok_or("inlayHint should return an array")?;

    assert!(!hints.is_empty(), "default config should produce hints");

    for hint in hints {
        assert!(hint.get("position").is_some(), "every hint needs a position");
        assert!(hint.get("label").is_some(), "every hint needs a label");
    }

    let labels: Vec<&str> = hints.iter().filter_map(|h| h["label"].as_str()).collect();

    let has_substr_param = ["expr:", "offset:", "length:"].iter().any(|p| labels.contains(p));
    assert!(
        has_substr_param,
        "should have substr parameter hints in default config; got {labels:?}"
    );

    Ok(())
}

// ---------------------------------------------------------------------------
// Config: enabled = false returns an empty response.
// ---------------------------------------------------------------------------

#[test]
#[serial]
fn inlay_hints_disabled_returns_empty_array() -> TestResult {
    let mut harness = LspHarness::new();
    harness.initialize(Some(inlay_hint_caps()))?;

    configure_inlay_hints(&mut harness, json!({ "enabled": false }));

    let uri = "file:///hints_disabled.pl";
    harness.open(uri, r#"my $x = substr("hello", 1, 3); my $n = 42;"#)?;

    let result = request_hints(&mut harness, uri)?;
    let hints = result.as_array().ok_or("should return an array even when disabled")?;

    assert!(hints.is_empty(), "inlayHints.enabled=false must produce zero hints; got {hints:?}");

    Ok(())
}

// ---------------------------------------------------------------------------
// Config: parameterHints = false suppresses parameter-kind hints (kind == 2).
// ---------------------------------------------------------------------------

#[test]
#[serial]
fn inlay_hints_parameter_hints_disabled_suppresses_param_kind() -> TestResult {
    let mut harness = LspHarness::new();
    harness.initialize(Some(inlay_hint_caps()))?;

    configure_inlay_hints(
        &mut harness,
        json!({ "enabled": true, "parameterHints": false, "typeHints": true }),
    );

    let uri = "file:///hints_no_params.pl";
    // substr has three parameters; with parameterHints=false those should not appear.
    harness.open(uri, r#"my $x = substr("hello", 1, 3);"#)?;

    let result = request_hints(&mut harness, uri)?;
    let hints = result.as_array().ok_or("should return an array")?;

    let param_hints: Vec<_> = hints.iter().filter(|h| h["kind"] == 2).collect();
    assert!(
        param_hints.is_empty(),
        "parameterHints=false must suppress all kind-2 hints; got {param_hints:?}"
    );

    Ok(())
}

// ---------------------------------------------------------------------------
// Config: typeHints = false suppresses type-kind hints (kind == 1).
// ---------------------------------------------------------------------------

#[test]
#[serial]
fn inlay_hints_type_hints_disabled_suppresses_type_kind() -> TestResult {
    let mut harness = LspHarness::new();
    harness.initialize(Some(inlay_hint_caps()))?;

    configure_inlay_hints(
        &mut harness,
        json!({ "enabled": true, "parameterHints": true, "typeHints": false }),
    );

    let uri = "file:///hints_no_types.pl";
    // Array literal and numeric literal both produce type hints normally.
    harness.open(uri, r#"my $arr = [1, 2, 3]; my $n = 42; my $s = "hello";"#)?;

    let result = request_hints(&mut harness, uri)?;
    let hints = result.as_array().ok_or("should return an array")?;

    let type_hints: Vec<_> = hints.iter().filter(|h| h["kind"] == 1).collect();
    assert!(
        type_hints.is_empty(),
        "typeHints=false must suppress all kind-1 hints; got {type_hints:?}"
    );

    Ok(())
}

// ---------------------------------------------------------------------------
// Config: maxLength truncates long labels.
// ---------------------------------------------------------------------------

#[test]
#[serial]
fn inlay_hints_max_length_truncates_hint_labels() -> TestResult {
    let mut harness = LspHarness::new();
    harness.initialize(Some(inlay_hint_caps()))?;

    configure_inlay_hints(
        &mut harness,
        json!({ "enabled": true, "parameterHints": true, "typeHints": true, "maxLength": 10 }),
    );

    let uri = "file:///hints_label_capped.pl";
    let text = r#"my $a = substr("hello", 1, 3, "x");"#;
    harness.open(uri, text)?;

    let result = request_hints(&mut harness, uri)?;
    let hints = result.as_array().ok_or("should return an array")?;
    let labels: Vec<&str> = hints.iter().filter_map(|h| h["label"].as_str()).collect();

    assert!(!labels.is_empty(), "fixture should produce hint labels");
    assert!(
        labels.iter().all(|label| label.chars().count() <= 10),
        "maxLength=10 must truncate every label to at most 10 characters; got {labels:?}"
    );
    assert!(
        labels.contains(&"replacemen"),
        "replacement: should be truncated to 10 characters; got {labels:?}"
    );

    Ok(())
}

// ---------------------------------------------------------------------------
// Config: mixed, both categories disabled returns empty.
// ---------------------------------------------------------------------------

#[test]
#[serial]
fn inlay_hints_both_categories_disabled_returns_empty() -> TestResult {
    let mut harness = LspHarness::new();
    harness.initialize(Some(inlay_hint_caps()))?;

    configure_inlay_hints(
        &mut harness,
        json!({ "enabled": true, "parameterHints": false, "typeHints": false }),
    );

    let uri = "file:///hints_both_off.pl";
    harness.open(uri, r#"my $x = substr("hello", 1, 3); my $n = 42; my $a = [1, 2, 3];"#)?;

    let result = request_hints(&mut harness, uri)?;
    let hints = result.as_array().ok_or("should return an array")?;

    assert!(
        hints.is_empty(),
        "with both parameterHints=false and typeHints=false the response must be empty; got {hints:?}"
    );

    Ok(())
}

// ---------------------------------------------------------------------------
// Config: re-enabling after disable restores hints
// ---------------------------------------------------------------------------

#[test]
#[serial]
fn inlay_hints_re_enable_after_disable_restores_hints() -> TestResult {
    let mut harness = LspHarness::new();
    harness.initialize(Some(inlay_hint_caps()))?;

    let uri = "file:///hints_toggle.pl";
    harness.open(uri, r#"my $x = substr("hello", 1, 3);"#)?;

    // Disable
    configure_inlay_hints(&mut harness, json!({ "enabled": false }));
    let disabled_result = request_hints(&mut harness, uri)?;
    let disabled_hints = disabled_result.as_array().ok_or("expected array")?;
    assert!(disabled_hints.is_empty(), "should be empty after disable");

    // Re-enable
    configure_inlay_hints(
        &mut harness,
        json!({ "enabled": true, "parameterHints": true, "typeHints": true }),
    );
    let enabled_result = request_hints(&mut harness, uri)?;
    let enabled_hints = enabled_result.as_array().ok_or("expected array")?;
    assert!(
        !enabled_hints.is_empty(),
        "should return hints after re-enable; got {enabled_hints:?}"
    );

    Ok(())
}
