//! Deterministic human projection of the validated stable train graph.
//!
//! The projection is a pure function of the validated manifest: sorted node
//! and edge order, no timestamps, no environment data, no live state. It is
//! the sole checked human train projection; `train graph --check` fails when
//! the on-disk artifact no longer matches a fresh generation, so the
//! projection can never silently diverge from the manifest.

use std::fmt::Write as _;

use super::model::Manifest;
use super::validate::GraphSummary;

/// Header comment stamped into every generated projection.
pub const PROJECTION_GENERATED_NOTE: &str = "generated by `cargo xtask issue-controllers train \
graph` from `.spec/11764-controller-train-graph/train.manifest.json`; do not edit by hand — \
regenerate after a T02R-classified manifest revision";

/// Render the complete deterministic projection document.
pub fn render_projection(
    manifest: &Manifest,
    semantic_digest: &str,
    summary: &GraphSummary,
) -> String {
    let mut out = String::new();
    let class_line: String = summary
        .class_counts
        .iter()
        .map(|(class, count)| format!("{class} {count}"))
        .collect::<Vec<_>>()
        .join(", ");

    out.push_str("# issue_controller_train.v1 — checked train projection\n");
    out.push('\n');
    out.push_str(PROJECTION_GENERATED_NOTE);
    out.push_str(
        ". This projection records stable contract facts only: no branches, PRs, \
                  checks, SHAs, candidates, agents, implementation status or behavior \
                  verdicts.\n",
    );
    out.push('\n');
    let _ =
        writeln!(out, "- schema: {} (schema_version {})", manifest.schema, manifest.schema_version);
    let _ = writeln!(out, "- semantic digest: {semantic_digest}");
    let _ = writeln!(out, "- nodes: {}", summary.node_count);
    let _ = writeln!(out, "- typed edges: {} ({class_line})", summary.edge_count);
    let _ = writeln!(out, "- checked by: `cargo xtask issue-controllers train check --static`");

    out.push_str("\n## Programme\n");
    let _ = writeln!(out, "- controller: CTRL #{}", manifest.programme.controller_issue);
    let _ = writeln!(out, "- home programme: {}", manifest.programme.home_programme);
    let _ = writeln!(
        out,
        "- durable architecture: S00 #{} (`{}`)",
        manifest.programme.durable_architecture_issue,
        manifest.programme.durable_architecture_bundle
    );
    let _ = writeln!(
        out,
        "- revision governance: {} #{}",
        manifest.revision_governance.owner_node, manifest.revision_governance.owner_issue
    );

    out.push_str("\n## Nodes\n");
    let mut nodes: Vec<&super::model::TrainNode> = manifest.nodes.iter().collect();
    nodes.sort_by(|a, b| a.node_id.cmp(&b.node_id));
    for node in nodes {
        render_node(&mut out, node);
    }

    out.push_str("\n## Typed edges\n");
    let mut edges: Vec<(String, String, String)> = Vec::new();
    for node in &manifest.nodes {
        for dep in &node.dependencies {
            edges.push((node.node_id.clone(), dep.target.clone(), dep.class.clone()));
        }
    }
    edges.sort();
    for (source, target, class) in edges {
        let _ = writeln!(out, "- {source} --{class}--> {target}");
    }

    out.push('\n');
    out
}

fn render_node(out: &mut String, node: &super::model::TrainNode) {
    let _ = writeln!(out, "\n### {} #{} — {}", node.node_id, node.issue, node.title);
    if !node.aliases.is_empty() {
        let mut aliases = node.aliases.clone();
        aliases.sort();
        let _ = writeln!(out, "- aliases: {}", aliases.join(", "));
    }
    let buildable = if node.buildable { "yes" } else { "no" };
    let _ = writeln!(
        out,
        "- train role: {} | lane: {} | buildable: {buildable}",
        node.train_role, node.lane
    );
    let _ = writeln!(out, "- one-PR result: {}", node.one_pr_outcome);
    let _ = writeln!(
        out,
        "- writer: {} (parallel: {}; stack: {})",
        node.writer.conflict_key, node.writer.parallel_group, node.writer.stack_relation
    );
    let _ = writeln!(out, "- claim ceiling: {}", node.claim_ceiling);
    let _ = writeln!(
        out,
        "- spec: {} (owner: {}; stale policy: {})",
        node.spec.disposition, node.spec.owner, node.spec.stale_policy
    );
    let _ = writeln!(out, "- first falsifier: {}", node.first_falsifier);
    let _ = writeln!(out, "- proof: {} (routed: {})", node.proof.focused, node.proof.routed);
    let questions = node.review_forward.questions.join(" / ");
    let lenses = node.review_forward.lenses.join(" / ");
    let _ = writeln!(out, "- review: {questions} (lenses: {lenses})");
    if !node.successors.is_empty() {
        let mut successors = node.successors.clone();
        successors.sort();
        let _ = writeln!(out, "- successors: {}", successors.join(", "));
    }
    let mut hard: Vec<&str> = Vec::new();
    let mut evidence: Vec<&str> = Vec::new();
    let mut optional: Vec<&str> = Vec::new();
    let mut external: Vec<&str> = Vec::new();
    for dep in &node.dependencies {
        match dep.class.as_str() {
            "hard" => hard.push(dep.target.as_str()),
            "evidence" => evidence.push(dep.target.as_str()),
            "optional" => optional.push(dep.target.as_str()),
            "external" => external.push(dep.target.as_str()),
            _ => {}
        }
    }
    for (label, mut group) in
        [("hard", hard), ("evidence", evidence), ("optional", optional), ("external", external)]
    {
        if !group.is_empty() {
            group.sort_unstable();
            let _ = writeln!(out, "- {label} dependencies: {}", group.join(", "));
        }
    }
    let _ = writeln!(
        out,
        "- transfer/supersession exits: old_path={}; supersession={}; transfer={}",
        node.exits.old_path, node.exits.supersession, node.exits.transfer
    );
}

/// Render the deterministic per-node explanation for `train explain-static`.
pub fn render_explanation(manifest: &Manifest, semantic_digest: &str, node_id: &str) -> String {
    let mut nodes: Vec<&super::model::TrainNode> = manifest.nodes.iter().collect();
    nodes.sort_by(|a, b| a.node_id.cmp(&b.node_id));
    let mut out = String::new();
    let _ = writeln!(
        out,
        "issue_controller_train.v1 node {node_id} (semantic_sha256={semantic_digest})"
    );
    let mut found = false;
    for node in nodes {
        if node.node_id != node_id {
            continue;
        }
        render_node(&mut out, node);
        // Immediate reverse edges (who depends on this node), by class.
        let mut dependents: Vec<(String, String)> = manifest
            .nodes
            .iter()
            .flat_map(|other| {
                other
                    .dependencies
                    .iter()
                    .filter(move |dep| dep.target == node.node_id)
                    .map(move |dep| (other.node_id.clone(), dep.class.clone()))
            })
            .collect();
        dependents.sort();
        if !dependents.is_empty() {
            let rendered: Vec<String> = dependents
                .iter()
                .map(|(src, class)| format!("{src} --{class}--> {}", node.node_id))
                .collect();
            let _ = writeln!(out, "- dependents: {}", rendered.join(", "));
        }
        found = true;
    }
    if !found {
        out.clear();
    }
    out
}

/// All valid node ids, sorted — used to fail closed with a helpful list.
pub fn known_node_ids(manifest: &Manifest) -> Vec<String> {
    let mut ids: Vec<String> = manifest.nodes.iter().map(|n| n.node_id.clone()).collect();
    ids.sort();
    ids
}
