//! Deterministic Markdown projection of `release_trust_invariants.v1`.

use std::fs;
use std::path::Path;

use super::error::RegistryError;
use super::model::{STATUS_PATH, TrustInvariantRegistry};

/// Render the committed status markdown from a validated registry.
#[must_use]
pub fn render_status(registry: &TrustInvariantRegistry) -> String {
    let mut markdown = String::from("# Release Trust Invariants\n\n");
    markdown.push_str(
        "> Generated by `cargo xtask release-trust-invariants check` / `write-status`.\n\n",
    );
    markdown.push_str(&format!(
        "Registry issue #{} (parent #{}). This page is a deterministic projection of `{}`.\n\n",
        registry.issue,
        registry.parent_issue,
        super::model::REGISTRY_PATH
    ));
    markdown.push_str(&format!("{}\n\n", registry.claim_boundary));
    markdown.push_str("## Owner authorities\n\n");
    markdown.push_str("| Issue | Status | Successor | Title |\n| --- | --- | --- | --- |\n");
    for owner in &registry.owner_authorities {
        let successor =
            owner.successor.map(|issue| format!("#{issue}")).unwrap_or_else(|| "—".to_string());
        markdown.push_str(&format!(
            "| #{} | `{}` | {successor} | {} |\n",
            owner.issue,
            owner.status.as_str(),
            markdown_table_cell(&owner.title)
        ));
    }

    markdown.push_str("\n## Producer authorities\n\n");
    markdown.push_str(
        "| Producer | Status | Owner | Successor | Command or workflow |\n| --- | --- | --- | --- | --- |\n",
    );
    for producer in &registry.producer_authorities {
        let successor = producer
            .successor
            .map(|kind| format!("`{}`", kind.as_str()))
            .unwrap_or_else(|| "—".to_string());
        markdown.push_str(&format!(
            "| `{}` | `{}` | #{} | {successor} | {} |\n",
            producer.producer_kind.as_str(),
            producer.status.as_str(),
            producer.owner_issue,
            markdown_table_cell(&producer.command_or_workflow)
        ));
    }

    markdown.push_str("\n## Controller requirements\n\n");
    markdown.push_str("| Controller | Mandatory IDs |\n| --- | --- |\n");
    for requirement in &registry.controller_requirements {
        let ids = requirement
            .mandatory_invariant_ids
            .iter()
            .map(|id| format!("`{id}`"))
            .collect::<Vec<_>>()
            .join(", ");
        markdown.push_str(&format!("| #{} | {ids} |\n", requirement.controller_issue));
    }

    markdown.push_str("\n## Invariants\n\n");
    markdown.push_str(
        "| ID | Claim | Owner | Producer | Consumers | Negative controls |\n| --- | --- | --- | --- | --- | --- |\n",
    );
    for row in &registry.invariants {
        let consumers = row
            .release_consumers
            .iter()
            .map(|issue| format!("#{issue}"))
            .collect::<Vec<_>>()
            .join(", ");
        let controls = row
            .negative_control_ids
            .iter()
            .map(|id| format!("`{id}`"))
            .collect::<Vec<_>>()
            .join(", ");
        markdown.push_str(&format!(
            "| `{}` | `{}` | #{} | `{}` | {consumers} | {controls} |\n",
            row.invariant_id,
            row.release_claim.as_str(),
            row.owner_issue,
            row.producer_kind.as_str()
        ));
    }

    markdown.push_str("\n## Claim boundaries\n\n");
    for row in &registry.invariants {
        markdown.push_str(&format!(
            "- `{}`: {}\n",
            row.invariant_id,
            markdown_inline(&row.claim_boundary)
        ));
    }

    markdown.push_str("\n## What this does not establish\n\n");
    markdown.push_str(
        "This projection does not consume live candidate receipts, execute falsifiers, aggregate evidence, or change release controllers.\n",
    );
    markdown
}

/// Flatten newlines and escape `|` so registry text cannot split a table row.
fn markdown_table_cell(text: &str) -> String {
    markdown_inline(text).replace('|', r"\|")
}

/// Keep generated list or paragraph text on one semantic line.
fn markdown_inline(text: &str) -> String {
    text.split(['\r', '\n'])
        .map(str::trim)
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join(" ")
}

/// Byte-compare generated status against the committed file.
pub fn check_status(root: &Path, registry: &TrustInvariantRegistry) -> Result<(), RegistryError> {
    let expected = render_status(registry);
    let path = root.join(STATUS_PATH);
    let existing = fs::read_to_string(&path).map_err(|error| {
        RegistryError::new(format!("{STATUS_PATH}: cannot read generated status: {error}"))
    })?;
    if existing != expected {
        return Err(RegistryError::new(format!(
            "{STATUS_PATH} is out of date; run `cargo xtask release-trust-invariants write-status`"
        )));
    }
    Ok(())
}

/// Write generated status markdown.
pub fn write_status(root: &Path, registry: &TrustInvariantRegistry) -> Result<(), RegistryError> {
    let markdown = render_status(registry);
    let path = root.join(STATUS_PATH);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            RegistryError::new(format!("{}: cannot create parent: {error}", parent.display()))
        })?;
    }
    fs::write(&path, markdown)
        .map_err(|error| RegistryError::new(format!("{STATUS_PATH}: cannot write: {error}")))
}
