//! Generated-artifact policy inspection.
//!
//! The advisory default makes the generated surface visible without silently
//! turning a new heuristic into a merge gate. Blocking modes are explicit.

use clap::ValueEnum;
use color_eyre::eyre::{Context, Result, bail};
use glob::Pattern;
use serde::{Deserialize, Serialize};
use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
};

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum GeneratedPolicyMode {
    Advisory,
    BlockingAllowlist,
    BlockingStrict,
}

impl GeneratedPolicyMode {
    fn as_str(self) -> &'static str {
        match self {
            Self::Advisory => "advisory",
            Self::BlockingAllowlist => "blocking-allowlist",
            Self::BlockingStrict => "blocking-strict",
        }
    }
}

#[derive(Debug, Deserialize)]
struct Policy {
    schema_version: u32,
    policy: String,
    owner: String,
    status: String,
    updated: String,
    #[serde(default)]
    allow: Vec<Entry>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
struct Entry {
    id: String,
    #[serde(default)]
    path: Option<String>,
    #[serde(default)]
    glob: Option<String>,
    kind: String,
    generated_by: String,
    #[serde(default)]
    regenerate: Option<String>,
    owner: String,
    reason: String,
    #[serde(default)]
    covered_by: Vec<String>,
    created: String,
    review_after: String,
    #[serde(default)]
    broad_glob_reason: Option<String>,
}

#[derive(Debug, Serialize)]
struct Report {
    schema_version: u32,
    mode: String,
    tracked_files: usize,
    matched_files: usize,
    generated_markers_without_entry: Vec<String>,
    invalid_entries: Vec<String>,
    errors: Vec<String>,
}

fn load_policy(root: &Path, path: &Path) -> Result<Policy> {
    let text = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let policy: Policy =
        toml::from_str(&text).with_context(|| format!("parsing {}", path.display()))?;
    if policy.schema_version != 1 {
        bail!("unsupported generated policy schema_version {}", policy.schema_version);
    }
    if policy.policy != "generated-allowlist" {
        bail!("expected policy = \"generated-allowlist\", got {:?}", policy.policy);
    }
    if policy.owner.is_empty() || policy.status.is_empty() || policy.updated.is_empty() {
        bail!("generated policy preamble has an empty required field");
    }
    let _ = root;
    Ok(policy)
}

fn tracked_files(root: &Path) -> Result<Vec<String>> {
    let output = Command::new("git")
        .args(["ls-files", "-z"])
        .current_dir(root)
        .output()
        .context("running git ls-files -z")?;
    if !output.status.success() {
        bail!("git ls-files failed: {}", String::from_utf8_lossy(&output.stderr));
    }
    let mut files = output
        .stdout
        .split(|byte| *byte == 0)
        .filter(|path| !path.is_empty())
        .map(|path| String::from_utf8_lossy(path).replace('\\', "/"))
        .collect::<Vec<_>>();
    files.sort();
    Ok(files)
}

fn entry_matches(entry: &Entry, path: &str) -> bool {
    if let Some(exact) = entry.path.as_deref() {
        return exact == path;
    }
    entry
        .glob
        .as_deref()
        .and_then(|pattern| Pattern::new(pattern).ok())
        .is_some_and(|pattern| pattern.matches(path))
}

fn has_generated_marker(path: &Path) -> bool {
    fs::read_to_string(path).is_ok_and(|text| {
        text.lines().any(|line| {
            let trimmed = line.trim_start();
            let body = trimmed
                .strip_prefix("#")
                .or_else(|| trimmed.strip_prefix("//"))
                .or_else(|| trimmed.strip_prefix("*"))
                .or_else(|| trimmed.strip_prefix("<!--"))
                .map(str::trim)
                .unwrap_or("");
            let body = body.trim_end_matches("-->").trim().to_ascii_lowercase();
            body.starts_with("auto-generated")
                || body.starts_with("do not edit")
                || body.starts_with("generated by cargo xtask")
        })
    })
}

fn validate_entries(entries: &[Entry]) -> Vec<String> {
    let mut errors = Vec::new();
    let mut ids = std::collections::BTreeSet::new();
    for entry in entries {
        if !ids.insert(entry.id.as_str()) {
            errors.push(format!("duplicate entry id {}", entry.id));
        }
        if entry.path.is_some() == entry.glob.is_some() {
            errors.push(format!("{} must set exactly one of path or glob", entry.id));
        }
        if let Some(path) = entry.path.as_deref() {
            if path.starts_with('/') {
                errors.push(format!("{} has an absolute path", entry.id));
            }
            if path.contains('\\') {
                errors.push(format!("{} has a backslash path", entry.id));
            }
        }
        if let Some(pattern) = entry.glob.as_deref()
            && Pattern::new(pattern).is_err()
        {
            errors.push(format!("{} has an invalid glob", entry.id));
        }
        for value in [&entry.id, &entry.kind, &entry.generated_by, &entry.owner, &entry.reason] {
            if value.is_empty() {
                errors.push(format!("{} has an empty required field", entry.id));
            }
        }
        if (entry.kind == "lockfile" || entry.kind == "status_page")
            && entry.regenerate.as_deref().is_none_or(str::is_empty)
        {
            errors.push(format!("{} requires regenerate", entry.id));
        }
    }
    errors
}

pub fn run(root: &Path, mode: GeneratedPolicyMode, output: Option<PathBuf>) -> Result<()> {
    let policy_path = root.join("policy/generated-allowlist.toml");
    let policy = load_policy(root, &policy_path)?;
    let files = tracked_files(root)?;
    let invalid_entries = validate_entries(&policy.allow);
    let mut matched_files = 0;
    let mut marker_misses = Vec::new();

    for path in &files {
        let matched = policy.allow.iter().any(|entry| entry_matches(entry, path));
        if matched {
            matched_files += 1;
        } else if has_generated_marker(&root.join(path)) {
            marker_misses.push(path.clone());
        }
    }

    let mut errors = invalid_entries.clone();
    if mode != GeneratedPolicyMode::Advisory {
        errors.extend(
            marker_misses
                .iter()
                .map(|path| format!("generated marker found without allowlist entry: {path}")),
        );
    }
    if mode == GeneratedPolicyMode::BlockingStrict {
        for entry in &policy.allow {
            if entry.glob.as_deref().is_some_and(|pattern| {
                (pattern.contains('*') || pattern.contains('?'))
                    && entry.broad_glob_reason.as_deref().is_none_or(str::is_empty)
            }) {
                errors.push(format!("{} has a broad glob without broad_glob_reason", entry.id));
            }
            if !files.iter().any(|path| entry_matches(entry, path)) {
                errors.push(format!("{} matches no tracked file", entry.id));
            }
            if entry.review_after.as_str() < "2026-08-24" {
                errors.push(format!("{} has a stale review_after", entry.id));
            }
        }
    }

    let report = Report {
        schema_version: 1,
        mode: mode.as_str().to_string(),
        tracked_files: files.len(),
        matched_files,
        generated_markers_without_entry: marker_misses,
        invalid_entries,
        errors: errors.clone(),
    };
    let output = output.unwrap_or_else(|| root.join("target/policy/generated-policy-report.json"));
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&output, serde_json::to_vec_pretty(&report)?)?;
    println!(
        "Generated policy: {} tracked files, {} matched, {} error(s)",
        report.tracked_files,
        report.matched_files,
        report.errors.len()
    );
    if !errors.is_empty() && mode != GeneratedPolicyMode::Advisory {
        bail!("generated policy check failed; see {}", output.display());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn matching_is_exact_or_glob_based() {
        let root = crate::utils::project_root().expect("project root");
        let files = tracked_files(&root).expect("tracked files");
        let policy = load_policy(&root, &root.join("policy/generated-allowlist.toml"))
            .expect("generated allowlist");

        let exact = policy
            .allow
            .iter()
            .find(|entry| entry.id == "generated-cargo-lock")
            .expect("generated-cargo-lock allowlist entry");
        assert_eq!(exact.path.as_deref(), Some("Cargo.lock"));
        assert!(files.iter().any(|path| path == "Cargo.lock"), "Cargo.lock must stay tracked");
        assert!(entry_matches(exact, "Cargo.lock"));
        assert!(!entry_matches(exact, "flake.lock"));

        let status = policy
            .allow
            .iter()
            .find(|entry| entry.id == "generated-status-pages")
            .expect("generated-status-pages allowlist entry");
        let live_glob = status.glob.as_deref().expect("generated-status-pages glob");
        assert_eq!(
            live_glob, "docs/project/status/**/*.md",
            "live status glob must stay the repaired **/*.md form; the prior **.md spelling is invalid for the glob crate and silently matched zero files (#12566)"
        );
        assert!(
            Pattern::new(live_glob).is_ok(),
            "live generated-status-pages glob must be valid for the glob crate"
        );

        const SAMPLE: &str = "docs/project/status/dap.md";
        assert!(
            files.iter().any(|path| path == SAMPLE),
            "status glob sample {SAMPLE} must stay tracked"
        );
        assert!(entry_matches(status, SAMPLE), "live glob must match a tracked status page");
        assert!(!entry_matches(status, "docs/project/ROADMAP.md"));
    }

    #[test]
    fn strict_validation_requires_regeneration_for_generated_kinds() {
        let mut entry = Entry {
            id: "status".into(),
            path: Some("status.md".into()),
            glob: None,
            kind: "status_page".into(),
            generated_by: "xtask".into(),
            regenerate: None,
            owner: "docs".into(),
            reason: "generated".into(),
            covered_by: vec![],
            created: "2026-01-01".into(),
            review_after: "2026-02-01".into(),
            broad_glob_reason: None,
        };
        assert!(
            validate_entries(&[entry.clone()])
                .iter()
                .any(|error| error.contains("requires regenerate"))
        );
        entry.regenerate = Some("cargo xtask update-status".into());
        assert!(validate_entries(&[entry]).is_empty());
    }

    #[test]
    fn marker_detection_is_line_based() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let path = dir.path().join("generated.md");
        fs::write(&path, "# AUTO-GENERATED\\n")?;
        assert!(has_generated_marker(&path));
        Ok(())
    }
}
