//! `cargo xtask public-release-claims-v2` — build, check, list, and explain
//! the deterministic install-claim inventory derivative
//! `public_release_claims.v2` (#11548, shape (a) per the #11549 scoping
//! receipt). Non-authoritative: no route IDs, no projection contexts.

use crate::utils::project_root;
use color_eyre::eyre::{Context, Result, eyre};
use serde_json::Value;
use std::fs;
use xtask::public_release_claims as claims;

#[derive(clap::Subcommand, Debug)]
pub enum PublicReleaseClaimsV2Subcommand {
    /// Generate the canonical catalog; `--write` persists it, without it the
    /// committed artifact is compared against regeneration.
    Build {
        /// Overwrite `distribution/public_release_claims.v2.json` when the
        /// regenerated bytes differ.
        #[arg(long)]
        write: bool,
    },
    /// Validate the committed artifact: byte-identity against the source
    /// inventory + release-asset manifest, canonical form, denominator
    /// completeness, receipt binding, anti-claim set, and closed schema.
    Check,
    /// List stable claim IDs in catalog order.
    List,
    /// Print one claim row as pretty JSON.
    Explain {
        /// Stable claim ID (for example `C207`).
        claim_id: String,
    },
}

pub fn run(command: PublicReleaseClaimsV2Subcommand) -> Result<()> {
    match command {
        PublicReleaseClaimsV2Subcommand::Build { write } => {
            let stats = run_build(write)?;
            println!(
                "public_release_claims.v2 catalog ok: {} surfaces, {} claims, {} findings, {} dimensioned rows, {} anti-claimed rows, {} derived relations",
                stats.surfaces,
                stats.claims,
                stats.findings,
                stats.dimensioned_rows,
                stats.anti_claimed_rows,
                stats.derived_relations
            );
        }
        PublicReleaseClaimsV2Subcommand::Check => {
            let stats = run_check()?;
            println!(
                "public_release_claims.v2 check passed: {} surfaces, {} claims, {} findings, {} dimensioned rows, {} anti-claimed rows, {} derived relations",
                stats.surfaces,
                stats.claims,
                stats.findings,
                stats.dimensioned_rows,
                stats.anti_claimed_rows,
                stats.derived_relations
            );
        }
        PublicReleaseClaimsV2Subcommand::List => {
            let manifest = load_from_repo()?;
            for id in claims::list_claim_ids(&manifest) {
                println!("{id}");
            }
        }
        PublicReleaseClaimsV2Subcommand::Explain { claim_id } => {
            let manifest = load_from_repo()?;
            let explained = claims::explain_claim(&manifest, &claim_id)
                .ok_or_else(|| eyre!("unknown claim id `{claim_id}`"))?;
            println!("{explained}");
        }
    }
    Ok(())
}

fn load_from_repo() -> Result<Value> {
    let root = project_root()?;
    let bytes = fs::read(root.join(claims::ARTIFACT_PATH))
        .wrap_err_with(|| format!("reading {}", claims::ARTIFACT_PATH))?;
    serde_json::from_slice(&bytes).wrap_err("parsing public_release_claims.v2 catalog")
}

/// Run the `build --write` / dry-run flows through one writer path.
pub fn run_build(write: bool) -> Result<claims::CatalogStats> {
    let root = project_root()?;
    let bytes =
        claims::generate_artifact_bytes(&root).wrap_err("generating public_release_claims.v2")?;
    let target = root.join(claims::ARTIFACT_PATH);
    if write {
        if fs::read(&target).ok().as_deref() == Some(bytes.as_slice()) {
            println!("{} already canonical; nothing written", claims::ARTIFACT_PATH);
        } else {
            fs::write(&target, &bytes).with_context(|| format!("writing {}", target.display()))?;
            println!("wrote {}", target.display());
        }
    } else {
        let existing = fs::read(&target).map_err(|_| {
            eyre!(
                "{}: missing; run `cargo xtask public-release-claims-v2 build --write`",
                claims::ARTIFACT_PATH
            )
        })?;
        if existing != bytes {
            color_eyre::eyre::bail!(
                "{} differs from regenerated output; run `cargo xtask public-release-claims-v2 build --write`",
                claims::ARTIFACT_PATH
            );
        }
        println!("{} matches regeneration", claims::ARTIFACT_PATH);
    }
    claims::validate_repository_catalog(&root).wrap_err("validating public_release_claims.v2")
}

/// Validate the committed artifact against live sources without writing.
pub fn run_check() -> Result<claims::CatalogStats> {
    let root = project_root()?;
    claims::validate_repository_catalog(&root).wrap_err("checking public_release_claims.v2")
}
