use color_eyre::eyre::{Result, WrapErr};
use serde::Deserialize;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, Deserialize)]
struct Metadata {
    packages: Vec<Package>,
    workspace_members: Vec<String>,
    workspace_root: String,
}

#[derive(Debug, Deserialize)]
struct Package {
    name: String,
    id: String,
    manifest_path: String,
    dependencies: Vec<Dependency>,
}

#[derive(Debug, Deserialize)]
struct Dependency {
    name: String,
}

#[derive(Debug)]
struct CrateMetrics {
    name: String,
    path: String,
    total_deps: usize,
    internal_deps: usize,
    rust_files: usize,
    loc: usize,
}

pub fn run(output: Option<PathBuf>) -> Result<()> {
    let metadata = cargo_metadata()?;
    let members: std::collections::HashSet<_> = metadata.workspace_members.into_iter().collect();
    let workspace_root = PathBuf::from(&metadata.workspace_root);
    let output = output.unwrap_or_else(|| workspace_root.join("docs/SRP_MICROCRATES.md"));

    let mut metrics = Vec::new();
    for pkg in metadata.packages {
        if !members.contains(&pkg.id) {
            continue;
        }
        let manifest = PathBuf::from(&pkg.manifest_path);
        let Some(crate_dir) = manifest.parent() else {
            continue;
        };

        let relative_crate_dir = match crate_dir.strip_prefix(&workspace_root) {
            Ok(path) => path,
            Err(_) => continue,
        };

        if !relative_crate_dir.starts_with("crates") {
            continue;
        }

        let src_dir = crate_dir.join("src");
        let (rust_files, loc) = count_rust_code(&src_dir)?;
        let total_deps = pkg.dependencies.len();
        let internal_deps = pkg
            .dependencies
            .iter()
            .filter(|dep| dep.name.starts_with("perl-") || dep.name.starts_with("tree-sitter-perl"))
            .count();

        metrics.push(CrateMetrics {
            name: pkg.name,
            path: relative_crate_dir.display().to_string(),
            total_deps,
            internal_deps,
            rust_files,
            loc,
        });
    }

    metrics.sort_by(|a, b| a.name.cmp(&b.name));

    let srp_microcrates: Vec<_> = metrics
        .iter()
        .filter(|m| m.loc > 0 && m.loc <= 700 && m.rust_files <= 3 && m.total_deps <= 8)
        .collect();

    let split_candidates: Vec<_> =
        metrics.iter().filter(|m| m.loc > 2000 || m.total_deps > 20 || m.rust_files > 20).collect();

    let mut families: BTreeMap<&str, usize> = BTreeMap::new();
    for metric in &metrics {
        for family in [
            "perl-module-",
            "perl-lsp-",
            "perl-lsp-feature-",
            "perl-dap-",
            "perl-ts-",
            "perl-workspace-",
        ] {
            if metric.name.starts_with(family) {
                *families.entry(family).or_default() += 1;
            }
        }
    }

    let mut report = String::new();
    report.push_str("# SRP microcrate inventory\n\n");
    report.push_str("Auto-generated by `cargo run -p xtask -- srp-microcrates`.\n\n");
    report.push_str("## Family counts\n\n");
    report.push_str("| Family | Count |\n|---|---:|\n");
    for (family, count) in families {
        report.push_str(&format!("| `{}` | {} |\n", family, count));
    }

    report.push_str("\n## SRP microcrates\n\n");
    report.push_str("Heuristic: <=700 LOC, <=3 Rust source files, <=8 direct deps.\n\n");
    report.push_str(
        "| Crate | LOC | Rust files | Direct deps | Internal deps |\n|---|---:|---:|---:|---:|\n",
    );
    for metric in &srp_microcrates {
        report.push_str(&format!(
            "| `{}` | {} | {} | {} | {} |\n",
            metric.name, metric.loc, metric.rust_files, metric.total_deps, metric.internal_deps
        ));
    }

    report.push_str("\n## Split candidates (separate into additional microcrates)\n\n");
    report.push_str("Heuristic: >2000 LOC, >20 direct deps, or >20 Rust source files.\n\n");
    report.push_str(
        "| Crate | LOC | Rust files | Direct deps | Internal deps | Path |\n|---|---:|---:|---:|---:|---|\n",
    );
    for metric in &split_candidates {
        report.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | `{}` |\n",
            metric.name,
            metric.loc,
            metric.rust_files,
            metric.total_deps,
            metric.internal_deps,
            metric.path,
        ));
    }

    if let Some(parent) = output.parent()
        && !parent.as_os_str().is_empty()
    {
        fs::create_dir_all(parent)
            .wrap_err_with(|| format!("failed to create output directory: {}", parent.display()))?;
    }
    fs::write(&output, report)
        .wrap_err_with(|| format!("failed to write report to {}", output.display()))?;

    println!("Wrote SRP report to {}", output.display());
    Ok(())
}

fn cargo_metadata() -> Result<Metadata> {
    let output = Command::new("cargo")
        .args(["metadata", "--no-deps", "--format-version", "1"])
        .output()
        .wrap_err("failed to execute cargo metadata")?;

    if !output.status.success() {
        return Err(color_eyre::eyre::eyre!(
            "cargo metadata failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }

    serde_json::from_slice(&output.stdout).wrap_err("failed to parse cargo metadata JSON")
}

fn count_rust_code(src_dir: &Path) -> Result<(usize, usize)> {
    if !src_dir.exists() {
        return Ok((0, 0));
    }

    let mut files = 0;
    let mut loc = 0;
    for entry in walkdir::WalkDir::new(src_dir) {
        let entry = entry.wrap_err("failed to walk src dir")?;
        if entry.file_type().is_file() && entry.path().extension().is_some_and(|ext| ext == "rs") {
            files += 1;
            let contents = fs::read_to_string(entry.path()).wrap_err_with(|| {
                format!("failed to read source file {}", entry.path().display())
            })?;
            loc += contents.lines().count();
        }
    }

    Ok((files, loc))
}
