//! Generate and verify the vendored `features_sot.toml` projections (#7029).
//!
//! The workspace root `features.toml` is the single catalog authority
//! (ADR-0040). Crate-local `features_sot.toml` files exist only so
//! standalone/packaged builds can resolve a catalog when the workspace root
//! is unavailable; they are deterministic projections of the authority.
//! `run(false)` regenerates them; `run(true)` fails on byte drift, which the
//! `lsp-318-claim-guard` workflow runs as the enforcement seam.

use color_eyre::eyre::{Result, bail, eyre};
use std::fs;

use crate::utils::project_root;

/// Vendored projections of the authority (#7029).
pub const VENDORED_PROJECTIONS: &[&str] = &[
    "crates/perl-lsp-rs/features_sot.toml",
    "crates/perl-lsp-rs-core/features_sot.toml",
    "crates/perl-parser/features_sot.toml",
    "crates/perl-dap/features_sot.toml",
];

const PROJECTION_HEADER: &str = "\
# @generated by `cargo xtask sync-feature-sot`; DO NOT EDIT.
# Deterministic projection of the workspace catalog authority (features.toml)
# for standalone/vendored builds (#7029). Hand-edits fail the byte drift check
# in .github/workflows/lsp-318-claim-guard.yml.
";

/// Render the projection bytes for a vendored copy from the authority text.
///
/// The projection is the authority body (from `[meta]` onward, so the
/// authority's own header comments are not duplicated) behind a provenance
/// header. Rendering is a pure function of the authority bytes, so running
/// the generator twice produces no diff.
pub fn render_projection(authority_text: &str) -> Result<String> {
    let body_start = authority_text
        .find("[meta]")
        .ok_or_else(|| eyre!("features.toml is missing its [meta] section"))?;
    Ok(format!("{PROJECTION_HEADER}\n{}", &authority_text[body_start..]))
}

/// Whether a projection file no longer matches the rendered authority.
///
/// A missing file (`NotFound`) counts as drift rather than an error: the
/// check mode reports it and the regeneration mode writes it, so deleting a
/// projection or adding a crate cannot wedge the generator.
fn projection_has_drift(current: &std::io::Result<String>, projection: &str) -> Result<bool> {
    match current {
        Ok(content) => Ok(content != projection),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(true),
        Err(e) => Err(eyre!("reading projection: {e}")),
    }
}

/// Regenerate (`check = false`) or verify (`check = true`) all projections.
pub fn run(check: bool) -> Result<()> {
    let root = project_root()?;
    let authority_path = root.join("features.toml");
    let authority = fs::read_to_string(&authority_path)
        .map_err(|e| eyre!("reading {}: {e}", authority_path.display()))?;

    // Parse through the shared catalog so a broken authority fails here
    // instead of landing as an unparseable projection.
    perl_lsp_rs_core::feature_catalog::read_catalog(&authority_path)
        .map_err(|e| eyre!("validating features.toml before projecting: {e}"))?;

    let projection = render_projection(&authority)?;

    let mut drifted: Vec<String> = Vec::new();
    for relative in VENDORED_PROJECTIONS {
        let path = root.join(relative);
        let current = fs::read_to_string(&path);
        if !projection_has_drift(&current, &projection)? {
            continue;
        }
        if check {
            drifted.push(relative.to_string());
        } else {
            fs::write(&path, &projection).map_err(|e| eyre!("writing {}: {e}", path.display()))?;
            println!("synced {relative}");
        }
    }

    if check {
        if drifted.is_empty() {
            println!(
                "feature SOT projections OK: {} file(s) match features.toml (#7029)",
                VENDORED_PROJECTIONS.len()
            );
            return Ok(());
        }
        bail!(
            "vendored feature catalog projection(s) drifted from features.toml (#7029): {}; \
             run `cargo xtask features sync-sot` to regenerate",
            drifted.join(", ")
        );
    }

    println!(
        "feature SOT projections synced: {} file(s) regenerated from features.toml",
        VENDORED_PROJECTIONS.len()
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_projection_places_the_provenance_header_before_meta() -> Result<()> {
        let authority = "# authority header\n\n[meta]\nversion = \"0.17.0\"\n";
        let projection = render_projection(authority)?;
        assert!(projection.starts_with("# @generated by `cargo xtask sync-feature-sot`"));
        assert!(!projection.contains("authority header"));
        assert!(projection.contains("[meta]\nversion = \"0.17.0\""));
        Ok(())
    }

    #[test]
    fn render_projection_is_deterministic() -> Result<()> {
        let authority = "[meta]\nversion = \"0.17.0\"\nlsp_version = \"3.18\"\n";
        assert_eq!(render_projection(authority)?, render_projection(authority)?);
        Ok(())
    }

    #[test]
    fn render_projection_rejects_an_authority_without_meta() {
        assert!(render_projection("# only comments\n").is_err());
    }

    /// #7029 negative control: the check mode must fail when a projection
    /// no longer matches the authority it claims to project.
    /// Review repair: a missing projection file is drift, not an abort, so
    /// regeneration can restore a deleted projection or seed a new crate.
    #[test]
    fn missing_projection_counts_as_drift_not_error() {
        let missing = std::io::Result::<String>::Err(std::io::Error::new(
            std::io::ErrorKind::NotFound,
            "gone",
        ));
        assert!(projection_has_drift(&missing, "anything").unwrap_or(false));
    }

    #[test]
    fn matching_and_drifted_projections_classify_correctly() {
        let ok = std::io::Result::Ok("same".to_string());
        assert!(!projection_has_drift(&ok, "same").unwrap_or(true));
        assert!(projection_has_drift(&ok, "different").unwrap_or(false));
    }

    #[test]
    fn check_mode_fails_on_drifted_projection() -> Result<()> {
        let authority = "[meta]\nversion = \"0.17.0\"\n";
        let expected = render_projection(authority)?;
        let drifted = expected.replace("0.17.0", "9.9.9");
        assert_ne!(expected, drifted, "mutated projection must differ");
        Ok(())
    }

    /// The shipped authority and its four projections must agree byte-for-byte
    /// after running the generator; regeneration twice produces no diff.
    #[test]
    fn shipped_projections_match_the_authority() -> Result<()> {
        let root = project_root()?;
        let authority = fs::read_to_string(root.join("features.toml"))?;
        let projection = render_projection(&authority)?;
        for relative in VENDORED_PROJECTIONS {
            let current = fs::read_to_string(root.join(relative))?;
            assert_eq!(
                current, projection,
                "{relative} drifted from features.toml; run `cargo xtask features sync-sot`"
            );
        }
        Ok(())
    }
}
