//! Source origin and physical source role classifications.
//!
//! These enums describe *where* a source came from and *what role* it plays in
//! the physical filesystem — separate from the stable logical identity.
//!
//! | Type | Question answered |
//! |---|---|
//! | [`SourceOrigin`] | Where did this source come from at the origin level? |
//! | [`PhysicalSourceRole`] | What is the physical/functional role of this file? |
//!
//! Both types use `#[non_exhaustive]` so that future variants can be added
//! without breaking downstream `match` expressions.

use serde::{Deserialize, Serialize};

/// Classification of where a logical source originated.
///
/// `SourceOrigin` answers the question "how did this source enter the
/// workspace?" — it is a property of the logical source, not of any specific
/// content revision or physical location.
///
/// # Unknown origin
///
/// `Unknown` is an explicit variant, not an implicit default. Producers that
/// cannot determine origin must record `Unknown` rather than guessing or using
/// `Workspace` as a fallback.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub enum SourceOrigin {
    /// An ordinary file present in the workspace on disk.
    Workspace,
    /// A virtual source that has no corresponding physical path (e.g. an LSP
    /// in-memory document that has never been saved).
    Virtual,
    /// A file produced by a build step, code generator, or template expansion.
    Generated,
    /// A staged or intermediate artifact not yet part of the committed workspace.
    Staged,
    /// A file pulled from an upstream dependency, vendor tree, or external
    /// source that is not directly owned by this project.
    Upstream,
    /// A source derived at runtime (e.g. `eval`-generated or string-eval
    /// content that the runtime exposes as a synthetic source unit).
    RuntimeDerived,
    /// Origin cannot be determined from the available context.
    Unknown,
}

impl SourceOrigin {
    /// Returns `true` if the origin is `Workspace`.
    #[must_use]
    pub fn is_workspace(&self) -> bool {
        matches!(self, Self::Workspace)
    }

    /// Returns `true` if the origin has a physical counterpart on disk (i.e.
    /// is not purely virtual or runtime-derived).
    #[must_use]
    pub fn has_physical_path(&self) -> bool {
        matches!(self, Self::Workspace | Self::Generated | Self::Staged | Self::Upstream)
    }
}

impl std::fmt::Display for SourceOrigin {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            Self::Workspace => "workspace",
            Self::Virtual => "virtual",
            Self::Generated => "generated",
            Self::Staged => "staged",
            Self::Upstream => "upstream",
            Self::RuntimeDerived => "runtime-derived",
            Self::Unknown => "unknown",
        };
        f.write_str(s)
    }
}

/// The physical/functional role of a source file in the workspace.
///
/// `PhysicalSourceRole` classifies what the file *does* in the workspace
/// structure — whether it is the primary editable source, a generated artifact,
/// a staged copy, an upstream dependency, or whether it is not currently
/// accessible.
///
/// This is distinct from [`SourceOrigin`]: a file that originated as `Upstream`
/// dependency may still have a `Primary` physical role if the developer has
/// vendored and is editing it directly.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub enum PhysicalSourceRole {
    /// The primary, user-edited source file.
    Primary,
    /// A file generated by a build tool, preprocessor, or code generator.
    Generated,
    /// A temporary or staged copy not yet committed.
    Staged,
    /// A file belonging to an upstream dependency or vendor tree.
    Upstream,
    /// A file created or populated at runtime (e.g. string-eval source).
    RuntimeDerived,
    /// The physical file is not available (e.g. it has been deleted, is
    /// inaccessible, or exists only as a logical reference).
    Unavailable,
    /// The role cannot be determined from the available context.
    Unknown,
}

impl PhysicalSourceRole {
    /// Returns `true` if the file is expected to be present on disk and
    /// accessible for reading.
    #[must_use]
    pub fn is_accessible(&self) -> bool {
        matches!(
            self,
            Self::Primary | Self::Generated | Self::Staged | Self::Upstream | Self::RuntimeDerived
        )
    }
}

impl std::fmt::Display for PhysicalSourceRole {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            Self::Primary => "primary",
            Self::Generated => "generated",
            Self::Staged => "staged",
            Self::Upstream => "upstream",
            Self::RuntimeDerived => "runtime-derived",
            Self::Unavailable => "unavailable",
            Self::Unknown => "unknown",
        };
        f.write_str(s)
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    // ── SourceOrigin tests ────────────────────────────────────────────────────

    #[test]
    fn workspace_origin_is_workspace() {
        assert!(SourceOrigin::Workspace.is_workspace());
        assert!(!SourceOrigin::Virtual.is_workspace());
    }

    #[test]
    fn has_physical_path_covers_correct_variants() {
        assert!(SourceOrigin::Workspace.has_physical_path());
        assert!(SourceOrigin::Generated.has_physical_path());
        assert!(SourceOrigin::Staged.has_physical_path());
        assert!(SourceOrigin::Upstream.has_physical_path());
        assert!(!SourceOrigin::Virtual.has_physical_path());
        assert!(!SourceOrigin::RuntimeDerived.has_physical_path());
        assert!(!SourceOrigin::Unknown.has_physical_path());
    }

    #[test]
    fn source_origin_display() {
        assert_eq!(format!("{}", SourceOrigin::Workspace), "workspace");
        assert_eq!(format!("{}", SourceOrigin::Virtual), "virtual");
        assert_eq!(format!("{}", SourceOrigin::Generated), "generated");
        assert_eq!(format!("{}", SourceOrigin::Staged), "staged");
        assert_eq!(format!("{}", SourceOrigin::Upstream), "upstream");
        assert_eq!(format!("{}", SourceOrigin::RuntimeDerived), "runtime-derived");
        assert_eq!(format!("{}", SourceOrigin::Unknown), "unknown");
    }

    // ── PhysicalSourceRole tests ──────────────────────────────────────────────

    #[test]
    fn primary_role_is_accessible() {
        assert!(PhysicalSourceRole::Primary.is_accessible());
    }

    #[test]
    fn unavailable_role_is_not_accessible() {
        assert!(!PhysicalSourceRole::Unavailable.is_accessible());
        assert!(!PhysicalSourceRole::Unknown.is_accessible());
    }

    #[test]
    fn physical_source_role_display() {
        assert_eq!(format!("{}", PhysicalSourceRole::Primary), "primary");
        assert_eq!(format!("{}", PhysicalSourceRole::Generated), "generated");
        assert_eq!(format!("{}", PhysicalSourceRole::Staged), "staged");
        assert_eq!(format!("{}", PhysicalSourceRole::Upstream), "upstream");
        assert_eq!(format!("{}", PhysicalSourceRole::RuntimeDerived), "runtime-derived");
        assert_eq!(format!("{}", PhysicalSourceRole::Unavailable), "unavailable");
        assert_eq!(format!("{}", PhysicalSourceRole::Unknown), "unknown");
    }

    // ── Serde round-trip tests ────────────────────────────────────────────────

    #[test]
    fn source_origin_serde_round_trip() {
        let variants = [
            SourceOrigin::Workspace,
            SourceOrigin::Virtual,
            SourceOrigin::Generated,
            SourceOrigin::Staged,
            SourceOrigin::Upstream,
            SourceOrigin::RuntimeDerived,
            SourceOrigin::Unknown,
        ];
        for v in &variants {
            let json = serde_json::to_string(v).unwrap();
            let back: SourceOrigin = serde_json::from_str(&json).unwrap();
            assert_eq!(*v, back, "round-trip failed for {v}");
        }
    }

    #[test]
    fn physical_source_role_serde_round_trip() {
        let variants = [
            PhysicalSourceRole::Primary,
            PhysicalSourceRole::Generated,
            PhysicalSourceRole::Staged,
            PhysicalSourceRole::Upstream,
            PhysicalSourceRole::RuntimeDerived,
            PhysicalSourceRole::Unavailable,
            PhysicalSourceRole::Unknown,
        ];
        for v in &variants {
            let json = serde_json::to_string(v).unwrap();
            let back: PhysicalSourceRole = serde_json::from_str(&json).unwrap();
            assert_eq!(*v, back, "round-trip failed for {v}");
        }
    }
}
