//! Contract tests for the standalone semantic conformance vectors (#11550):
//! CLI surface behavior plus the structural independence boundary (mutation
//! control 16 — the oracle must never be generated from, or execute,
//! production code).

use anyhow::Result;
use assert_cmd::cargo::cargo_bin_cmd;
use std::fs;
use std::path::PathBuf;

#[test]
fn check_passes_over_the_whole_corpus() -> Result<()> {
    let output = cargo_bin_cmd!("xtask").args(["standalone-vectors", "check"]).output()?;
    assert!(
        output.status.success(),
        "standalone-vectors check must pass:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
    Ok(())
}

#[test]
fn check_is_idempotent_across_second_generation() -> Result<()> {
    for _ in 0..2 {
        let output = cargo_bin_cmd!("xtask").args(["standalone-vectors", "check"]).output()?;
        assert!(output.status.success(), "second generation must produce no diff");
    }
    Ok(())
}

#[test]
fn mutation_check_catches_every_registered_mutation() -> Result<()> {
    let output = cargo_bin_cmd!("xtask").args(["standalone-vectors", "mutation-check"]).output()?;
    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    assert!(
        output.status.success(),
        "mutation-check must pass:\n{stdout}\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(stdout.contains("15 mutations"), "the bank reports its size: {stdout}");
    Ok(())
}

#[test]
fn explain_renders_a_known_vector_and_rejects_unknown_ids() -> Result<()> {
    let output = cargo_bin_cmd!("xtask")
        .args(["standalone-vectors", "explain", "v001-archive-pair-success"])
        .output()?;
    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    assert!(output.status.success(), "explain v001 failed: {stdout}");
    assert!(stdout.contains("installed_transition"), "{stdout}");
    assert!(stdout.contains("all authored expectations match"), "{stdout}");

    let missing = cargo_bin_cmd!("xtask")
        .args(["standalone-vectors", "explain", "does-not-exist"])
        .output()?;
    assert!(!missing.status.success(), "unknown vector ids fail closed");
    Ok(())
}

/// Mutation control 16 (#11550): expected outcomes are never generated by
/// production code. The oracle subtree imports only std/serde/sha2-class
/// proof dependencies and never spawns processes (so it cannot execute the
/// production POSIX/PowerShell adapters either).
#[test]
fn oracle_subtree_has_no_production_imports_or_subprocesses() {
    let module_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/tasks/standalone_vectors");
    let entries = match fs::read_dir(&module_dir) {
        Ok(entries) => entries,
        Err(error) => panic_free(&format!("read_dir failed: {error}")),
    };

    let forbidden: &[&str] = &[
        "use perl_",
        "perl_lsp_rs_core",
        "perl_lsp_r",
        "perl_parser",
        "perl_workspace",
        "perl_dap",
        "perl_corpus",
        "Command::new",
        "std::process::Command",
        "duct::cmd",
        "tokio::process",
    ];

    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("rs") {
            continue;
        }
        let text = match fs::read_to_string(&path) {
            Ok(text) => text,
            Err(error) => panic_free(&format!("read {path:?} failed: {error}")),
        };
        for pattern in forbidden {
            assert!(
                !text.contains(pattern),
                "{path:?} must not reference {pattern:?}: the oracle is independent of \
                 production code and may not execute adapters"
            );
        }
    }
}

/// Panic/unwrap are denied workspace-wide; tests fail through a distinct
/// nonzero exit instead.
fn panic_free(message: &str) -> ! {
    eprintln!("test failure: {message}");
    std::process::exit(101)
}
