//! Parser contracts for source bodies supplied through Perl command-line switches.
//!
//! The parser receives the source body, not shell quoting or the implicit loop
//! generated by `-n`/`-p`. Cases that use `next`, `$_`, or `@F` therefore model
//! the body Perl wraps at runtime rather than a standalone execution context.
//! Autosplit switches such as `-a` and `-F` alter interpreter setup without
//! inserting source text, so `@F` cases test the unchanged command body.

use std::error::Error;

mod cpan_test_helpers;

use cpan_test_helpers::{assert_clean_parse, assert_no_blocking_diagnostics};
use perl_parser_core::hir::{CompilePhase, HirFile, HirKind, lower_ast};
use perl_parser_core::{Node, Parser};

fn collect_ast_shapes(node: &Node, shapes: &mut Vec<(&'static str, usize, usize)>) {
    shapes.push((node.kind.kind_name(), node.location.start, node.location.end));
    for child in node.children() {
        collect_ast_shapes(child, shapes);
    }
}

type TestResult = Result<(), Box<dyn Error>>;

fn parse_clean_with_hir(source: &str) -> Result<(Node, HirFile), Box<dyn Error>> {
    assert_clean_parse(source);
    assert_no_blocking_diagnostics(source);

    let mut parser = Parser::new(source);
    let ast = parser.parse().map_err(|error| format!("clean parse failed: {error:?}"))?;
    let hir = lower_ast(&ast);
    Ok((ast, hir))
}

fn assert_ast_range_contains(source: &str, ast: &Node, kind: &str, fragment: &str) {
    let mut shapes = Vec::new();
    collect_ast_shapes(ast, &mut shapes);
    let found = shapes.iter().any(|(node_kind, start, end)| {
        *node_kind == kind && source.get(*start..*end).is_some_and(|range| range.contains(fragment))
    });
    assert!(
        found,
        "expected AST {kind} range containing {fragment:?} in {source:?}; shapes: {shapes:?}"
    );
}

fn assert_hir_range_contains(source: &str, hir: &HirFile, anchor_kind: &str, fragment: &str) {
    let found = hir.items.iter().any(|item| {
        item.anchor.node_kind == anchor_kind
            && source
                .get(item.range.start..item.range.end)
                .is_some_and(|range| range.contains(fragment))
    });
    assert!(
        found,
        "expected HIR {anchor_kind} range containing {fragment:?} in {source:?}; items: {:?}",
        hir.items.iter().map(|item| (item.anchor.node_kind, item.range)).collect::<Vec<_>>()
    );
}

fn assert_hir_kind(hir: &HirFile, expected: &str, source: &str) {
    let found = hir.items.iter().any(|item| {
        matches!(
            (&item.kind, expected),
            (HirKind::RegexExpr(_), "RegexExpr")
                | (HirKind::MatchExpr(_), "MatchExpr")
                | (HirKind::SubstitutionExpr(_), "SubstitutionExpr")
                | (HirKind::TransliterationExpr(_), "TransliterationExpr")
                | (HirKind::LiteralExpr(_), "LiteralExpr")
                | (HirKind::ReadlineMigrationAdapter(_), "ReadlineMigrationAdapter")
        )
    });
    assert!(found, "expected HIR {expected} for {source:?}");
}

fn assert_single_line_source(source: &str) {
    assert!(
        !source.contains('\n') && !source.contains('\r'),
        "one-liner proof input must not contain a line boundary: {source:?}"
    );
}

fn assert_not_single_line_source(source: &str) {
    assert!(
        source.contains('\n') || source.contains('\r'),
        "negative multiline control must contain a line boundary: {source:?}"
    );
}

// Test-name prefixes encode the represented switch bundle:
// `e` = `-e`, `ne` = `-n -e`, `pe` = `-p -e`, and `lane` = `-l -a -n -e`.
macro_rules! command_line_oneliner {
    ($name:ident, $switches:literal, $source:literal) => {
        #[doc = concat!("Parses the source body used by a `perl ", $switches, " '...'` one-liner.")]
        #[test]
        fn $name() {
            let source = $source;
            assert_clean_parse(source);
            assert_no_blocking_diagnostics(source);
        }
    };
}

command_line_oneliner!(e_print_literal, "-e", r#"print "hello\n";"#);

command_line_oneliner!(ne_implicit_topic_match, "-ne", r#"print if /needle/;"#);

command_line_oneliner!(pe_implicit_topic_substitution, "-pe", r#"s/foo/bar/g;"#);

command_line_oneliner!(pe_implicit_topic_transliteration, "-pe", r#"tr/a-z/A-Z/;"#);

command_line_oneliner!(ne_skip_blank_lines, "-ne", r#"next unless /\S/; print;"#);

command_line_oneliner!(lane_first_autosplit_field, "-lane", r#"print $F[0];"#);

command_line_oneliner!(lane_join_autosplit_fields, "-lane", r#"print join "\t", @F;"#);

command_line_oneliner!(e_grep_diamond_input, "-e", r#"print grep /needle/, <>;"#);

command_line_oneliner!(e_map_diamond_input, "-e", r#"print map { chomp; "$_\n" } <>;"#);

command_line_oneliner!(
    ne_end_phase_counter,
    "-ne",
    r#"$count++ if /needle/; END { print "$count\n"; }"#
);

command_line_oneliner!(ne_argv_and_input_line_number, "-ne", r#"print "$ARGV:$.:$_" if /needle/;"#);

command_line_oneliner!(
    ne_begin_phase_input_record_separator,
    "-ne",
    r#"BEGIN { $/ = undef; } print length;"#
);

command_line_oneliner!(e_explicit_diamond_loop, "-e", r#"while (<>) { print if /needle/; }"#);

command_line_oneliner!(e_sort_diamond_with_for_modifier, "-e", r#"print for sort <>;"#);

command_line_oneliner!(e_parenthesized_split_slice, "-e", r#"print +(split)[0];"#);

command_line_oneliner!(ne_capture_group, "-ne", r#"print "$1\n" if /^(\w+)/;"#);

command_line_oneliner!(pe_trim_whitespace, "-pe", r#"s/^\s+|\s+$//g;"#);

command_line_oneliner!(e_printf_special_variables, "-e", r#"printf "%s:%d\n", $ARGV, $.;"#);

#[test]
fn positive_idioms_have_typed_ast_hir_and_source_range_proof() -> TestResult {
    let cases = [
        (r#"print if /needle/;"#, "Regex", "RegexExpr", "/needle/"),
        (r#"s/foo/bar/g;"#, "Substitution", "SubstitutionExpr", "s/foo/bar/g"),
        (r#"tr/a-z/A-Z/;"#, "Transliteration", "TransliterationExpr", "tr/a-z/A-Z/"),
        (r#"print while <>;"#, "Diamond", "ReadlineMigrationAdapter", "<>"),
        (r#"print "quoted \"value\"";"#, "String", "LiteralExpr", "quoted"),
    ];

    for (source, ast_kind, hir_kind, fragment) in cases {
        assert_single_line_source(source);
        let (ast, hir) = parse_clean_with_hir(source)?;
        assert_ast_range_contains(source, &ast, ast_kind, fragment);
        assert_hir_kind(&hir, hir_kind, source);
        assert_hir_range_contains(source, &hir, ast_kind, fragment);
    }

    let phase_source = r#"BEGIN { $/ = undef; } END { print $.; }"#;
    assert_single_line_source(phase_source);
    let (phase_ast, phase_hir) = parse_clean_with_hir(phase_source)?;
    assert_ast_range_contains(phase_source, &phase_ast, "PhaseBlock", "BEGIN");
    assert_ast_range_contains(phase_source, &phase_ast, "PhaseBlock", "END");
    assert_eq!(phase_hir.compile_environment.phase_blocks.len(), 2);
    for (phase, fragment) in [(CompilePhase::Begin, "BEGIN"), (CompilePhase::End, "END")] {
        let fact = phase_hir
            .compile_environment
            .phase_blocks
            .iter()
            .find(|fact| fact.phase == phase)
            .ok_or_else(|| format!("missing {phase:?} HIR phase block"))?;
        let range = phase_source
            .get(fact.range.start..fact.range.end)
            .ok_or("phase HIR range is not a source boundary")?;
        assert!(range.contains(fragment), "phase range {range:?} must contain {fragment:?}");
    }

    Ok(())
}

#[test]
fn negative_controls_keep_context_errors_and_boundaries_visible() -> TestResult {
    for source in [
        r#"print if /needle;"#,
        r#"s/foo/bar;"#,
        r#"tr/a-z/A-Z;"#,
        r#"BEGIN { print;"#,
        r#"print "unterminated;"#,
    ] {
        cpan_test_helpers::assert_has_error(source, "error");
    }

    // An explicit loop is a wrong-context control for the implicit `-n`/`-p`
    // claim. It must remain visible as a real loop in both layers, rather than
    // being silently treated as a command-line wrapper.
    let explicit_loop = r#"for (<>) { next if /needle/; }"#;
    let (loop_ast, loop_hir) = parse_clean_with_hir(explicit_loop)?;
    assert_ast_range_contains(explicit_loop, &loop_ast, "Foreach", "for");
    assert_ast_range_contains(explicit_loop, &loop_ast, "Diamond", "<>");
    assert_hir_range_contains(explicit_loop, &loop_hir, "Foreach", "for");
    assert!(
        loop_hir.items.iter().any(|item| matches!(item.kind, HirKind::LoopShell(_))),
        "explicit loop must lower to a typed LoopShell"
    );

    // Option-order and shell-quoting are CLI concerns, not parser-body syntax.
    // If either leaks into this target, the AST range makes the contamination
    // explicit instead of allowing it to masquerade as a one-liner idiom.
    let option_contaminated = r#"-ne print;"#;
    let (option_ast, option_hir) = parse_clean_with_hir(option_contaminated)?;
    assert_ast_range_contains(option_contaminated, &option_ast, "Unary", "-ne");
    assert!(!option_hir.items.iter().any(|item| item.anchor.node_kind == "Match"));

    // A multiline source can be a valid Perl program, but it is outside this
    // one-liner fixture contract. Keep its AST/HIR ranges checked while making
    // the excluded boundary explicit.
    let multiline = "print if /needle/;\nprint;";
    assert_not_single_line_source(multiline);
    let (multiline_ast, multiline_hir) = parse_clean_with_hir(multiline)?;
    assert_ast_range_contains(multiline, &multiline_ast, "Program", "\n");
    assert!(multiline_hir.items.iter().all(|item| item.range.end <= multiline.len()));

    Ok(())
}
