//! Parser contracts for source bodies supplied through Perl command-line switches.
//!
//! The parser receives the source body, not shell quoting or the implicit loop
//! generated by `-n`/`-p`. Cases that use `next`, `$_`, or `@F` therefore model
//! the body Perl wraps at runtime rather than a standalone execution context.

mod cpan_test_helpers;

use cpan_test_helpers::{assert_clean_parse, assert_no_blocking_diagnostics};

macro_rules! command_line_oneliner {
    ($name:ident, $switches:literal, $source:literal) => {
        #[doc = concat!("Parses the source body used by a `perl ", $switches, " '...'` one-liner.")]
        #[test]
        fn $name() {
            let source = $source;
            assert_clean_parse(source);
            assert_no_blocking_diagnostics(source);
        }
    };
}

command_line_oneliner!(e_print_literal, "-e", r#"print "hello\n";"#);

command_line_oneliner!(ne_implicit_topic_match, "-ne", r#"print if /needle/;"#);

command_line_oneliner!(pe_implicit_topic_substitution, "-pe", r#"s/foo/bar/g;"#);

command_line_oneliner!(pe_implicit_topic_transliteration, "-pe", r#"tr/a-z/A-Z/;"#);

command_line_oneliner!(ne_skip_blank_lines, "-ne", r#"next unless /\S/; print;"#);

command_line_oneliner!(lane_first_autosplit_field, "-lane", r#"print $F[0];"#);

command_line_oneliner!(lane_join_autosplit_fields, "-lane", r#"print join "\t", @F;"#);

command_line_oneliner!(e_grep_diamond_input, "-e", r#"print grep /needle/, <>;"#);

command_line_oneliner!(e_map_diamond_input, "-e", r#"print map { chomp; "$_\n" } <>;"#);

command_line_oneliner!(
    ne_end_phase_counter,
    "-ne",
    r#"$count++ if /needle/; END { print "$count\n"; }"#
);

command_line_oneliner!(ne_argv_and_input_line_number, "-ne", r#"print "$ARGV:$.:$_" if /needle/;"#);

command_line_oneliner!(
    ne_begin_phase_input_record_separator,
    "-ne",
    r#"BEGIN { $/ = undef; } print length;"#
);

command_line_oneliner!(e_explicit_diamond_loop, "-e", r#"while (<>) { print if /needle/; }"#);

command_line_oneliner!(e_sort_diamond_with_for_modifier, "-e", r#"print for sort <>;"#);

command_line_oneliner!(e_parenthesized_split_slice, "-e", r#"print +(split)[0];"#);

command_line_oneliner!(ne_capture_group, "-ne", r#"print "$1\n" if /^(\w+)/;"#);

command_line_oneliner!(pe_trim_whitespace, "-pe", r#"s/^\s+|\s+$//g;"#);

command_line_oneliner!(e_printf_special_variables, "-e", r#"printf "%s:%d\n", $ARGV, $.;"#);
