use serde::Deserialize;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

const DEFAULT_DAP_FEATURES: &[&str] = &["dap.breakpoints.basic", "dap.core", "dap.inline_values"];

#[derive(Debug, Deserialize)]
struct FeatureCatalog {
    feature: Vec<Feature>,
}

#[derive(Debug, Deserialize)]
struct Feature {
    id: String,
    #[serde(default)]
    area: String,
    #[serde(default)]
    advertised: bool,
}

#[derive(Debug)]
pub struct CatalogSource {
    pub path: PathBuf,
}

pub fn resolve_catalog_source(manifest_dir: &Path) -> Result<CatalogSource, Box<dyn Error>> {
    resolve_catalog_source_with_override(
        manifest_dir,
        std::env::var("FEATURES_TOML_OVERRIDE").ok().map(PathBuf::from),
    )
}

pub fn resolve_catalog_source_with_override(
    manifest_dir: &Path,
    override_path: Option<PathBuf>,
) -> Result<CatalogSource, Box<dyn Error>> {
    if let Some(override_path) = override_path {
        if override_path.exists() {
            return Ok(CatalogSource { path: override_path });
        }
        return Err(format!(
            "FEATURES_TOML_OVERRIDE path does not exist: {}",
            override_path.display()
        )
        .into());
    }

    let local = manifest_dir.join("features.toml");
    if local.exists() {
        return Ok(CatalogSource { path: local });
    }

    let workspace = manifest_dir
        .parent()
        .and_then(Path::parent)
        .map(|parent| parent.join("features.toml"))
        .filter(|path| path.exists());
    if let Some(path) = workspace {
        return Ok(CatalogSource { path });
    }

    let vendored = manifest_dir.join("features_sot.toml");
    if vendored.exists() {
        return Ok(CatalogSource { path: vendored });
    }

    Err(format!("features catalog not found for manifest dir: {}", manifest_dir.display()).into())
}

fn load_catalog_for_build(source: &CatalogSource) -> Result<FeatureCatalog, Box<dyn Error>> {
    let content = fs::read_to_string(&source.path)?;
    Ok(toml::from_str(&content)?)
}

fn render_dap_feature_catalog_module(ids: &[String]) -> String {
    let mut sorted = ids.to_vec();
    sorted.sort_unstable();
    sorted.dedup();

    let mut code = String::from(
        "// @generated by build.rs; DO NOT EDIT.\n\npub const ADVERTISED_DAP_FEATURES: &[&str] = &[\n",
    );
    for id in &sorted {
        code.push_str(&format!("    {:?},\n", id));
    }
    code.push_str(
        "];\n\npub fn advertised_features() -> &'static [&'static str] { ADVERTISED_DAP_FEATURES }\n\npub fn has_feature(id: &str) -> bool { ADVERTISED_DAP_FEATURES.contains(&id) }\n",
    );
    code
}

fn render_dap_fallback_module(default_features: &[&str]) -> String {
    render_dap_feature_catalog_module(
        &default_features.iter().map(|feature| (*feature).to_string()).collect::<Vec<_>>(),
    )
}

pub fn generate_catalog_module_at(
    manifest_dir: &Path,
    out_dir: &Path,
    override_path: Option<PathBuf>,
) -> Result<(), Box<dyn Error>> {
    let source = resolve_catalog_source_with_override(manifest_dir, override_path)?;
    let code = match load_catalog_for_build(&source) {
        Ok(catalog) => {
            let mut source_features = catalog
                .feature
                .iter()
                .filter(|feature| feature.area == "debug" && feature.advertised)
                .map(|feature| feature.id.clone())
                .collect::<Vec<_>>();
            source_features.sort_unstable();
            source_features.dedup();
            render_dap_feature_catalog_module(&source_features)
        }
        Err(error) => {
            eprintln!("Warning: failed to load DAP feature catalog from features.toml: {error}");
            render_dap_fallback_module(DEFAULT_DAP_FEATURES)
        }
    };

    fs::write(out_dir.join("dap_feature_catalog.rs"), code)?;
    Ok(())
}
