use crate::tasks::srp_microcrates::metrics::CrateMetrics;
use std::collections::BTreeMap;

const SRP_LOC_LIMIT: usize = 700;
const SRP_FILE_LIMIT: usize = 3;
const SRP_DEP_LIMIT: usize = 8;
const SPLIT_LOC_LIMIT: usize = 2000;
const SPLIT_FILE_LIMIT: usize = 20;
const SPLIT_DEP_LIMIT: usize = 20;
const FAMILIES: [&str; 6] =
    ["perl-module-", "perl-lsp-", "perl-lsp-feature-", "perl-dap-", "perl-ts-", "perl-workspace-"];

pub(super) fn render(metrics: &[CrateMetrics]) -> String {
    let srp_microcrates: Vec<_> =
        metrics.iter().filter(|metric| is_srp_microcrate(metric)).collect();
    let split_candidates: Vec<_> =
        metrics.iter().filter(|metric| is_split_candidate(metric)).collect();
    let families = count_families(metrics);

    let mut report = String::new();
    report.push_str("# SRP microcrate inventory\n\n");
    report.push_str("Auto-generated by `cargo run -p xtask -- srp-microcrates`.\n\n");
    render_family_counts(&mut report, &families);
    render_srp_microcrates(&mut report, &srp_microcrates);
    render_split_candidates(&mut report, &split_candidates);
    report
}

fn is_srp_microcrate(metric: &CrateMetrics) -> bool {
    metric.loc > 0
        && metric.loc <= SRP_LOC_LIMIT
        && metric.rust_files <= SRP_FILE_LIMIT
        && metric.total_deps <= SRP_DEP_LIMIT
}

fn is_split_candidate(metric: &CrateMetrics) -> bool {
    metric.loc > SPLIT_LOC_LIMIT
        || metric.total_deps > SPLIT_DEP_LIMIT
        || metric.rust_files > SPLIT_FILE_LIMIT
}

fn count_families(metrics: &[CrateMetrics]) -> BTreeMap<&'static str, usize> {
    let mut families = BTreeMap::new();
    for metric in metrics {
        for family in FAMILIES {
            if metric.name.starts_with(family) {
                *families.entry(family).or_default() += 1;
            }
        }
    }
    families
}

fn render_family_counts(report: &mut String, families: &BTreeMap<&str, usize>) {
    report.push_str("## Family counts\n\n");
    report.push_str("| Family | Count |\n|---|---:|\n");
    for (family, count) in families {
        report.push_str(&format!("| `{}` | {} |\n", family, count));
    }
}

fn render_srp_microcrates(report: &mut String, srp_microcrates: &[&CrateMetrics]) {
    report.push_str("\n## SRP microcrates\n\n");
    report.push_str("Heuristic: <=700 LOC, <=3 Rust source files, <=8 direct deps.\n\n");
    report.push_str(
        "| Crate | LOC | Rust files | Direct deps | Internal deps |\n|---|---:|---:|---:|---:|\n",
    );
    for metric in srp_microcrates {
        report.push_str(&format!(
            "| `{}` | {} | {} | {} | {} |\n",
            metric.name, metric.loc, metric.rust_files, metric.total_deps, metric.internal_deps
        ));
    }
}

fn render_split_candidates(report: &mut String, split_candidates: &[&CrateMetrics]) {
    report.push_str("\n## Split candidates (separate into additional microcrates)\n\n");
    report.push_str("Heuristic: >2000 LOC, >20 direct deps, or >20 Rust source files.\n\n");
    report.push_str(
        "| Crate | LOC | Rust files | Direct deps | Internal deps | Path |\n|---|---:|---:|---:|---:|---|\n",
    );
    for metric in split_candidates {
        report.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | `{}` |\n",
            metric.name,
            metric.loc,
            metric.rust_files,
            metric.total_deps,
            metric.internal_deps,
            metric.path,
        ));
    }
}
