//! Closed denominators and load-bearing legal joins for issue #11045.

pub(super) const REQUIRED_AXES: &[&str] = &[
    "application_readiness",
    "cleanup",
    "connection",
    "control",
    "execution",
    "output_delivery",
    "protocol_admission",
    "protocol_lifecycle",
    "publication",
    "task_settlement",
    "terminal",
    "tracking_registration",
];

pub(super) const REQUIRED_IDENTITIES: &[&str] = &[
    "connection_id",
    "currentness_token",
    "deadline_id",
    "failure_id",
    "ingress_sequence",
    "lifecycle_transition_id",
    "message_id",
    "mutation_barrier_id",
    "operation_id",
    "output_id",
    "output_sequence",
    "progress_key",
    "publication_id",
    "request_key",
    "reservation_id",
    "reverse_request_key",
    "route_id",
    "session_id",
    "task_id",
    "work_id",
];

pub(super) const REQUIRED_BOUNDARY_TERMS: &[&str] =
    &["application_completion", "delivery_fate", "terminal_decision", "terminal_signal"];

pub(super) const REQUIRED_STATES: &[&str] = &[
    "application_completed",
    "application_ready",
    "application_unavailable",
    "cancellation_requested",
    "client_consumed",
    "connection_closed",
    "connection_closing",
    "connection_open",
    "deadline_expired",
    "delivery_fate_known",
    "enqueued",
    "execution_admitted",
    "execution_rejected",
    "message_observed",
    "output_admitted",
    "output_failed",
    "output_flush_committed",
    "output_prepared",
    "output_write_committed",
    "owner_cleaned",
    "protocol_exited",
    "protocol_initialized",
    "protocol_shutdown_requested",
    "protocol_uninitialized",
    "protocol_valid",
    "publication_committed",
    "request_registered",
    "request_tracking_reserved",
    "running",
    "stale_publication_rejected",
    "task_group_settled",
    "terminal_selected",
];

pub(super) const REQUIRED_AMBIGUOUS_TERMS: &[&str] = &[
    "accepted",
    "active",
    "admitted",
    "closed",
    "completed",
    "delivered",
    "pending",
    "published",
    "terminal",
];

pub(super) const REQUIRED_JOURNEYS: &[&str] = &[
    "cancellation_during_work",
    "execution_rejection",
    "graceful_shutdown",
    "ordinary_success",
    "request_id_reuse",
    "stale_publication",
    "transport_loss",
    "writer_failure",
];

pub(super) const REQUIRED_RELATION_KEYS: &[&str] = &[
    "session_id|requires|connection_id",
    "request_key|requires|connection_id",
    "request_key|requires|session_id",
    "request_key|independent_of|progress_key",
    "request_key|independent_of|reverse_request_key",
    "reverse_request_key|independent_of|progress_key",
    "application_completion|forbids_inference|terminal_decision",
    "application_completion|forbids_inference|publication_committed",
    "terminal_signal|forbids_inference|terminal_decision",
    "terminal_decision|independent_of|delivery_fate",
    "terminal_decision|forbids_inference|delivery_fate",
    "delivery_fate|forbids_inference|terminal_decision",
    "delivery_fate|forbids_inference|client_consumed",
    "protocol_valid|forbids_inference|request_tracking_reserved",
    "protocol_valid|forbids_inference|request_registered",
    "protocol_valid|forbids_inference|execution_admitted",
    "application_completed|forbids_inference|terminal_selected",
    "application_completed|forbids_inference|publication_committed",
    "terminal_selected|forbids_inference|output_admitted",
    "terminal_selected|forbids_inference|output_write_committed",
    "terminal_selected|forbids_inference|output_flush_committed",
    "publication_committed|forbids_inference|output_admitted",
    "publication_committed|forbids_inference|output_write_committed",
    "publication_committed|forbids_inference|output_flush_committed",
    "publication_committed|forbids_inference|client_consumed",
    "output_admitted|forbids_inference|client_consumed",
    "output_write_committed|forbids_inference|client_consumed",
    "output_flush_committed|forbids_inference|client_consumed",
    "output_failed|independent_of|terminal_selected",
    "owner_cleaned|requires|terminal_selected",
    "owner_cleaned|requires|delivery_fate_known",
    "owner_cleaned|requires|task_group_settled",
    "connection_closed|forbids_inference|protocol_exited",
    "connection_closed|forbids_inference|owner_cleaned",
    "connection_closed|forbids_inference|task_group_settled",
    "connection_closed|forbids_inference|delivery_fate_known",
    "protocol_exited|forbids_inference|connection_closed",
    "protocol_exited|forbids_inference|owner_cleaned",
    "protocol_initialized|independent_of|application_ready",
    "stale_publication_rejected|forbids_inference|publication_committed",
];
