use color_eyre::eyre::{Context, Result};
use serde::Deserialize;
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const INVENTORY_PATH: &str = "policy/provider-fact-reads.toml";

#[derive(Debug, Deserialize)]
struct Inventory {
    owner_issue: u64,
    generated_status: String,
    required_providers: Vec<String>,
    #[serde(rename = "read")]
    reads: Vec<FactRead>,
}

#[derive(Debug, Deserialize)]
struct FactRead {
    id: String,
    provider: String,
    request_class: String,
    query: String,
    producer: String,
    proof_class: String,
    readiness_input: String,
    fallback: String,
    duplicate_interpretation: String,
    migration_disposition: String,
    replacement_owner: String,
    source: Vec<FactSource>,
}

#[derive(Debug, Deserialize)]
struct FactSource {
    path: String,
    anchor: Vec<SourceAnchor>,
}

#[derive(Debug, Deserialize)]
struct SourceAnchor {
    kind: String,
    value: String,
    count: usize,
}

pub(super) fn generate(root: &Path) -> Result<(PathBuf, String)> {
    let inventory_path = root.join(INVENTORY_PATH);
    let text = fs::read_to_string(&inventory_path)
        .with_context(|| format!("failed to read {}", inventory_path.display()))?;
    let inventory: Inventory = toml::from_str(&text)
        .with_context(|| format!("failed to parse {}", inventory_path.display()))?;
    let output_path = root.join(&inventory.generated_status);
    let rendered = render(&inventory)?;
    Ok((output_path, rendered))
}

fn render(inventory: &Inventory) -> Result<String> {
    let mut output = String::new();
    writeln!(output, "# Provider Fact Read Inventory")?;
    writeln!(output)?;
    writeln!(
        output,
        "> Generated by `cargo xtask update-status --write --only provider-facts` from"
    )?;
    writeln!(
        output,
        "> `{INVENTORY_PATH}`. This inventory records current provider fact reads,"
    )?;
    writeln!(
        output,
        "> ownership assumptions, and duplicate interpretation seams. It does not"
    )?;
    writeln!(
        output,
        "> change provider behavior, promote a producer, or authorize edits."
    )?;
    writeln!(output)?;
    writeln!(
        output,
        "Owner: [#{}](https://github.com/EffortlessMetrics/perl-lsp-swarm/issues/{})",
        inventory.owner_issue, inventory.owner_issue
    )?;
    writeln!(output)?;
    writeln!(output, "## Coverage")?;
    writeln!(output)?;
    writeln!(output, "| Provider | Inventoried reads |")?;
    writeln!(output, "| --- | ---: |")?;

    let mut counts = BTreeMap::<&str, usize>::new();
    for read in &inventory.reads {
        *counts.entry(read.provider.as_str()).or_default() += 1;
    }
    for provider in &inventory.required_providers {
        writeln!(
            output,
            "| `{}` | {} |",
            escape_cell(provider),
            counts
                .get(provider.as_str())
                .copied()
                .unwrap_or_default()
        )?;
    }

    writeln!(output)?;
    writeln!(output, "## Reads")?;
    writeln!(output)?;
    writeln!(
        output,
        "| ID | Provider | Request | Query / fact need | Current producer | Proof assumption | Readiness / freshness | Fallback / refusal | Executable seams | Duplicate interpretation seam | Migration |"
    )?;
    writeln!(
        output,
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"
    )?;
    for read in &inventory.reads {
        writeln!(
            output,
            "| `{}` | `{}` | `{}` | {} | `{}` | `{}` | {} | {} | {} | {} | `{}` → {} |",
            escape_cell(&read.id),
            escape_cell(&read.provider),
            escape_cell(&read.request_class),
            escape_cell(&read.query),
            escape_cell(&read.producer),
            escape_cell(&read.proof_class),
            escape_cell(&read.readiness_input),
            escape_cell(&read.fallback),
            render_sources(&read.source),
            escape_cell(&read.duplicate_interpretation),
            escape_cell(&read.migration_disposition),
            escape_cell(&read.replacement_owner),
        )?;
    }

    writeln!(output)?;
    writeln!(output, "## Claim boundary")?;
    writeln!(output)?;
    writeln!(output, "- A producer name is not a proof or safety class.")?;
    writeln!(output, "- An inventory row is not a cutover decision.")?;
    writeln!(
        output,
        "- Every row is anchored to executable Rust structure; comments and string literals do not satisfy the inventory."
    )?;
    writeln!(
        output,
        "- `port_candidate` means the read should move behind the canonical provider port."
    )?;
    writeln!(
        output,
        "- `intentional_provider_policy` means domain policy may remain provider-owned after shared facts arrive."
    )?;
    writeln!(
        output,
        "- `retire_after_parity` requires request-bound comparison evidence before removal."
    )?;
    writeln!(
        output,
        "- Generated, dynamic, stale, partial, ambiguous, or low-confidence facts do not gain edit authority from this inventory."
    )?;

    Ok(output)
}

fn render_sources(sources: &[FactSource]) -> String {
    sources
        .iter()
        .map(|source| {
            let anchors = source
                .anchor
                .iter()
                .map(|anchor| format!("{}:{}×{}", anchor.kind, anchor.value, anchor.count))
                .collect::<Vec<_>>()
                .join(", ");
            format!("`{}`<br>{}", escape_cell(&source.path), escape_cell(&anchors))
        })
        .collect::<Vec<_>>()
        .join("<br>")
}

fn escape_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', "<br>")
}
