pub(crate) mod badges;
pub(crate) mod doc_drift;
pub(crate) mod doc_links;
pub(crate) mod doc_paths;
pub(crate) mod fatal_constructs;
pub(crate) mod panic_test;
pub(crate) mod print_in_lib;
pub(crate) mod regex_static;
pub(crate) mod todos;
