//! Built-in completion name catalog.

/// Returns all built-in names surfaced by completion.
pub fn all_names() -> impl Iterator<Item = &'static str> {
    [
        // I/O
        "print",
        "printf",
        "say",
        "sprintf",
        "open",
        "close",
        "read",
        "write",
        "seek",
        "tell",
        "binmode",
        "eof",
        "fileno",
        "flock",
        "getc",
        "readline",
        "sysread",
        "syswrite",
        "sysseek",
        "pipe",
        // String
        "chomp",
        "chop",
        "chr",
        "ord",
        "lc",
        "uc",
        "lcfirst",
        "ucfirst",
        "length",
        "substr",
        "index",
        "rindex",
        "split",
        "join",
        "reverse",
        "quotemeta",
        // Array
        "push",
        "pop",
        "shift",
        "unshift",
        "splice",
        "grep",
        "map",
        "sort",
        "wantarray",
        "scalar",
        // Hash
        "keys",
        "values",
        "each",
        "exists",
        "delete",
        // Math / numeric
        "abs",
        "atan2",
        "cos",
        "sin",
        "exp",
        "log",
        "sqrt",
        "int",
        "rand",
        "srand",
        "hex",
        "oct",
        // File tests (operators, not functions, but surfaced as completions)
        "-r",
        "-w",
        "-x",
        "-o",
        "-R",
        "-W",
        "-X",
        "-O",
        "-e",
        "-z",
        "-s",
        "-f",
        "-d",
        "-l",
        "-p",
        "-S",
        "-b",
        "-c",
        "-t",
        "-u",
        "-g",
        "-k",
        "-T",
        "-B",
        "-M",
        "-A",
        "-C",
        // File system
        "stat",
        "lstat",
        "rename",
        "unlink",
        "mkdir",
        "rmdir",
        "chdir",
        "chmod",
        "chown",
        "link",
        "symlink",
        "readlink",
        "glob",
        "opendir",
        "readdir",
        "closedir",
        "rewinddir",
        "telldir",
        "seekdir",
        "truncate",
        // System / process
        "system",
        "exec",
        "fork",
        "wait",
        "waitpid",
        "kill",
        "sleep",
        "alarm",
        "getpid",
        "getppid",
        "times",
        // Time
        "time",
        "localtime",
        "gmtime",
        // Misc / context
        "caller",
        "die",
        "warn",
        "eval",
        "exit",
        "require",
        "use",
        "no",
        "import",
        "unimport",
        "bless",
        "ref",
        "tied",
        "untie",
        "pack",
        "unpack",
        "vec",
        "study",
        "pos",
        "qr",
        "defined",
        "undef",
        "prototype",
        "reset",
        "dump",
        "dbmopen",
        "dbmclose",
        // Network / socket
        "socket",
        "socketpair",
        "listen",
        "accept",
        "connect",
        "bind",
        "recv",
        "send",
        "shutdown",
        "getpeername",
        "getsockname",
        "getsockopt",
        "setsockopt",
        // IPC
        "msgctl",
        "msgget",
        "msgrcv",
        "msgsnd",
        "semctl",
        "semget",
        "semop",
        "shmctl",
        "shmget",
        "shmread",
        "shmwrite",
        // User / group
        "getlogin",
        "getpwnam",
        "getpwuid",
        "getpwent",
        "setpwent",
        "endpwent",
        "getgrnam",
        "getgrgid",
        "getgrent",
        "setgrent",
        "endgrent",
        // Network lookup
        "gethostbyname",
        "gethostbyaddr",
        "gethostent",
        "sethostent",
        "endhostent",
        "getnetbyname",
        "getnetbyaddr",
        "getnetent",
        "setnetent",
        "endnetent",
        "getprotobyname",
        "getprotobynumber",
        "getprotoent",
        "setprotoent",
        "endprotoent",
        "getservbyname",
        "getservbyport",
        "getservent",
        "setservent",
        "endservent",
        // UTF-8 encoding (perldoc utf8)
        "utf8::encode",
        "utf8::decode",
        "utf8::is_utf8",
        "utf8::valid",
        "utf8::upgrade",
        "utf8::downgrade",
        "utf8::native_to_unicode",
        "utf8::unicode_to_native",
        // Perl 5.36+ `use builtin` functions
        // These are available via: use builtin 'funcname'; or as builtin::funcname()
        // Perl 5.36: boolean + reference utilities
        "true",
        "false",
        "is_bool",
        "weaken",
        "unweaken",
        "is_weak",
        "refaddr",
        "reftype",
        "blessed",
        // Perl 5.38: math + string utilities
        "ceil",
        "floor",
        "inf",
        "nan",
        "trim",
        "indexed",
        "is_tainted",
        // Perl 5.40: module loading + lexical export
        "load_module",
        "export_lexically",
    ]
    .into_iter()
}

/// Returns the names of `use builtin` functions that require an explicit
/// `use builtin 'name'` (or `use builtin qw(...)`) import to be in scope.
///
/// These names overlap with `all_names()` and are also gated behind
/// `has_builtin_import`. `all_names()` is kept unfiltered so the
/// `could_be_function` probe remains accurate.
pub fn builtin_import_names() -> &'static [&'static str] {
    &[
        "true",
        "false",
        "is_bool",
        "weaken",
        "unweaken",
        "is_weak",
        "refaddr",
        "reftype",
        "blessed",
        "ceil",
        "floor",
        "inf",
        "nan",
        "trim",
        "indexed",
        "is_tainted",
        "load_module",
        "export_lexically",
    ]
}
