-- Deterministic fixture tests for the #11170 deterministic composition
-- materializer.
--
-- Run:
--   lua clients/lite-xl/tests/compose_materializer_test.lua [path-to-compose]
-- Default module path is ../compose.lua relative to this file.
--
-- Seam owned: the MATERIALIZER LAWS over a hermetic fake source adapter -
-- no real git, no real staged tree, fully controlled snapshots. Each issue
-- scenario is one fixture:
--
--   F1  two non-overlapping patches compose;
--   F2  ordered dependent overlapping patches compose (declared edge,
--       later declared winner owns the path);
--   F3  an UNDECLARED overlap stops with typed undeclared_overlap naming
--       both components and the shared path (combined-tree interaction);
--   F4  a wrong base digest stops with typed base_digest_mismatch;
--   F5  snapshot bytes drifting from the recorded reviewed digest stop
--       with typed digest_mismatch (the no-fuzz/skipped-hunk analog:
--       whole-file snapshots cannot fuzz, so any divergence from the
--       reviewed bytes is fatal);
--   F6  a member whose hard prerequisite is absent from the profile stops
--       with typed missing_prerequisite;
--   F7  a stale internal candidate SHA stops with typed stale_candidate_sha;
--   F8  an extra hand-edited file in the generated tree fails verify with
--       typed unowned_diff;
--   F9  the same members declared in a different listed order produce a
--       byte-identical tree digest and receipt (order derives only from
--       dependencies);
--   F10 regeneration is byte-identical and second-run clean;
--   F11 a quality-class component inserted into a core-class-only profile
--       stops with typed class_violation;
--   F12 NEGATIVE CONTROL: flipping one generated byte after composition
--       changes the tree digest and fails verification;
--   F13 a dependency cycle stops with typed dependency_cycle;
--   F14 a component introducing a NEW file (not in the base) materializes
--       additively;
--   F15 an empty profile materializes the pristine base tree exactly.
--
-- Receipts carry no wall-clock input anywhere ("timestamp"/"built_at"
-- never appear); determinism comes from inputs alone.
--
-- Red-first baseline: run against CURRENT MAIN before this patch - there
-- is no compose.lua yet, so loading this suite fails (nonzero exit).
--
-- Mutation falsifiers of the PATCHED module (each mechanically verified
-- against a mutated copy; 11-mutant battery all red):
--   1. skip the prereq-closure membership check -> F6 observes silent
--     materialization instead of missing_prerequisite;
--   2. let the last writer win without checking declared dependencies ->
--     F3 observes silent path stealing instead of undeclared_overlap;
--   3. digest laws are enforced at TWO layers (snapshot verification AND
--     write-back inventory comparison); removing either single layer keeps
--     F5 red via the survivor - only removing BOTH lets drifted bytes
--     compose green (verified);
--   4. verify_tree has two unowned-diff branches (extra file, mutated
--     bytes); disabling one still catches F8/F12 via the other; disabling
--     verification entirely is caught (verified);
--   5. take application order from listed order instead of deriving it
--     from dependencies -> F9 observes order-dependent output and F2
--     observes wrong chain winners (verified);
--   6. stamp os.time into the receipt -> F10 observes nondeterministic
--     receipts (verified).

local compose_path = arg and arg[1] or nil
if not compose_path then
  local info = debug.getinfo(1, "S").source:sub(2)
  local dir = info:match("^(.*)[/\\]") or "."
  compose_path = dir .. "/../compose.lua"
end

local passed, failed = 0, 0
local function ok(condition, message)
  if condition then
    passed = passed + 1
  else
    failed = failed + 1
    print("FAIL: " .. message)
  end
end

local function expect_error(code, fn, label)
  local ran, err = pcall(fn)
  if ran then
    ok(false, label .. ": expected typed error " .. code .. ", none raised")
    return nil
  end
  if type(err) ~= "table" or err.compose_error ~= true then
    ok(false, label .. ": raised non-typed error: " .. tostring(err))
    return nil
  end
  ok(err.code == code,
    label .. ": typed " .. code .. " (got " .. tostring(err.code) .. ")")
  return err
end

-- ---------------------------------------------------------------------------
-- Deterministic content hashing for the hermetic sandbox (FNV-1a 32-bit).
-- ---------------------------------------------------------------------------

local function fnv_hex(bytes)
  local h = 2166136261
  local b = { string.byte(bytes, 1, #bytes) }
  for i = 1, #b do
    h = h ~ b[i]
    h = (h * 16777619) & 0xFFFFFFFF
  end
  return string.format("%08x", h)
end

-- ---------------------------------------------------------------------------
-- Hermetic fake adapter
-- ---------------------------------------------------------------------------

local function fake_adapter(spec)
  local commits = spec.commits or {}
  local ancestors = spec.ancestors or {}
  return {
    component_exists = function(sha)
      return commits[sha] ~= nil and commits[sha].exists ~= false
    end,
    touched_upstream_paths = function(sha)
      local c = commits[sha]
      local out = {}
      if c and c.paths then
        for p in pairs(c.paths) do out[#out + 1] = p end
      end
      table.sort(out)
      return out
    end,
    snapshot = function(sha, path, dest)
      local c = commits[sha]
      local bytes = c and c.paths and c.paths[path] or nil
      if not bytes then
        error("fixture has no snapshot " .. sha .. ":" .. path)
      end
      local f = io.open(dest, "wb")
      f:write(bytes)
      f:close()
      return true
    end,
    is_ancestor = function(a, b)
      return ancestors[a .. ">" .. b] == true
    end,
    hash_file = function(path)
      local f = io.open(path, "rb")
      if not f then error("no file " .. path) end
      local bytes = f:read("*a")
      f:close()
      return fnv_hex(bytes)
    end,
    digest_text = function(text)
      return fnv_hex(text)
    end,
  }
end

-- ---------------------------------------------------------------------------
-- Sandbox + synthetic manifest builders
-- ---------------------------------------------------------------------------

local scratch_root = (os.getenv("TEMP") or ".") .. "/compose_materializer_scratch"
os.execute('mkdir "' .. scratch_root .. '" 2>nul')

-- Directory creation is deferred and flushed as ONE chained command:
-- process spawns dominate runtime on this host.
local CREATED = { [scratch_root] = true }
local PENDING = {}

local function sandbox(name)
  local dir = scratch_root .. "/" .. name
  if not CREATED[dir] then
    CREATED[dir] = true
    PENDING[#PENDING + 1] = dir
  end
  return dir
end

local function flush_dirs()
  if #PENDING == 0 then return end
  local parts = {}
  for _, d in ipairs(PENDING) do
    parts[#parts + 1] = 'mkdir "' .. d .. '" 2>nul'
  end
  PENDING = {}
  os.execute(table.concat(parts, " & "))
end

local function write_file(path, bytes)
  local dir = path:match("^(.*)[/\\]")
  if dir and not CREATED[dir] then
    sandbox(dir:sub(#scratch_root + 2))
  end
  flush_dirs()
  local f = io.open(path, "wb")
  f:write(bytes)
  f:close()
end

local BASE_BYTES = {
  ["json.lua"] = "return { name = 'pristine-json' }\n",
  ["util.lua"] = "return { name = 'pristine-util' }\n",
}

-- Build a sandbox with pristine base modules; returns base_dir and the
-- matching base digest map.
local function make_base(name)
  local base_dir = sandbox(name)
  local digests = {}
  for p, bytes in pairs(BASE_BYTES) do
    write_file(base_dir .. "/" .. p, bytes)
    digests[p] = fnv_hex(bytes)
  end
  return base_dir, digests
end

local function comp(id, sha, paths, snap_bytes, prereqs, class)
  local content = {}
  for _, p in ipairs(paths) do
    content[p] = fnv_hex(snap_bytes[p])
  end
  local conflict_keys = {}
  for _, p in ipairs(paths) do
    conflict_keys[#conflict_keys + 1] = "lite-xl.upstream." .. p
  end
  return {
    id = id,
    issue = 1,
    candidate_sha = sha,
    changed_paths = paths,
    hard_prerequisites = prereqs or {},
    class = class or "protocol",
    upstream_state = "internal",
    owner_issue = 1,
    conflict_keys = conflict_keys,
    invalidation_inputs = { "candidate_sha", "upstream_base_ref" },
    content = content,
  }
end

local function prof(id, members, admitted)
  return {
    id = id,
    claim = "fixture envelope",
    admitted_classes = admitted or { protocol = true },
    members = members,
  }
end

local function manifest(components, profiles, base_files)
  return {
    schema = "candidate-manifest.v1",
    upstream_base = { repository = "fixture/x", ref = "fix000", files = base_files },
    components = components,
    profiles = profiles,
  }
end

local function load_compose()
  local okk, mod = pcall(dofile, compose_path)
  ok(okk, "compose module loads (" .. tostring(mod) .. ")")
  return okk and mod or nil
end

local compose = load_compose()
if not compose then
  print(string.format("compose_materializer_test: %d passed, %d failed", passed, failed))
  os.exit(1)
end

-- Explicit-call variant keeping base_dir under test control.
local function run(m, adapter, profile_id, tag, base_dir)
  local tree_dir = sandbox(tag .. "_tree")
  local receipt_path = sandbox(tag .. "_rcpt") .. "/receipt.json"
  local res = compose.materialize({
    manifest = m,
    adapter = adapter,
    profile = profile_id,
    base_dir = base_dir,
    out_dir = tree_dir,
    receipt_path = receipt_path,
  })
  return res, tree_dir, receipt_path
end

local function read_file(path)
  local f = io.open(path, "rb")
  if not f then return nil end
  local b = f:read("*a")
  f:close()
  return b
end

-- ---------------------------------------------------------------------------
-- Shared two-component worlds
-- ---------------------------------------------------------------------------

-- World A: leaf_one patches json.lua; leaf_two patches util.lua (disjoint).
local function disjoint_world()
  local base_dir, base_dig = make_base("f1")
  local s1 = "return { name = 'json-after-one' }\n"
  local s2 = "return { name = 'util-after-two' }\n"
  local c1 = comp("leaf_one", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    { "json.lua" }, { ["json.lua"] = s1 }, {})
  local c2 = comp("leaf_two", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    { "util.lua" }, { ["util.lua"] = s2 }, {})
  local m = manifest({ c1, c2 },
    { prof("p", { "leaf_one", "leaf_two" }) }, base_dig)
  local ad = fake_adapter({ commits = {
    [c1.candidate_sha] = { paths = { ["json.lua"] = s1 } },
    [c2.candidate_sha] = { paths = { ["util.lua"] = s2 } },
  } })
  return base_dir, m, ad, c1, c2, s1, s2
end

-- F1: non-overlapping patches compose.
do
  local base_dir, m, ad, c1, c2, s1, s2 = disjoint_world()
  local res, tree_dir = run(m, ad, "p", "f1", base_dir)
  ok(type(res) == "table" and res.tree_digest ~= nil, "F1 composes with a tree digest")
  ok(read_file(tree_dir .. "/json.lua") == s1, "F1 json.lua carries leaf_one bytes")
  ok(read_file(tree_dir .. "/util.lua") == s2, "F1 util.lua carries leaf_two bytes")
  ok(res.inventory["json.lua"] == fnv_hex(s1), "F1 inventory records json blob")
  ok(res.receipt_json:find('"leaf_one"', 1, true) ~= nil,
    "F1 receipt lists leaf_one")
  ok(res.receipt_json:find('"leaf_two"', 1, true) ~= nil,
    "F1 receipt lists leaf_two")
  ok(res.receipt_json:find("timestamp", 1, true) == nil
    and res.receipt_json:find("built_at", 1, true) == nil,
    "F1 receipt excludes wall-clock inputs")
end

-- F2: ordered dependent overlapping patches compose; later winner owns.
do
  local base_dir = make_base("f2")
  local s1 = "return { v = 1 }\n"
  local s2 = "return { v = 1, extra = true }\n"
  local c1 = comp("dep_first", "1111111111111111111111111111111111111111",
    { "json.lua" }, { ["json.lua"] = s1 }, {})
  local c2 = comp("dep_second", "2222222222222222222222222222222222222222",
    { "json.lua" }, { ["json.lua"] = s2 }, { "dep_first" })
  local m = manifest({ c2, c1 },
    { prof("p", { "dep_second", "dep_first" }) },
    { ["json.lua"] = fnv_hex(BASE_BYTES["json.lua"]) })
  local ad = fake_adapter({ commits = {
    [c1.candidate_sha] = { paths = { ["json.lua"] = s1 } },
    [c2.candidate_sha] = { paths = { ["json.lua"] = s2 } },
  }, ancestors = { [c1.candidate_sha .. ">" .. c2.candidate_sha] = true } })
  local res, tree_dir = run(m, ad, "p", "f2", base_dir)
  ok(res.tree["json.lua"] == fnv_hex(s2),
    "F2 later dependent leaf owns the overlapping path")
  ok(read_file(tree_dir .. "/json.lua") == s2, "F2 written bytes are the winner's")
end

-- F3: undeclared overlap stops typed.
do
  local base_dir = make_base("f3")
  local s1 = "return { who = 'one' }\n"
  local s2 = "return { who = 'two' }\n"
  local c1 = comp("ovr_one", "3333333333333333333333333333333333333333",
    { "json.lua" }, { ["json.lua"] = s1 }, {})
  local c2 = comp("ovr_two", "4444444444444444444444444444444444444444",
    { "json.lua" }, { ["json.lua"] = s2 }, {})
  local m = manifest({ c1, c2 }, { prof("p", { "ovr_one", "ovr_two" }) },
    { ["json.lua"] = fnv_hex(BASE_BYTES["json.lua"]) })
  local ad = fake_adapter({ commits = {
    [c1.candidate_sha] = { paths = { ["json.lua"] = s1 } },
    [c2.candidate_sha] = { paths = { ["json.lua"] = s2 } },
  } })
  local err = expect_error("undeclared_overlap", function()
    run(m, ad, "p", "f3", base_dir)
  end, "F3")
  ok((err.component == "ovr_one" and err.other_component == "ovr_two")
    or (err.component == "ovr_two" and err.other_component == "ovr_one"),
    "F3 names both conflicting components")
  ok(err.path == "json.lua", "F3 names the shared path")
end

-- F4: wrong base digest stops typed.
do
  local base_dir, digests = make_base("f4")
  digests["json.lua"] = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
  local c1 = comp("solo", "5555555555555555555555555555555555555555",
    { "util.lua" },
    { ["util.lua"] = "return { patched = true }\n" }, {})
  local m = manifest({ c1 }, { prof("p", { "solo" }) }, digests)
  local ad = fake_adapter({ commits = {
    [c1.candidate_sha] = { paths = { ["util.lua"] = "return { patched = true }\n" } },
  } })
  expect_error("base_digest_mismatch", function()
    run(m, ad, "p", "f4", base_dir)
  end, "F4")
end

-- F5: snapshot drifting from the recorded reviewed digest stops typed.
do
  local base_dir, digests = make_base("f5")
  local reviewed = "return { reviewed = true }\n"
  local drifted = "return { reviewed = true, sneaky = 1 }\n"
  local c1 = comp("drifty", "6666666666666666666666666666666666666666",
    { "json.lua" }, { ["json.lua"] = reviewed }, {})
  -- Adapter serves DRIFTED bytes; manifest still records the REVIEWED digest.
  local m = manifest({ c1 }, { prof("p", { "drifty" }) }, digests)
  local ad = fake_adapter({ commits = {
    [c1.candidate_sha] = { paths = { ["json.lua"] = drifted } },
  } })
  local err = expect_error("digest_mismatch", function()
    run(m, ad, "p", "f5", base_dir)
  end, "F5")
  ok(err.path == "json.lua", "F5 names the drifting path")
end

-- F6: missing prerequisite in profile membership stops typed.
do
  local base_dir = make_base("f6")
  local s1 = "return { step = 1 }\n"
  local s2 = "return { step = 2 }\n"
  local c1 = comp("pre_req", "7777777777777777777777777777777777777777",
    { "json.lua" }, { ["json.lua"] = s1 }, {})
  local c2 = comp("needs_it", "8888888888888888888888888888888888888888",
    { "json.lua" }, { ["json.lua"] = s2 }, { "pre_req" })
  local m = manifest({ c1, c2 },
    { prof("p", { "needs_it" }) },   -- pre_req NOT a member
    { ["json.lua"] = fnv_hex(BASE_BYTES["json.lua"]) })
  local ad = fake_adapter({ commits = {
    [c1.candidate_sha] = { paths = { ["json.lua"] = s1 } },
    [c2.candidate_sha] = { paths = { ["json.lua"] = s2 } },
  } })
  local err = expect_error("missing_prerequisite", function()
    run(m, ad, "p", "f6", base_dir)
  end, "F6")
  ok(err.component == "needs_it" and err.prerequisite == "pre_req",
    "F6 names the member and its absent prerequisite")
end

-- F7: stale internal candidate SHA stops typed.
do
  local base_dir, digests = make_base("f7")
  local gone = comp("vanished", "9999999999999999999999999999999999999999",
    { "json.lua" }, { ["json.lua"] = "return {}\n" }, {})
  local m = manifest({ gone }, { prof("p", { "vanished" }) }, digests)
  local ad = fake_adapter({ commits = {
    -- commit absent entirely: resolver cannot resolve it
  } })
  local err = expect_error("stale_candidate_sha", function()
    run(m, ad, "p", "f7", base_dir)
  end, "F7")
  ok(err.component == "vanished", "F7 names the stale component")
end

-- F8/F12: verification catches extra files and flipped bytes.
do
  local base_dir, m, ad, c1, c2, s1, s2 = disjoint_world()
  local res, tree_dir, receipt_path = run(m, ad, "p", "f8", base_dir)

  -- untouched tree verifies clean
  local okv = pcall(compose.verify_tree, {
    tree_dir = tree_dir, inventory = res.inventory, adapter = ad,
  })
  ok(okv, "F8 freshly composed tree verifies clean")

  -- extra hand-edited file appears
  write_file(tree_dir .. "/hand_edit.lua", "return 'sneaky'\n")
  local err = expect_error("unowned_diff", function()
    compose.verify_tree({ tree_dir = tree_dir, inventory = res.inventory, adapter = ad })
  end, "F8")
  ok(err.path == "hand_edit.lua", "F8 names the unowned file")

  -- negative control: flip one generated byte after composition
  os.remove(tree_dir .. "/hand_edit.lua")
  write_file(tree_dir .. "/json.lua", (s1:gsub("one", "ONE")))
  local err2 = expect_error("unowned_diff", function()
    compose.verify_tree({ tree_dir = tree_dir, inventory = res.inventory, adapter = ad })
  end, "F12")
  ok(err2.path ~= nil, "F12 attributes the mutated file")
end

-- F9: listed-order permutation produces identical output.
do
  local base_dir, digests = make_base("f9")
  local sa = "return { chain = 'a' }\n"
  local sb = "return { chain = 'a', then_b = true }\n"
  local ca = comp("ord_a", "aaaa0000aaaa0000aaaa0000aaaa0000aaaa0000",
    { "json.lua" }, { ["json.lua"] = sa }, {})
  local cb = comp("ord_b", "bbbb0000bbbb0000bbbb0000bbbb0000bbbb0000",
    { "json.lua" }, { ["json.lua"] = sb }, { "ord_a" })
  local cu = comp("ord_u", "cccc0000cccc0000cccc0000cccc0000cccc0000",
    { "util.lua" }, { ["util.lua"] = "return { u = 1 }\n" }, {})
  local ad_spec = { commits = {
    [ca.candidate_sha] = { paths = { ["json.lua"] = sa } },
    [cb.candidate_sha] = { paths = { ["json.lua"] = sb } },
    [cu.candidate_sha] = { paths = { ["util.lua"] = "return { u = 1 }\n" } },
  }, ancestors = { [ca.candidate_sha .. ">" .. cb.candidate_sha] = true } }
  local m1 = manifest({ ca, cb, cu }, { prof("p", { "ord_a", "ord_b", "ord_u" }) }, digests)
  local m2 = manifest({ cu, cb, ca }, { prof("p", { "ord_u", "ord_b", "ord_a" }) }, digests)
  local r1 = run(m1, fake_adapter(ad_spec), "p", "f9a", base_dir)
  local r2 = run(m2, fake_adapter(ad_spec), "p", "f9b", base_dir)
  ok(r1.tree_digest == r2.tree_digest,
    "F9 permuted listed order yields identical tree digest")
  ok(r1.receipt_json == r2.receipt_json,
    "F9 permuted listed order yields byte-identical receipt")
end

-- F10: regeneration is byte-identical and second-run clean.
do
  local base_dir, m, ad = disjoint_world()
  local r1, t1, rp1 = run(m, ad, "p", "f10a", base_dir)
  local r2, t2, rp2 = run(m, ad, "p", "f10b", base_dir)
  ok(r1.tree_digest == r2.tree_digest, "F10 tree digest stable across runs")
  ok(r1.receipt_json == r2.receipt_json, "F10 receipt byte-identical across runs")
  ok(read_file(t1 .. "/util.lua") == read_file(t2 .. "/util.lua"),
    "F10 regenerated trees byte-identical")
end

-- F11: quality class rejected by core-only envelope.
do
  local base_dir, digests = make_base("f11")
  local cq = comp("quality_thing", "dddd1111dddd1111dddd1111dddd1111dddd1111",
    { "json.lua" }, { ["json.lua"] = "return { q = 1 }\n" }, {}, "quality")
  local m = manifest({ cq },
    { prof("core_like", { "quality_thing" }, { protocol = true }) }, digests)
  local ad = fake_adapter({ commits = {
    [cq.candidate_sha] = { paths = { ["json.lua"] = "return { q = 1 }\n" } },
  } })
  local err = expect_error("class_violation", function()
    run(m, ad, "core_like", "f11", base_dir)
  end, "F11")
  ok(err.component == "quality_thing", "F11 names the violating component")
  ok(err.profile == "core_like", "F11 names the rejecting profile")
end

-- F13: dependency cycle stops typed.
do
  local base_dir = make_base("f13")
  local s1 = "return { cyc = 1 }\n"
  local c1 = comp("cyc_a", "eeee1111eeee1111eeee1111eeee1111eeee1111",
    { "json.lua" }, { ["json.lua"] = s1 }, { "cyc_b" })
  local c2 = comp("cyc_b", "eeee2222eeee2222eeee2222eeee2222eeee2222",
    { "json.lua" }, { ["json.lua"] = s1 }, { "cyc_a" })
  local m = manifest({ c1, c2 }, { prof("p", { "cyc_a", "cyc_b" }) },
    { ["json.lua"] = fnv_hex(BASE_BYTES["json.lua"]) })
  local ad = fake_adapter({ commits = {
    [c1.candidate_sha] = { paths = { ["json.lua"] = s1 } },
    [c2.candidate_sha] = { paths = { ["json.lua"] = s1 } },
  } })
  expect_error("dependency_cycle", function()
    run(m, ad, "p", "f13", base_dir)
  end, "F13")
end

-- F14: new-file component materializes additively.
do
  local base_dir, digests = make_base("f14")
  local snew = "-- capability projection\nreturn {}\n"
  local cn = comp("new_filer", "ffff1111ffff1111ffff1111ffff1111ffff1111",
    { "capability_manifest.lua" },
    { ["capability_manifest.lua"] = snew }, {})
  local m = manifest({ cn }, { prof("p", { "new_filer" }) }, digests)
  local ad = fake_adapter({ commits = {
    [cn.candidate_sha] = { paths = { ["capability_manifest.lua"] = snew } },
  } })
  local res, tree_dir = run(m, ad, "p", "f14", base_dir)
  ok(res.tree["capability_manifest.lua"] == fnv_hex(snew),
    "F14 new file present in inventory")
  ok(read_file(tree_dir .. "/capability_manifest.lua") == snew,
    "F14 new file written with component bytes")
  ok(read_file(tree_dir .. "/json.lua") == BASE_BYTES["json.lua"],
    "F14 untouched base module stays pristine")
end

-- F15: empty profile materializes the pristine base exactly.
do
  local base_dir, digests = make_base("f15")
  local m = manifest({}, { prof("empty_p", {}) }, digests)
  local ad = fake_adapter({})
  local res, tree_dir = run(m, ad, "empty_p", "f15", base_dir)
  ok(read_file(tree_dir .. "/json.lua") == BASE_BYTES["json.lua"],
    "F15 json.lua is pristine")
  ok(read_file(tree_dir .. "/util.lua") == BASE_BYTES["util.lua"],
    "F15 util.lua is pristine")
  ok(res.inventory["json.lua"] == digests["json.lua"],
    "F15 inventory equals the pinned base digests")

  -- F16: a NESTED stale file from an earlier run must be cleared by the
  -- composer-owned cleanup, not silently kept beside the fresh tree.
  os.execute('mkdir "' .. tree_dir .. '/subdir" 2>nul')
  write_file(tree_dir .. "/subdir/stale.lua", "return 'stale'\n")
  local res2, tree_dir2 = run(m, ad, "empty_p", "f16", base_dir)
  ok(res2.tree_digest == res.tree_digest,
    "F16 recomposition digest unaffected by stale input")
  ok(read_file(tree_dir2 .. "/subdir/stale.lua") == nil,
    "F16 nested stale file removed by composition")
  local okv = pcall(compose.verify_tree, {
    tree_dir = tree_dir2, inventory = res2.inventory, adapter = ad,
  })
  ok(okv, "F16 regenerated tree verifies clean")
end

print(string.format("compose_materializer_test: %d passed, %d failed", passed, failed))
os.exit(failed == 0 and 0 or 1)
