-- Deterministic fixture tests for the #11170 deterministic composition
-- materializer.
--
-- Run:
--   lua clients/lite-xl/tests/compose_materializer_test.lua [path-to-compose]
-- Default module path is ../compose.lua relative to this file.
--
-- Seam owned: the MATERIALIZER LAWS over a hermetic fake source adapter -
-- no real git, no real staged tree, fully controlled snapshots. Each issue
-- scenario is one fixture:
--
--   F1  two non-overlapping patches compose;
--   F2  ordered dependent overlapping patches compose (declared edge,
--       later declared winner owns the path);
--   F3  an UNDECLARED overlap stops with typed undeclared_overlap naming
--       both components and the shared path (combined-tree interaction);
--   F4  a wrong base digest stops with typed base_digest_mismatch;
--   F5  snapshot bytes drifting from the recorded reviewed digest stop
--       with typed digest_mismatch (the no-fuzz/skipped-hunk analog:
--       whole-file snapshots cannot fuzz, so any divergence from the
--       reviewed bytes is fatal);
--   F6  a member whose hard prerequisite is absent from the profile stops
--       with typed missing_prerequisite;
--   F7  a stale internal candidate SHA stops with typed stale_candidate_sha;
--   F8  an extra hand-edited file in the generated tree fails verify with
--       typed unowned_diff;
--   F9  the same members declared in a different listed order produce a
--       byte-identical tree digest and receipt (order derives only from
--       dependencies);
--   F10 regeneration is byte-identical and second-run clean;
--   F11 a quality-class component inserted into a core-class-only profile
--       stops with typed class_violation;
--   F12 NEGATIVE CONTROL: flipping one generated byte after composition
--       changes the tree digest and fails verification;
--   F13 a dependency cycle stops with typed dependency_cycle;
--   F14 a component introducing a NEW file (not in the base) materializes
--       additively;
--   F15 an empty profile materializes the pristine base tree exactly.
--
-- Receipts carry no wall-clock input anywhere ("timestamp"/"built_at"
-- never appear); determinism comes from inputs alone.
--
-- Red-first baseline: run against CURRENT MAIN before this patch - there
-- is no compose.lua yet, so loading this suite fails (nonzero exit).
--
-- Mutation falsifiers of the PATCHED module (each mechanically verified
-- against a mutated copy; 11-mutant battery all red):
--   1. skip the prereq-closure membership check -> F6 observes silent
--     materialization instead of missing_prerequisite;
--   2. let the last writer win without checking declared dependencies ->
--     F3 observes silent path stealing instead of undeclared_overlap;
--   3. digest laws are enforced at TWO layers (snapshot verification AND
--     write-back inventory comparison); removing either single layer keeps
--     F5 red via the survivor - only removing BOTH lets drifted bytes
--     compose green (verified);
--   4. verify_tree has two unowned-diff branches (extra file, mutated
--     bytes); disabling one still catches F8/F12 via the other; disabling
--     verification entirely is caught (verified);
--   5. take application order from listed order instead of deriving it
--     from dependencies -> F9 observes order-dependent output and F2
--     observes wrong chain winners (verified);
--   6. stamp os.time into the receipt -> F10 observes nondeterministic
--     receipts (verified).

local compose_path = arg and arg[1] or nil
if not compose_path then
  local info = debug.getinfo(1, "S").source:sub(2)
  local dir = info:match("^(.*)[/\\]") or "."
  compose_path = dir .. "/../compose.lua"
end

local passed, failed = 0, 0
local function ok(condition, message)
  if condition then
    passed = passed + 1
  else
    failed = failed + 1
    print("FAIL: " .. message)
  end
end

local function expect_error(code, fn, label)
  local ran, err = pcall(fn)
  if ran then
    ok(false, label .. ": expected typed error " .. code .. ", none raised")
    return nil
  end
  if type(err) ~= "table" or err.compose_error ~= true then
    ok(false, label .. ": raised non-typed error: " .. tostring(err))
    return nil
  end
  ok(err.code == code,
    label .. ": typed " .. code .. " (got " .. tostring(err.code) .. ")")
  return err
end

-- ---------------------------------------------------------------------------
-- Deterministic content hashing for the hermetic sandbox (FNV-1a 32-bit).
-- ---------------------------------------------------------------------------

local function fnv_hex(bytes)
  local h = 2166136261
  local b = { string.byte(bytes, 1, #bytes) }
  for i = 1, #b do
    h = h ~ b[i]
    h = (h * 16777619) & 0xFFFFFFFF
  end
  return string.format("%08x", h)
end

-- ---------------------------------------------------------------------------
-- Hermetic fake adapter
-- ---------------------------------------------------------------------------

local function fake_adapter(spec)
  local commits = spec.commits or {}
  local ancestors = spec.ancestors or {}
  return {
    component_exists = function(sha)
      return commits[sha] ~= nil and commits[sha].exists ~= false
    end,
    touched_upstream_paths = function(sha)
      local c = commits[sha]
      local out = {}
      if c and c.paths then
        for p in pairs(c.paths) do out[#out + 1] = p end
      end
      table.sort(out)
      return out
    end,
    snapshot = function(sha, path, dest)
      local c = commits[sha]
      local bytes = c and c.paths and c.paths[path] or nil
      if not bytes then
        error("fixture has no snapshot " .. sha .. ":" .. path)
      end
      local f = io.open(dest, "wb")
      f:write(bytes)
      f:close()
      return true
    end,
    is_ancestor = function(a, b)
      return ancestors[a .. ">" .. b] == true
    end,
    hash_file = function(path)
      local f = io.open(path, "rb")
      if not f then error("no file " .. path) end
      local bytes = f:read("*a")
      f:close()
      return fnv_hex(bytes)
    end,
    digest_text = function(text)
      return fnv_hex(text)
    end,
  }
end

-- ---------------------------------------------------------------------------
-- Sandbox + synthetic manifest builders
-- ---------------------------------------------------------------------------

local scratch_root = (os.getenv("TEMP") or ".") .. "/compose_materializer_scratch"
local IS_WINDOWS = package.config:sub(1, 1) == "\\"
os.execute(IS_WINDOWS
  and ('mkdir "' .. scratch_root .. '" 2>nul')
  or ('mkdir -p "' .. scratch_root .. '" 2>/dev/null'))

-- Directory creation is deferred and flushed as ONE chained command:
-- process spawns dominate runtime on this host.
local CREATED = { [scratch_root] = true }
local PENDING = {}

local function sandbox(name)
  local dir = scratch_root .. "/" .. name
  if not CREATED[dir] then
    CREATED[dir] = true
    PENDING[#PENDING + 1] = dir
  end
  return dir
end

local function flush_dirs()
  if #PENDING == 0 then return end
  local parts = {}
  for _, d in ipairs(PENDING) do
    parts[#parts + 1] = IS_WINDOWS
      and ('mkdir "' .. d .. '" 2>nul')
      or ('mkdir -p "' .. d .. '" 2>/dev/null')
  end
  PENDING = {}
  os.execute(table.concat(parts, IS_WINDOWS and " & " or " && "))
end

local function write_file(path, bytes)
  local dir = path:match("^(.*)[/\\]")
  if dir and not CREATED[dir] then
    sandbox(dir:sub(#scratch_root + 2))
  end
  flush_dirs()
  local f = io.open(path, "wb")
  f:write(bytes)
  f:close()
end

local BASE_BYTES = {
  ["json.lua"] = "return { name = 'pristine-json' }\n",
  ["util.lua"] = "return { name = 'pristine-util' }\n",
}

-- Build a sandbox with pristine base modules; returns base_dir and the
-- matching base digest map.
local function make_base(name)
  local base_dir = sandbox(name)
  local digests = {}
  for p, bytes in pairs(BASE_BYTES) do
    write_file(base_dir .. "/" .. p, bytes)
    digests[p] = fnv_hex(bytes)
  end
  return base_dir, digests
end

local function comp(id, sha, paths, snap_bytes, prereqs, class)
  local content = {}
  for _, p in ipairs(paths) do
    content[p] = fnv_hex(snap_bytes[p])
  end
  local conflict_keys = {}
  for _, p in ipairs(paths) do
    conflict_keys[#conflict_keys + 1] = "lite-xl.upstream." .. p
  end
  return {
    id = id,
    issue = 1,
    candidate_sha = sha,
    changed_paths = paths,
    hard_prerequisites = prereqs or {},
    class = class or "protocol",
    upstream_state = "internal",
    owner_issue = 1,
    conflict_keys = conflict_keys,
    invalidation_inputs = { "candidate_sha", "upstream_base_ref" },
    content = content,
  }
end

local function prof(id, members, admitted)
  return {
    id = id,
    claim = "fixture envelope",
    admitted_classes = admitted or { protocol = true },
    members = members,
  }
end

local function manifest(components, profiles, base_files)
  return {
    schema = "candidate-manifest.v1",
    upstream_base = { repository = "fixture/x", ref = "fix000", files = base_files },
    components = components,
    profiles = profiles,
  }
end

local function load_compose()
  local okk, mod = pcall(dofile, compose_path)
  ok(okk, "compose module loads (" .. tostring(mod) .. ")")
  return okk and mod or nil
end

local compose = load_compose()
if not compose then
  print(string.format("compose_materializer_test: %d passed, %d failed", passed, failed))
  os.exit(1)
end

-- Explicit-call variant keeping base_dir under test control.
local function run(m, adapter, profile_id, tag, base_dir)
  local tree_dir = sandbox(tag .. "_tree")
  local receipt_path = sandbox(tag .. "_rcpt") .. "/receipt.json"
  local res = compose.materialize({
    manifest = m,
    adapter = adapter,
    profile = profile_id,
    base_dir = base_dir,
    out_dir = tree_dir,
    receipt_path = receipt_path,
  })
  return res, tree_dir, receipt_path
end

local function read_file(path)
  local f = io.open(path, "rb")
  if not f then return nil end
  local b = f:read("*a")
  f:close()
  return b
end

-- ---------------------------------------------------------------------------
-- Shared two-component worlds
-- ---------------------------------------------------------------------------

-- World A: leaf_one patches json.lua; leaf_two patches util.lua (disjoint).
local function disjoint_world()
  local base_dir, base_dig = make_base("f1")
  local s1 = "return { name = 'json-after-one' }\n"
  local s2 = "return { name = 'util-after-two' }\n"
  local c1 = comp("leaf_one", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    { "json.lua" }, { ["json.lua"] = s1 }, {})
  local c2 = comp("leaf_two", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    { "util.lua" }, { ["util.lua"] = s2 }, {})
  local m = manifest({ c1, c2 },
    { prof("p", { "leaf_one", "leaf_two" }) }, base_dig)
  local ad = fake_adapter({ commits = {
    [c1.candidate_sha] = { paths = { ["json.lua"] = s1 } },
    [c2.candidate_sha] = { paths = { ["util.lua"] = s2 } },
  } })
  return base_dir, m, ad, c1, c2, s1, s2
end

-- F1: non-overlapping patches compose.
do
  local base_dir, m, ad, c1, c2, s1, s2 = disjoint_world()
  local res, tree_dir = run(m, ad, "p", "f1", base_dir)
  ok(type(res) == "table" and res.tree_digest ~= nil, "F1 composes with a tree digest")
  ok(read_file(tree_dir .. "/json.lua") == s1, "F1 json.lua carries leaf_one bytes")
  ok(read_file(tree_dir .. "/util.lua") == s2, "F1 util.lua carries leaf_two bytes")
  ok(res.inventory["json.lua"] == fnv_hex(s1), "F1 inventory records json blob")
  ok(res.receipt_json:find('"leaf_one"', 1, true) ~= nil,
    "F1 receipt lists leaf_one")
  ok(res.receipt_json:find('"leaf_two"', 1, true) ~= nil,
    "F1 receipt lists leaf_two")
  ok(res.receipt_json:find("timestamp", 1, true) == nil
    and res.receipt_json:find("built_at", 1, true) == nil,
    "F1 receipt excludes wall-clock inputs")
end

-- F2: ordered dependent overlapping patches compose; later winner owns.
do
  local base_dir = make_base("f2")
  local s1 = "return { v = 1 }\n"
  local s2 = "return { v = 1, extra = true }\n"
  local c1 = comp("dep_first", "1111111111111111111111111111111111111111",
    { "json.lua" }, { ["json.lua"] = s1 }, {})
  local c2 = comp("dep_second", "2222222222222222222222222222222222222222",
    { "json.lua" }, { ["json.lua"] = s2 }, { "dep_first" })
  local m = manifest({ c2, c1 },
    { prof("p", { "dep_second", "dep_first" }) },
    { ["json.lua"] = fnv_hex(BASE_BYTES["json.lua"]) })
  local ad = fake_adapter({ commits = {
    [c1.candidate_sha] = { paths = { ["json.lua"] = s1 } },
    [c2.candidate_sha] = { paths = { ["json.lua"] = s2 } },
  }, ancestors = { [c1.candidate_sha .. ">" .. c2.candidate_sha] = true } })
  local res, tree_dir = run(m, ad, "p", "f2", base_dir)
  ok(res.tree["json.lua"] == fnv_hex(s2),
    "F2 later dependent leaf owns the overlapping path")
  ok(read_file(tree_dir .. "/json.lua") == s2, "F2 written bytes are the winner's")
end

-- F3: undeclared overlap stops typed.
do
  local base_dir = make_base("f3")
  local s1 = "return { who = 'one' }\n"
  local s2 = "return { who = 'two' }\n"
  local c1 = comp("ovr_one", "3333333333333333333333333333333333333333",
    { "json.lua" }, { ["json.lua"] = s1 }, {})
  local c2 = comp("ovr_two", "4444444444444444444444444444444444444444",
    { "json.lua" }, { ["json.lua"] = s2 }, {})
  local m = manifest({ c1, c2 }, { prof("p", { "ovr_one", "ovr_two" }) },
    { ["json.lua"] = fnv_hex(BASE_BYTES["json.lua"]) })
  local ad = fake_adapter({ commits = {
    [c1.candidate_sha] = { paths = { ["json.lua"] = s1 } },
    [c2.candidate_sha] = { paths = { ["json.lua"] = s2 } },
  } })
  local err = expect_error("undeclared_overlap", function()
    run(m, ad, "p", "f3", base_dir)
  end, "F3")
  ok((err.component == "ovr_one" and err.other_component == "ovr_two")
    or (err.component == "ovr_two" and err.other_component == "ovr_one"),
    "F3 names both conflicting components")
  ok(err.path == "json.lua", "F3 names the shared path")
end

-- F4: wrong base digest stops typed.
do
  local base_dir, digests = make_base("f4")
  digests["json.lua"] = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
  local c1 = comp("solo", "5555555555555555555555555555555555555555",
    { "util.lua" },
    { ["util.lua"] = "return { patched = true }\n" }, {})
  local m = manifest({ c1 }, { prof("p", { "solo" }) }, digests)
  local ad = fake_adapter({ commits = {
    [c1.candidate_sha] = { paths = { ["util.lua"] = "return { patched = true }\n" } },
  } })
  expect_error("base_digest_mismatch", function()
    run(m, ad, "p", "f4", base_dir)
  end, "F4")
end

-- F5: snapshot drifting from the recorded reviewed digest stops typed.
do
  local base_dir, digests = make_base("f5")
  local reviewed = "return { reviewed = true }\n"
  local drifted = "return { reviewed = true, sneaky = 1 }\n"
  local c1 = comp("drifty", "6666666666666666666666666666666666666666",
    { "json.lua" }, { ["json.lua"] = reviewed }, {})
  -- Adapter serves DRIFTED bytes; manifest still records the REVIEWED digest.
  local m = manifest({ c1 }, { prof("p", { "drifty" }) }, digests)
  local ad = fake_adapter({ commits = {
    [c1.candidate_sha] = { paths = { ["json.lua"] = drifted } },
  } })
  local err = expect_error("digest_mismatch", function()
    run(m, ad, "p", "f5", base_dir)
  end, "F5")
  ok(err.path == "json.lua", "F5 names the drifting path")
end

-- F6: missing prerequisite in profile membership stops typed.
do
  local base_dir = make_base("f6")
  local s1 = "return { step = 1 }\n"
  local s2 = "return { step = 2 }\n"
  local c1 = comp("pre_req", "7777777777777777777777777777777777777777",
    { "json.lua" }, { ["json.lua"] = s1 }, {})
  local c2 = comp("needs_it", "8888888888888888888888888888888888888888",
    { "json.lua" }, { ["json.lua"] = s2 }, { "pre_req" })
  local m = manifest({ c1, c2 },
    { prof("p", { "needs_it" }) },   -- pre_req NOT a member
    { ["json.lua"] = fnv_hex(BASE_BYTES["json.lua"]) })
  local ad = fake_adapter({ commits = {
    [c1.candidate_sha] = { paths = { ["json.lua"] = s1 } },
    [c2.candidate_sha] = { paths = { ["json.lua"] = s2 } },
  } })
  local err = expect_error("missing_prerequisite", function()
    run(m, ad, "p", "f6", base_dir)
  end, "F6")
  ok(err.component == "needs_it" and err.prerequisite == "pre_req",
    "F6 names the member and its absent prerequisite")
end

-- F7: stale internal candidate SHA stops typed.
do
  local base_dir, digests = make_base("f7")
  local gone = comp("vanished", "9999999999999999999999999999999999999999",
    { "json.lua" }, { ["json.lua"] = "return {}\n" }, {})
  local m = manifest({ gone }, { prof("p", { "vanished" }) }, digests)
  local ad = fake_adapter({ commits = {
    -- commit absent entirely: resolver cannot resolve it
  } })
  local err = expect_error("stale_candidate_sha", function()
    run(m, ad, "p", "f7", base_dir)
  end, "F7")
  ok(err.component == "vanished", "F7 names the stale component")
end

-- F8/F12: verification catches extra files and flipped bytes.
do
  local base_dir, m, ad, c1, c2, s1, s2 = disjoint_world()
  local res, tree_dir, receipt_path = run(m, ad, "p", "f8", base_dir)

  -- untouched tree verifies clean
  local okv = pcall(compose.verify_tree, {
    tree_dir = tree_dir, inventory = res.inventory, adapter = ad,
  })
  ok(okv, "F8 freshly composed tree verifies clean")

  -- extra hand-edited file appears
  write_file(tree_dir .. "/hand_edit.lua", "return 'sneaky'\n")
  local err = expect_error("unowned_diff", function()
    compose.verify_tree({ tree_dir = tree_dir, inventory = res.inventory, adapter = ad })
  end, "F8")
  ok(err.path == "hand_edit.lua", "F8 names the unowned file")

  -- negative control: flip one generated byte after composition
  os.remove(tree_dir .. "/hand_edit.lua")
  write_file(tree_dir .. "/json.lua", (s1:gsub("one", "ONE")))
  local err2 = expect_error("unowned_diff", function()
    compose.verify_tree({ tree_dir = tree_dir, inventory = res.inventory, adapter = ad })
  end, "F12")
  ok(err2.path ~= nil, "F12 attributes the mutated file")
end

-- F9: listed-order permutation produces identical output.
do
  local base_dir, digests = make_base("f9")
  local sa = "return { chain = 'a' }\n"
  local sb = "return { chain = 'a', then_b = true }\n"
  local ca = comp("ord_a", "aaaa0000aaaa0000aaaa0000aaaa0000aaaa0000",
    { "json.lua" }, { ["json.lua"] = sa }, {})
  local cb = comp("ord_b", "bbbb0000bbbb0000bbbb0000bbbb0000bbbb0000",
    { "json.lua" }, { ["json.lua"] = sb }, { "ord_a" })
  local cu = comp("ord_u", "cccc0000cccc0000cccc0000cccc0000cccc0000",
    { "util.lua" }, { ["util.lua"] = "return { u = 1 }\n" }, {})
  local ad_spec = { commits = {
    [ca.candidate_sha] = { paths = { ["json.lua"] = sa } },
    [cb.candidate_sha] = { paths = { ["json.lua"] = sb } },
    [cu.candidate_sha] = { paths = { ["util.lua"] = "return { u = 1 }\n" } },
  }, ancestors = { [ca.candidate_sha .. ">" .. cb.candidate_sha] = true } }
  local m1 = manifest({ ca, cb, cu }, { prof("p", { "ord_a", "ord_b", "ord_u" }) }, digests)
  local m2 = manifest({ cu, cb, ca }, { prof("p", { "ord_u", "ord_b", "ord_a" }) }, digests)
  local r1 = run(m1, fake_adapter(ad_spec), "p", "f9a", base_dir)
  local r2 = run(m2, fake_adapter(ad_spec), "p", "f9b", base_dir)
  ok(r1.tree_digest == r2.tree_digest,
    "F9 permuted listed order yields identical tree digest")
  ok(r1.receipt_json == r2.receipt_json,
    "F9 permuted listed order yields byte-identical receipt")
end

-- F10: regeneration is byte-identical and second-run clean.
do
  local base_dir, m, ad = disjoint_world()
  local r1, t1, rp1 = run(m, ad, "p", "f10a", base_dir)
  local r2, t2, rp2 = run(m, ad, "p", "f10b", base_dir)
  ok(r1.tree_digest == r2.tree_digest, "F10 tree digest stable across runs")
  ok(r1.receipt_json == r2.receipt_json, "F10 receipt byte-identical across runs")
  ok(read_file(t1 .. "/util.lua") == read_file(t2 .. "/util.lua"),
    "F10 regenerated trees byte-identical")
end

-- F11: quality class rejected by core-only envelope.
do
  local base_dir, digests = make_base("f11")
  local cq = comp("quality_thing", "dddd1111dddd1111dddd1111dddd1111dddd1111",
    { "json.lua" }, { ["json.lua"] = "return { q = 1 }\n" }, {}, "quality")
  local m = manifest({ cq },
    { prof("core_like", { "quality_thing" }, { protocol = true }) }, digests)
  local ad = fake_adapter({ commits = {
    [cq.candidate_sha] = { paths = { ["json.lua"] = "return { q = 1 }\n" } },
  } })
  local err = expect_error("class_violation", function()
    run(m, ad, "core_like", "f11", base_dir)
  end, "F11")
  ok(err.component == "quality_thing", "F11 names the violating component")
  ok(err.profile == "core_like", "F11 names the rejecting profile")
end

-- F13: dependency cycle stops typed.
do
  local base_dir = make_base("f13")
  local s1 = "return { cyc = 1 }\n"
  local c1 = comp("cyc_a", "eeee1111eeee1111eeee1111eeee1111eeee1111",
    { "json.lua" }, { ["json.lua"] = s1 }, { "cyc_b" })
  local c2 = comp("cyc_b", "eeee2222eeee2222eeee2222eeee2222eeee2222",
    { "json.lua" }, { ["json.lua"] = s1 }, { "cyc_a" })
  local m = manifest({ c1, c2 }, { prof("p", { "cyc_a", "cyc_b" }) },
    { ["json.lua"] = fnv_hex(BASE_BYTES["json.lua"]) })
  local ad = fake_adapter({ commits = {
    [c1.candidate_sha] = { paths = { ["json.lua"] = s1 } },
    [c2.candidate_sha] = { paths = { ["json.lua"] = s1 } },
  } })
  expect_error("dependency_cycle", function()
    run(m, ad, "p", "f13", base_dir)
  end, "F13")
end

-- F14: new-file component materializes additively.
do
  local base_dir, digests = make_base("f14")
  local snew = "-- capability projection\nreturn {}\n"
  local cn = comp("new_filer", "ffff1111ffff1111ffff1111ffff1111ffff1111",
    { "capability_manifest.lua" },
    { ["capability_manifest.lua"] = snew }, {})
  local m = manifest({ cn }, { prof("p", { "new_filer" }) }, digests)
  local ad = fake_adapter({ commits = {
    [cn.candidate_sha] = { paths = { ["capability_manifest.lua"] = snew } },
  } })
  local res, tree_dir = run(m, ad, "p", "f14", base_dir)
  ok(res.tree["capability_manifest.lua"] == fnv_hex(snew),
    "F14 new file present in inventory")
  ok(read_file(tree_dir .. "/capability_manifest.lua") == snew,
    "F14 new file written with component bytes")
  ok(read_file(tree_dir .. "/json.lua") == BASE_BYTES["json.lua"],
    "F14 untouched base module stays pristine")
end

-- F15: empty profile materializes the pristine base exactly.
do
  local base_dir, digests = make_base("f15")
  local m = manifest({}, { prof("empty_p", {}) }, digests)
  local ad = fake_adapter({})
  local res, tree_dir = run(m, ad, "empty_p", "f15", base_dir)
  ok(read_file(tree_dir .. "/json.lua") == BASE_BYTES["json.lua"],
    "F15 json.lua is pristine")
  ok(read_file(tree_dir .. "/util.lua") == BASE_BYTES["util.lua"],
    "F15 util.lua is pristine")
  ok(res.inventory["json.lua"] == digests["json.lua"],
    "F15 inventory equals the pinned base digests")

  -- F16: a NESTED stale file from an earlier run must be cleared by the
  -- composer-owned cleanup, not silently kept beside the fresh tree.
  os.execute('mkdir "' .. tree_dir .. '/subdir" 2>nul')
  write_file(tree_dir .. "/subdir/stale.lua", "return 'stale'\n")
  local res2, tree_dir2 = run(m, ad, "empty_p", "f16", base_dir)
  ok(res2.tree_digest == res.tree_digest,
    "F16 recomposition digest unaffected by stale input")
  ok(read_file(tree_dir2 .. "/subdir/stale.lua") == nil,
    "F16 nested stale file removed by composition")
  local okv = pcall(compose.verify_tree, {
    tree_dir = tree_dir2, inventory = res2.inventory, adapter = ad,
  })
  ok(okv, "F16 regenerated tree verifies clean")
end

-- ---------------------------------------------------------------------------
-- Pending composition fixtures: immutable base/source projections and raw
-- M/A/D deltas are checked before any source bytes are admitted.
-- ---------------------------------------------------------------------------

do
  local pending_root = sandbox("pending")
  local bytes = {
    ["init.lua"] = "return { pending = 'base' }\n",
    ["json.lua"] = "return { pending = 'json' }\n",
    ["util.lua"] = "return { pending = 'util' }\n",
    ["capability_manifest.lua"] = "return { pending = 'cap' }\n",
  }
  local source_bytes = {}
  for path, value in pairs(bytes) do source_bytes[path] = value end
  source_bytes["init.lua"] = "return { pending = 'source' }\n"
  local base_blobs, source_blobs = {}, {}
  for path, value in pairs(bytes) do
    base_blobs[path] = fnv_hex(value)
    source_blobs[path] = fnv_hex(source_bytes[path])
  end
  local base_dir = sandbox("pending-base")
  for path, value in pairs(bytes) do write_file(base_dir .. "/" .. path, value) end
  local pending_manifest = manifest({}, { prof("empty", {}) }, base_blobs)
  local function pending_adapter(spec)
    return {
      component_exists = function(sha)
        return spec.components and spec.components[sha] ~= nil or false
      end,
      touched_upstream_paths = function(sha)
        local component = spec.components and spec.components[sha]
        local out = {}
        for path in pairs(component and component.paths or {}) do
          out[#out + 1] = path
        end
        table.sort(out)
        return out
      end,
      snapshot = function(sha, path, dest)
        local component = spec.components and spec.components[sha]
        local bytes = component and component.paths[path]
        if not bytes then error("missing pending component snapshot") end
        write_file(dest, bytes)
        return true
      end,
      tree_inventory = function(ref, prefix)
        local root = prefix:find("upstream") and "upstream"
          or prefix:find("tests") and "tests" or "fallback"
        local tree = spec.trees[ref] and spec.trees[ref][root] or {}
        local out = {}
        for path, blob in pairs(tree) do out[path] = blob end
        return out
      end,
      diff_entries = function() return spec.diff end,
      is_ancestor = function(a, b) return spec.ancestors[a .. ">" .. b] == true end,
      snapshot_path = function(ref, repo_path, dest)
        if repo_path:find("/tests/") then
          local suite = repo_path:match("/tests/([^/]+)$")
          write_file(dest, spec.test_bytes[ref][suite])
          return
        end
        local path = repo_path:match("/([^/]+)$")
        local value = spec.bytes[ref][path]
        if not value then error("missing pending fixture snapshot") end
        write_file(dest, value)
      end,
      hash_file = function(path) return fnv_hex(read_file(path)) end,
      digest_text = function(text) return fnv_hex(text) end,
    }
  end
  local refs = {
    base = "1111111111111111111111111111111111111111",
    source = "2222222222222222222222222222222222222222",
    wrong = "3333333333333333333333333333333333333333",
  }
  local function fixture()
    local base_tree, source_tree = {}, {}
    for path, blob in pairs(base_blobs) do base_tree[path] = blob end
    for path, blob in pairs(source_blobs) do source_tree[path] = blob end
    local base_snapshot, source_snapshot = {}, {}
    for path, value in pairs(bytes) do base_snapshot[path] = value end
    for path, value in pairs(source_bytes) do source_snapshot[path] = value end
    local proof_source = "local f = io.open(arg[1], 'rb')\n"
      .. "if not f then os.exit(1) end\nf:close()\n"
    local proof_blob = fnv_hex(proof_source)
    local spec = {
      trees = {
        [refs.base] = { upstream = base_tree, fallback = {} },
        [refs.source] = { upstream = source_tree, fallback = {} },
      },
      bytes = { [refs.base] = base_snapshot, [refs.source] = source_snapshot },
      test_bytes = { [refs.base] = { ["pending_test.lua"] = proof_source },
        [refs.source] = { ["pending_test.lua"] = proof_source } },
      pending_test_blob = proof_blob,
      ancestors = { [refs.base .. ">" .. refs.source] = true },
      diff = { { status = "M", path = "upstream/init.lua" } },
    }
    return spec, pending_adapter(spec)
  end
  local function pending_run(spec, ad, tag, delta, base_ref)
    return compose.materialize_pending({
      manifest = pending_manifest, adapter = ad, profile = "empty",
      base_dir = base_dir, out_dir = pending_root .. "/" .. tag .. "/upstream",
      receipt_path = pending_root .. "/" .. tag .. "/receipt.json",
      base_ref = base_ref or refs.base, source_ref = refs.source,
      required_modules = { "init.lua", "json.lua", "util.lua", "capability_manifest.lua" },
      declared_delta = delta or {
        { status = "M", path = "upstream/init.lua",
          base_blob = base_blobs["init.lua"], source_blob = source_blobs["init.lua"] },
      },
      suite_specs = {
        { path = "tests/pending_test.lua", source_blob = spec.pending_test_blob,
          module = "init.lua" },
      },
    })
  end
  local spec, ad = fixture()
  local accepted = pending_run(spec, ad, "accepted")
  ok(accepted.tree["init.lua"] == source_blobs["init.lua"],
    "P1 fixture applies the immutable source snapshot")
  local repeated = pending_run(spec, ad, "accepted-again")
  ok(accepted.receipt_json == repeated.receipt_json,
    "P1 fixture regeneration is byte-identical")

  local inherited_manifest = manifest({}, { prof("empty", {}) }, base_blobs)
  inherited_manifest.proof_matrix = {
    ["init.lua"] = { { suite = "inherited_profile_test.lua",
      modules = { "init.lua" } } },
  }
  local inherited_source = "local f = io.open(arg[1], 'rb')\n"
    .. "if not f then os.exit(1) end\nf:close()\n"
  local inherited_blob = fnv_hex(inherited_source)
  spec.trees[refs.base].tests = {}
  spec.trees[refs.source].tests = { ["inherited_profile_test.lua"] = inherited_blob }
  spec.test_bytes = {
    [refs.base] = {}, [refs.source] = {
      ["inherited_profile_test.lua"] = inherited_source,
    },
  }
  local inherited = compose.materialize_pending({
    manifest = inherited_manifest, adapter = ad, profile = "empty",
    base_dir = base_dir, out_dir = pending_root .. "/inherited/upstream",
    receipt_path = pending_root .. "/inherited/receipt.json",
    base_ref = refs.base, source_ref = refs.source,
    declared_delta = {
      { status = "M", path = "upstream/init.lua",
        base_blob = base_blobs["init.lua"], source_blob = source_blobs["init.lua"] },
    }, suite_specs = {},
  })
  ok(inherited.suites[1].suite == "inherited_profile_test.lua"
    and inherited.suites[1].exit_code == 0,
    "P1 selected profile proof row runs from the immutable source")

  local stale_spec, stale_ad = fixture()
  stale_spec.trees[refs.base].tests = {}
  stale_spec.trees[refs.source].tests = {}
  stale_spec.test_bytes = { [refs.base] = {}, [refs.source] = {} }
  expect_error("pending_suite", function()
    compose.materialize_pending({
      manifest = inherited_manifest, adapter = stale_ad, profile = "empty",
      base_dir = base_dir, out_dir = pending_root .. "/stale-suite/upstream",
      receipt_path = pending_root .. "/stale-suite/receipt.json",
      base_ref = refs.base, source_ref = refs.source,
      declared_delta = {
        { status = "M", path = "upstream/init.lua",
          base_blob = base_blobs["init.lua"], source_blob = source_blobs["init.lua"] },
      }, suite_specs = {},
    })
  end, "P1 inherited proof rejects a stale source suite inventory")

  local helper_spec, helper_ad = fixture()
  local helper_suite_dir = pending_root .. "/stale-helper/tests"
  write_file(helper_suite_dir .. "/harness.lua", "return true\n")
  expect_error("pending_unowned_diff", function()
    compose.materialize_pending({
      manifest = pending_manifest, adapter = helper_ad, profile = "empty",
      base_dir = base_dir, out_dir = pending_root .. "/stale-helper/upstream",
      receipt_path = pending_root .. "/stale-helper/receipt.json",
      base_ref = refs.base, source_ref = refs.source,
      declared_delta = {
        { status = "M", path = "upstream/init.lua",
          base_blob = base_blobs["init.lua"], source_blob = source_blobs["init.lua"] },
      }, suite_specs = {
        { path = "tests/pending_test.lua", source_blob = helper_spec.pending_test_blob,
          module = "init.lua" },
      },
    })
  end, "P1 exact suite staging rejects a stale helper file")

  local invalid_spec, invalid_ad = fixture()
  local invalid_source = "this is not valid lua\n"
  local invalid_blob = fnv_hex(invalid_source)
  invalid_spec.trees[refs.source].upstream["init.lua"] = invalid_blob
  invalid_spec.bytes[refs.source]["init.lua"] = invalid_source
  expect_error("pending_proof", function()
    compose.materialize_pending({
      manifest = pending_manifest, adapter = invalid_ad, profile = "empty",
      base_dir = base_dir, out_dir = pending_root .. "/invalid-lua/upstream",
      receipt_path = pending_root .. "/invalid-lua/receipt.json",
      base_ref = refs.base, source_ref = refs.source,
      declared_delta = {
        { status = "M", path = "upstream/init.lua",
          base_blob = base_blobs["init.lua"], source_blob = invalid_blob },
      }, suite_specs = {
        { path = "tests/pending_test.lua", source_blob = invalid_spec.pending_test_blob,
          module = "init.lua" },
      },
    })
  end, "P1 correct source blob still rejects invalid generated Lua")

  local receipt_spec, receipt_ad = fixture()
  local receipt_first = pending_run(receipt_spec, receipt_ad, "receipt-reuse")
  ok(read_file(receipt_first.receipt_path) ~= nil,
    "P1 successful pending composition writes its receipt")
  local original_remove = os.remove
  local original_open = io.open
  os.remove = function(path)
    if path == receipt_first.receipt_path then return nil end
    return original_remove(path)
  end
  io.open = function(path, mode)
    if path == receipt_first.receipt_path and mode == "rb" then return nil end
    return original_open(path, mode)
  end
  expect_error("pending_receipt", function()
    pending_run(receipt_spec, receipt_ad, "receipt-reuse")
  end, "P1 existing receipt removal failure blocks recomposition")
  os.remove = original_remove
  io.open = original_open
  ok(read_file(receipt_first.receipt_path) ~= nil,
    "P1 removal failure preserves the prior receipt for diagnosis")
  local receipt_invalid = "this source is invalid lua\n"
  local receipt_invalid_blob = fnv_hex(receipt_invalid)
  receipt_spec.trees[refs.source].upstream["init.lua"] = receipt_invalid_blob
  receipt_spec.bytes[refs.source]["init.lua"] = receipt_invalid
  expect_error("pending_proof", function()
    compose.materialize_pending({
      manifest = pending_manifest, adapter = receipt_ad, profile = "empty",
      base_dir = base_dir, out_dir = receipt_first.tree_dir,
      receipt_path = receipt_first.receipt_path,
      base_ref = refs.base, source_ref = refs.source,
      declared_delta = {
        { status = "M", path = "upstream/init.lua",
          base_blob = base_blobs["init.lua"], source_blob = receipt_invalid_blob },
      }, suite_specs = {
        { path = "tests/pending_test.lua", source_blob = receipt_spec.pending_test_blob,
          module = "init.lua" },
      },
    })
  end, "P1 failed recomposition invalidates the prior receipt")
  ok(read_file(receipt_first.receipt_path) == nil,
    "P1 failed recomposition leaves no stale receipt")

  local omitted_manifest = manifest({}, { prof("empty", {}) }, base_blobs)
  local omitted_spec, omitted_ad = fixture()
  expect_error("pending_proof", function()
    compose.materialize_pending({
      manifest = omitted_manifest, adapter = omitted_ad, profile = "empty",
      base_dir = base_dir, out_dir = pending_root .. "/omitted-proof/upstream",
      receipt_path = pending_root .. "/omitted-proof/receipt.json",
      base_ref = refs.base, source_ref = refs.source,
      declared_delta = {
        { status = "M", path = "upstream/init.lua",
          base_blob = base_blobs["init.lua"], source_blob = source_blobs["init.lua"] },
      }, suite_specs = {},
    })
  end, "P1 modified module requires a profile proof row")

  local deleted_spec, deleted_ad = fixture()
  deleted_spec.trees[refs.base].tests = {}
  deleted_spec.trees[refs.source].tests = { ["inherited_profile_test.lua"] = inherited_blob }
  deleted_spec.test_bytes = spec.test_bytes
  deleted_spec.trees[refs.source].upstream["init.lua"] = nil
  deleted_spec.bytes[refs.source]["init.lua"] = nil
  deleted_spec.diff = { { status = "D", path = "upstream/init.lua" } }
  expect_error("pending_required_module", function()
    compose.materialize_pending({
      manifest = inherited_manifest, adapter = deleted_ad, profile = "empty",
      base_dir = base_dir, out_dir = pending_root .. "/inherited-delete/upstream",
      receipt_path = pending_root .. "/inherited-delete/receipt.json",
      base_ref = refs.base, source_ref = refs.source,
      declared_delta = {
        { status = "D", path = "upstream/init.lua",
          base_blob = base_blobs["init.lua"] },
      }, suite_specs = {},
    })
  end, "P1 inherited proof obligation blocks required deletion")

  local wrong_base, wrong_ad = fixture()
  wrong_base.trees[refs.wrong] = { upstream = {}, fallback = {} }
  wrong_base.ancestors[refs.wrong .. ">" .. refs.source] = true
  local err = expect_error("pending_base_mismatch", function()
    compose.materialize_pending({ manifest = pending_manifest, adapter = wrong_ad,
      profile = "empty", base_dir = base_dir,
      out_dir = pending_root .. "/wrong-base/upstream",
      receipt_path = pending_root .. "/wrong-base/receipt.json",
      base_ref = refs.wrong, source_ref = refs.source,
      required_modules = { "init.lua", "json.lua", "util.lua", "capability_manifest.lua" },
      declared_delta = {}, suite_specs = {} })
  end, "P1 wrong base")
  ok(err ~= nil, "P1 wrong base refuses inherited landed coverage")

  local _, ancestry_ad = fixture()
  local ancestry_spec = fixture()
  ancestry_spec.ancestors = {}
  ancestry_ad = pending_adapter(ancestry_spec)
  expect_error("pending_source_ancestry", function()
    pending_run(ancestry_spec, ancestry_ad, "wrong-ancestry")
  end, "P1 unrelated source")

  expect_error("pending_identity", function()
    pending_run(spec, ad, "mutable-ref", {
      { status = "M", path = "upstream/init.lua",
        base_blob = base_blobs["init.lua"], source_blob = source_blobs["init.lua"] },
    }, "main")
  end, "P1 non-immutable ref")

  expect_error("pending_path_collision", function()
    compose.materialize_pending({ manifest = pending_manifest, adapter = ad,
      profile = "empty", base_dir = base_dir,
      out_dir = pending_root .. "/collision/upstream",
      receipt_path = pending_root .. "/collision/receipt.json",
      temp_dir = pending_root .. "/collision/upstream",
      base_ref = refs.base, source_ref = refs.source,
      required_modules = { "init.lua", "json.lua", "util.lua", "capability_manifest.lua" },
      declared_delta = {
        { status = "M", path = "upstream/init.lua",
          base_blob = base_blobs["init.lua"], source_blob = source_blobs["init.lua"] },
      }, suite_specs = {}, })
  end, "P1 output/temp collision")

  expect_error("pending_path_collision", function()
    compose.materialize_pending({ manifest = pending_manifest, adapter = ad,
      profile = "empty", base_dir = base_dir, out_dir = base_dir,
      receipt_path = pending_root .. "/base-collision/receipt.json",
      base_ref = refs.base, source_ref = refs.source,
      required_modules = { "init.lua", "json.lua", "util.lua", "capability_manifest.lua" },
      declared_delta = {
        { status = "M", path = "upstream/init.lua",
          base_blob = base_blobs["init.lua"], source_blob = source_blobs["init.lua"] },
      }, suite_specs = {}, })
  end, "P1 base/output collision")

  expect_error("pending_path_collision", function()
    compose.materialize_pending({ manifest = pending_manifest, adapter = ad,
      profile = "empty", base_dir = base_dir, out_dir = base_dir .. "/./",
      receipt_path = pending_root .. "/base-alias-collision/receipt.json",
      base_ref = refs.base, source_ref = refs.source,
      required_modules = { "init.lua", "json.lua", "util.lua", "capability_manifest.lua" },
      declared_delta = {
        { status = "M", path = "upstream/init.lua",
          base_blob = base_blobs["init.lua"], source_blob = source_blobs["init.lua"] },
      }, suite_specs = {}, })
  end, "P1 base/output dot alias collision")

  expect_error("pending_path_layout", function()
    compose.materialize_pending({ manifest = pending_manifest, adapter = ad,
      profile = "empty", base_dir = base_dir,
      out_dir = pending_root .. "/layout/upstream",
      suite_dir = pending_root .. "/other/tests",
      receipt_path = pending_root .. "/layout/receipt.json",
      base_ref = refs.base, source_ref = refs.source,
      required_modules = { "init.lua", "json.lua", "util.lua", "capability_manifest.lua" },
      declared_delta = {
        { status = "M", path = "upstream/init.lua",
          base_blob = base_blobs["init.lua"], source_blob = source_blobs["init.lua"] },
      }, suite_specs = {}, })
  end, "P1 suite/output sibling layout")

  local alias_dir = pending_root .. "/base-alias"
  local alias_created
  if IS_WINDOWS then
    alias_created = os.execute('cmd /c mklink /J "' .. alias_dir
      .. '" "' .. base_dir .. '" >nul 2>&1')
  else
    alias_created = os.execute('ln -s "' .. base_dir .. '" "' .. alias_dir
      .. '" 2>/dev/null')
  end
  if alias_created == true or alias_created == 0 then
    expect_error("pending_path_alias", function()
      compose.materialize_pending({ manifest = pending_manifest, adapter = ad,
        profile = "empty", base_dir = alias_dir,
        out_dir = pending_root .. "/alias-check/upstream",
        receipt_path = pending_root .. "/alias-check/receipt.json",
        base_ref = refs.base, source_ref = refs.source,
        required_modules = { "init.lua", "json.lua", "util.lua",
          "capability_manifest.lua" },
        declared_delta = {
          { status = "M", path = "upstream/init.lua",
            base_blob = base_blobs["init.lua"],
            source_blob = source_blobs["init.lua"] },
        }, suite_specs = {}, })
    end, "P1 existing directory alias is rejected before mutation")
  else
    print("P1 directory alias probe: NOT RUN (alias creation unavailable)")
  end

  local unsupported_spec, unsupported_ad = fixture()
  unsupported_spec.diff = { { status = "R", path = "upstream/init.lua" } }
  expect_error("pending_delta_mismatch", function()
    pending_run(unsupported_spec, unsupported_ad, "unsupported-status")
  end, "P1 unsupported diff status")

  expect_error("pending_suite", function()
    compose.materialize_pending({ manifest = pending_manifest, adapter = ad,
      profile = "empty", base_dir = base_dir,
      out_dir = pending_root .. "/suite-traversal/upstream",
      receipt_path = pending_root .. "/suite-traversal/receipt.json",
      base_ref = refs.base, source_ref = refs.source,
      required_modules = { "init.lua", "json.lua", "util.lua", "capability_manifest.lua" },
      declared_delta = {
        { status = "M", path = "upstream/init.lua",
          base_blob = base_blobs["init.lua"], source_blob = source_blobs["init.lua"] },
      }, suite_specs = {
        { path = "../tests/bad.lua", source_blob = source_blobs["init.lua"] },
      }, })
  end, "P1 suite traversal")

  expect_error("pending_required_module", function()
    compose.materialize_pending({ manifest = pending_manifest, adapter = ad,
      profile = "empty", base_dir = base_dir,
      out_dir = pending_root .. "/suite-module/upstream",
      receipt_path = pending_root .. "/suite-module/receipt.json",
      base_ref = refs.base, source_ref = refs.source,
      required_modules = { "init.lua", "json.lua", "util.lua", "capability_manifest.lua" },
      declared_delta = {
        { status = "M", path = "upstream/init.lua",
          base_blob = base_blobs["init.lua"], source_blob = source_blobs["init.lua"] },
      }, suite_specs = {
        { path = "tests/missing.lua", source_blob = source_blobs["init.lua"], module = "missing.lua" },
      }, })
  end, "P1 suite module missing from tree")

  local _, blob_ad = fixture()
  expect_error("pending_delta_mismatch", function()
    pending_run(spec, blob_ad, "wrong-blob", {
      { status = "M", path = "upstream/init.lua",
        base_blob = "00000000", source_blob = source_blobs["init.lua"] },
    })
  end, "P1 wrong blob")

  local extra_spec, extra_ad = fixture()
  extra_spec.trees[refs.source].upstream["extra.lua"] = fnv_hex("extra\n")
  extra_spec.bytes[refs.source]["extra.lua"] = "extra\n"
  extra_spec.diff[#extra_spec.diff + 1] = { status = "A", path = "upstream/extra.lua" }
  expect_error("pending_delta_mismatch", function()
    pending_run(extra_spec, extra_ad, "extra-path")
  end, "P1 undeclared extra path")

  local missing_spec, missing_ad = fixture()
  missing_spec.trees[refs.source].upstream["capability_manifest.lua"] = nil
  missing_spec.bytes[refs.source]["capability_manifest.lua"] = nil
  missing_spec.diff[#missing_spec.diff + 1] =
    { status = "D", path = "upstream/capability_manifest.lua" }
  expect_error("pending_required_module", function()
    pending_run(missing_spec, missing_ad, "missing-required", {
      { status = "M", path = "upstream/init.lua",
        base_blob = base_blobs["init.lua"], source_blob = source_blobs["init.lua"] },
      { status = "D", path = "upstream/capability_manifest.lua",
        base_blob = base_blobs["capability_manifest.lua"] },
    })
  end, "P1 missing required inherited module")

  -- A source rename is deliberately represented as a delete plus an add;
  -- neither Git's rename heuristic nor a modify-only shortcut may hide it.
  local rename_spec, rename_ad = fixture()
  local rename_bytes = {}
  for path, value in pairs(bytes) do rename_bytes[path] = value end
  rename_bytes["obsolete.lua"] = "return { obsolete = true }\n"
  local renamed_source = {}
  for path, value in pairs(source_bytes) do renamed_source[path] = value end
  renamed_source["renamed.lua"] = "return { renamed = true }\n"
  local rename_base_blobs, rename_source_blobs = {}, {}
  for path, value in pairs(rename_bytes) do
    rename_base_blobs[path] = fnv_hex(value)
  end
  for path, value in pairs(renamed_source) do
    rename_source_blobs[path] = fnv_hex(value)
  end
  write_file(base_dir .. "/obsolete.lua", rename_bytes["obsolete.lua"])
  rename_spec.trees[refs.base].upstream["obsolete.lua"] = rename_base_blobs["obsolete.lua"]
  rename_spec.trees[refs.source].upstream["renamed.lua"] = rename_source_blobs["renamed.lua"]
  rename_spec.bytes[refs.base] = rename_bytes
  rename_spec.bytes[refs.source] = renamed_source
  local optional_sha = "3333333333333333333333333333333333333333"
  rename_spec.components = { [optional_sha] = { paths = {
    ["obsolete.lua"] = rename_bytes["obsolete.lua"],
  } } }
  rename_spec.diff = {
    { status = "A", path = "upstream/renamed.lua" },
    { status = "D", path = "upstream/obsolete.lua" },
    { status = "M", path = "upstream/init.lua" },
  }
  local rename_base_files = {}
  for path, blob in pairs(base_blobs) do rename_base_files[path] = blob end
  local rename_manifest = manifest({
    comp("optional", optional_sha, { "obsolete.lua" },
      { ["obsolete.lua"] = rename_bytes["obsolete.lua"] }),
  }, { prof("empty", { "optional" }) }, rename_base_files)
  local rename_result = compose.materialize_pending({
    manifest = rename_manifest, adapter = rename_ad, profile = "empty",
    base_dir = base_dir, out_dir = pending_root .. "/rename/upstream",
    receipt_path = pending_root .. "/rename/receipt.json",
    base_ref = refs.base, source_ref = refs.source,
    required_modules = { "init.lua", "json.lua", "util.lua", "capability_manifest.lua" },
    declared_delta = {
      { status = "A", path = "upstream/renamed.lua",
        source_blob = rename_source_blobs["renamed.lua"] },
      { status = "D", path = "upstream/obsolete.lua",
        base_blob = rename_base_blobs["obsolete.lua"] },
      { status = "M", path = "upstream/init.lua",
        base_blob = rename_base_blobs["init.lua"],
        source_blob = rename_source_blobs["init.lua"] },
    },
    suite_specs = {
      { path = "tests/pending_test.lua", source_blob = rename_spec.pending_test_blob,
        modules = { "init.lua", "renamed.lua" } },
    },
  })
  ok(rename_result.tree["renamed.lua"] == rename_source_blobs["renamed.lua"],
    "P1 rename-as-add installs the new source path")
  ok(rename_result.tree["obsolete.lua"] == nil,
    "P1 optional component delete removes its effective module")

  local runtime_spec, runtime_ad = fixture()
  local runtime_bytes = "return { runtime = true }\n"
  local runtime_blob = fnv_hex(runtime_bytes)
  local runtime_base_blobs = {}
  for path, blob in pairs(base_blobs) do runtime_base_blobs[path] = blob end
  runtime_base_blobs["listbox.lua"] = runtime_blob
  write_file(base_dir .. "/listbox.lua", runtime_bytes)
  runtime_spec.trees[refs.base].upstream["listbox.lua"] = runtime_blob
  runtime_spec.trees[refs.source].upstream["listbox.lua"] = nil
  runtime_spec.bytes[refs.base]["listbox.lua"] = runtime_bytes
  runtime_spec.bytes[refs.source]["listbox.lua"] = nil
  runtime_spec.diff = { { status = "D", path = "upstream/listbox.lua",
    base_blob = runtime_blob } }
  local runtime_manifest = manifest({}, { prof("empty", {}) }, runtime_base_blobs)
  expect_error("pending_required_module", function()
    compose.materialize_pending({
      manifest = runtime_manifest, adapter = runtime_ad, profile = "empty",
      base_dir = base_dir, out_dir = pending_root .. "/runtime-delete/upstream",
      receipt_path = pending_root .. "/runtime-delete/receipt.json",
      base_ref = refs.base, source_ref = refs.source,
      declared_delta = { { status = "D", path = "upstream/listbox.lua",
        base_blob = runtime_blob } }, suite_specs = {},
    })
  end, "P1 pristine runtime module deletion requires projected retention")

  local function fake_popen(lines, close_result)
    local handle = {}
    function handle:lines()
      local index = 0
      return function()
        index = index + 1
        return lines[index]
      end
    end
    function handle:close()
      return table.unpack(close_result)
    end
    return handle
  end
  local function with_fake_popen(lines, close_result, fn, on_open)
    local original = io.popen
    io.popen = function(command)
      if on_open then on_open(command) end
      return fake_popen(lines, close_result)
    end
    local ran, result = pcall(fn)
    io.popen = original
    if not ran then error(result, 0) end
    return result
  end
  local empty_git = compose.git_adapter({ repo_root = scratch_root })
  local empty_inventory = with_fake_popen({}, { true }, function()
    return empty_git.tree_inventory(refs.source, "clients/lite-xl/tests")
  end)
  local empty_delta = with_fake_popen({}, { true }, function()
    return empty_git.diff_entries(refs.base, refs.source,
      { "clients/lite-xl/upstream" })
  end)
  ok(next(empty_inventory) == nil and next(empty_delta) == nil,
    "P1 proof Git reads preserve successful empty output")

  local failed_git = compose.git_adapter({ repo_root = scratch_root })
  expect_error("pending_tree_inventory", function()
    with_fake_popen({}, { nil, "exit", 1 }, function()
      return failed_git.tree_inventory(refs.source, "clients/lite-xl/tests")
    end)
  end, "P1 failed tree read cannot become an empty inventory")
  expect_error("pending_diff", function()
    with_fake_popen({}, { nil, "exit", 1 }, function()
      return failed_git.diff_entries(refs.base, refs.source,
        { "clients/lite-xl/upstream" })
    end)
  end, "P1 failed diff read cannot become an empty delta")

  local abnormal_git = compose.git_adapter({ repo_root = scratch_root })
  expect_error("pending_tree_inventory", function()
    with_fake_popen({}, { nil, "signal", 9 }, function()
      return abnormal_git.tree_inventory(refs.source, "clients/lite-xl/tests")
    end)
  end, "P1 abnormal tree read fails closed")
  expect_error("pending_diff", function()
    with_fake_popen({}, { nil, "signal", 9 }, function()
      return abnormal_git.diff_entries(refs.base, refs.source,
        { "clients/lite-xl/upstream" })
    end)
  end, "P1 abnormal diff read fails closed")

  local shell_calls = 0
  local shell_git = compose.git_adapter({ repo_root = scratch_root })
  with_fake_popen({}, { true }, function()
    expect_error("unsafe_shell_path", function()
      shell_git.tree_inventory(refs.source, "clients/lite-xl/tests/evil&name")
    end, "P1 shell-active tree path is rejected before execution")
  end, function() shell_calls = shell_calls + 1 end)
  ok(shell_calls == 0, "P1 denied shell path does not reach the process")
  local allowed_inventory = with_fake_popen({}, { true }, function()
    return shell_git.tree_inventory(refs.source,
      "clients/lite-xl/tests/allowed name.lua")
  end, function() shell_calls = shell_calls + 1 end)
  ok(next(allowed_inventory) == nil and shell_calls == 1,
    "P1 safe tree path reaches the mocked process")

  local clean_tree = pending_root .. "/accepted-again/upstream"
  write_file(clean_tree .. "/hand-edit.lua", "return true\n")
  expect_error("unowned_diff", function()
    compose.verify_tree({ tree_dir = clean_tree,
      inventory = accepted.inventory, adapter = ad })
  end, "P1 extra generated file")
  os.remove(clean_tree .. "/hand-edit.lua")
  write_file(clean_tree .. "/init.lua", "return { mutated = true }\n")
  expect_error("unowned_diff", function()
    compose.verify_tree({ tree_dir = clean_tree,
      inventory = accepted.inventory, adapter = ad })
  end, "P1 mutated generated file")
end

print(string.format("compose_materializer_test: %d passed, %d failed", passed, failed))
os.exit(failed == 0 and 0 or 1)
