//! The bounded representative fixture-node registry mandated by #11286.
//!
//! Every node's stable semantics are anchored to its owning issue; this file
//! compiles those anchors into typed rows (role, domain, policy, artifacts,
//! falsifiers, lenses, old-path exits). It encodes no readiness evaluation
//! and no observational state: observational planes degrade honestly to
//! `unavailable` until their owning trains land (#11280/#11281/#11283).

use super::model::{
    ArtifactMode, ArtifactRow, Authority, AuthorityGroup, ControlRow, DenominatorDisposition,
    DenominatorEntry, Disposition, Domain, DurableSpecDisposition, LensSpec, NodeSpec, OldPathRow,
    OperationRow, Profile, Role, StageExample,
};

/// Parent routing controller for feature-readiness (#10122).
const CONTROLLER_FR: u32 = 10122;

/// Surfaces no packet may authorize, inherited from the FR-C05 contract.
const FORBIDDEN_SHARED: &[&str] = &[
    "model invocation or agent scheduling machinery",
    "generic prompt framework or .spec planning tree",
    "support/release/publication state mutation",
];

/// Stage-specific falsification examples drawn verbatim from the #11286
/// reviewer contract; packets select the stages applicable to their role.
pub const STAGE_EXAMPLES: &[StageExample] = &[
    StageExample {
        stage: "parser_semantic_workspace_subject",
        question: "Can current text combine with an older parser/semantic/workspace subject?",
    },
    StageExample {
        stage: "instrument_failure_empty_success",
        question: "Can missing/not-ready/instrument failure become [], null, no-change or clean success?",
    },
    StageExample {
        stage: "old_path_still_live",
        question: "Can an old/private provider/action/formatter/import path still run?",
    },
    StageExample {
        stage: "cross_root_framework_client_platform",
        question: "Can another root/framework/client/platform/artifact satisfy the oracle?",
    },
    StageExample {
        stage: "held_edit_across_movement",
        question: "Can a held edit/prepare/action/result survive source/config/root/instance movement?",
    },
    StageExample {
        stage: "partial_result_disappearance",
        question: "Can an invalid edit/result member disappear while the rest pass?",
    },
    StageExample {
        stage: "fixture_as_semantic_support",
        question: "Can a grammar fixture or token type satisfy framework semantic support?",
    },
    StageExample {
        stage: "external_tool_presence_default",
        question: "Can external-tool presence change the native default?",
    },
    StageExample {
        stage: "proof_repairs_product",
        question: "Can a proof/installed PR repair product behavior?",
    },
    StageExample {
        stage: "artifact_stage_crosstalk",
        question: "Can a candidate/public artifact or one client stage satisfy another?",
    },
    StageExample {
        stage: "missing_required_artifact",
        question: "Can a required artifact/generator/check be missing while prose claims completeness?",
    },
];

fn currentness_lens(extra: &'static [&'static str]) -> LensSpec {
    LensSpec {
        name: "coherent_subject_currentness",
        applicable: true,
        reason: "the review binds exactly one source/document/root/configuration subject at one head",
        questions: extra,
    }
}

fn stage_separation_lens() -> LensSpec {
    LensSpec {
        name: "stage_separation",
        applicable: true,
        reason: "proof, installed-client, research, and governance stages must never repair product behavior",
        questions: &["Can this proof/installed/research PR be read as repairing product behavior?"],
    }
}

fn authority(reference: &'static str, subject: &'static str, group: AuthorityGroup) -> Authority {
    Authority { reference, subject, group }
}

#[allow(clippy::too_many_arguments)]
fn op(
    feature: &'static str,
    provider_or_client: &'static str,
    source_subject: &'static str,
    semantic: &'static str,
    currentness: &'static str,
    fallback: &'static str,
    refusal: &'static str,
    legitimate_empty: &'static str,
    canonical_owner: &'static str,
    old_path: &'static str,
    proof_owner: &'static str,
) -> OperationRow {
    OperationRow {
        feature,
        provider_or_client,
        source_subject,
        policy_semantic: semantic,
        policy_currentness: currentness,
        policy_fallback: fallback,
        policy_refusal: refusal,
        policy_legitimate_empty: legitimate_empty,
        canonical_owner,
        old_path,
        proof_owner,
    }
}

#[allow(clippy::too_many_arguments)]
fn artifact(
    id: &'static str,
    kind: &'static str,
    owner: &'static str,
    mode: ArtifactMode,
    current_disposition: &'static str,
    required_change_or_proof: &'static str,
    check_command: &'static str,
    review_lens: &'static str,
    claim_impact: &'static str,
) -> ArtifactRow {
    ArtifactRow {
        id,
        kind,
        owner,
        mode,
        current_disposition,
        required_change_or_proof,
        check_command,
        review_lens,
        claim_impact,
    }
}

fn control(class: &'static str, subject: &'static str) -> ControlRow {
    ControlRow { class, subject }
}

const XTEST_FOCUS: (&str, &str, &str) = (
    "xtask_feature_readiness_packets",
    "cargo test -p xtask --all-targets --locked feature_readiness_packets",
    "focused_proof",
);

#[allow(clippy::too_many_arguments)]
fn node(
    node_id: &'static str,
    issues: &[u32],
    controller_issue: u32,
    domain: Domain,
    role: Role,
    disposition: Disposition,
    profile: Profile,
    objective_sentence: &'static str,
    establishes: &[&'static str],
    cannot_establish: &[&'static str],
    prerequisite_disposition: &'static str,
    successors: &[&'static str],
    remaining_not_proven: &[&'static str],
    rollback_meaning: &'static str,
    authorities: &[Authority],
    operations: &[OperationRow],
    allowed_surfaces: &[&'static str],
    forbidden_surfaces: &[&'static str],
    artifacts: &[ArtifactRow],
    durable_spec: (DurableSpecDisposition, &'static str, &'static str),
    first_falsifier: (&'static str, &'static str, &'static str),
    positive_discriminator: &'static str,
    controls: &[ControlRow],
    commands: &[(&'static str, &'static str, &'static str)],
    lenses: &[LensSpec],
    stage_examples: &[usize],
    old_paths: &[OldPathRow],
    extra_stop_conditions: &[&'static str],
) -> NodeSpec {
    NodeSpec {
        node_id,
        issues: issues.to_vec(),
        controller_issue,
        domain,
        role,
        disposition,
        profile,
        objective_sentence,
        establishes: establishes.to_vec(),
        cannot_establish: cannot_establish.to_vec(),
        prerequisite_disposition,
        successors: successors.to_vec(),
        remaining_not_proven: remaining_not_proven.to_vec(),
        rollback_meaning,
        authorities: authorities.to_vec(),
        operations: operations.to_vec(),
        allowed_surfaces: allowed_surfaces.to_vec(),
        forbidden_surfaces: forbidden_surfaces.to_vec(),
        artifacts: artifacts.to_vec(),
        durable_spec,
        first_falsifier,
        positive_discriminator,
        controls: controls.to_vec(),
        commands: commands.to_vec(),
        lenses: lenses.to_vec(),
        stage_examples: stage_examples.to_vec(),
        old_paths: old_paths.to_vec(),
        extra_stop_conditions: extra_stop_conditions.to_vec(),
    }
}

fn node_fr_8305() -> NodeSpec {
    node(
        "fr_8305_import_containment_leaf",
        &[8305],
        8277,
        Domain::Imports,
        Role::ProductImplementation,
        Disposition::Actionable,
        Profile::CoreSemantic,
        "Keep the legacy organize-imports edit contained until a safe cohort is admitted, with every reachable path owned by the canonical import edit context.",
        &["no unsafe legacy organize-imports edit path is reachable"],
        &["safe-cohort admission timing", "edit quality beyond containment"],
        "#8277 governs cohort admission; this leaf only holds the containment line",
        &["fr_8277_import_governed_operations_leaf"],
        &["live editor cohort observation"],
        "revert restores the prior containment state; no data migration exists",
        &[
            authority(
                "#8277",
                "imports programme controller",
                AuthorityGroup::MustAlreadyBeCurrent,
            ),
            authority("#8305", "containment ruling", AuthorityGroup::MustAlreadyBeCurrent),
            authority(
                "import-edit-context",
                "canonical import edit context module",
                AuthorityGroup::OwnedByThisNode,
            ),
            authority(
                "schemas/agent_implementation_packet.v1",
                "shared builder-packet schema",
                AuthorityGroup::MustBeConsumedNeverReimplemented,
            ),
        ],
        &[op(
            "organize_imports",
            "builtin LSP edit provider",
            "current document text at request time",
            "edits are containment-only until cohort rules admit reordering",
            "the decision reads the current document version, never a cached one",
            "no silent fallback edit; unsupported shapes refuse",
            "unsupported document shapes refuse with an explicit error",
            "an empty edit plan is a legitimate outcome, never an error",
            "canonical import edit context module",
            "legacy organize-imports action entry point stays unreachable",
            "transition-proof pattern owned by #10724 for formatting; this leaf owns its own focused fixtures",
        )],
        &["canonical import edit context module and its focused tests"],
        FORBIDDEN_SHARED,
        &[
            artifact(
                "art_import_containment_fixtures",
                "regression fixtures",
                "owned_by_this_node",
                ArtifactMode::Update,
                "existing containment fixtures cover admitted shapes only",
                "extend to prove refusal on unsafe shapes and empty-plan legitimacy",
                XTEST_FOCUS.1,
                "fallback_refusal_legitimate_empty_truth",
                "keeps the containment claim falsifiable",
            ),
            artifact(
                "art_capability_manifest",
                "advertised capability manifest",
                "must_already_be_current owner crate",
                ArtifactMode::ProveUnchanged,
                "advertisement already excludes legacy reordering",
                "prove unchanged after the leaf lands",
                "cargo test -p perl-lsp-rs --all-targets --locked capability",
                "public_api_claim_consistency",
                "prevents advertisement drift against the containment claim",
            ),
        ],
        (
            DurableSpecDisposition::IssuePlanSufficientForThisLeaf,
            "#8305 body plus the #8277 controller",
            "the bounded containment plan fits the issue bodies; no new durable spec owner is created",
        ),
        (
            "invoke the legacy organize-imports action on an unsafe document shape",
            "request refuses instead of returning a partial reorder edit",
            "canonical import edit context module",
        ),
        "a supported shape yields exactly the containment-scoped edit set",
        &[
            control("unsafe_edit", "legacy action invoked on a multi-range selection"),
            control("stale", "edit computed against a superseded document version"),
            control("mutation", "remove the containment guard; the refusal fixture must fail"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&[
                "Can the refusal fire against a stale workspace subject and pass vacuously?",
            ]),
            LensSpec {
                name: "unsafe_edit_complete_set_reauthorization",
                applicable: true,
                reason: "the seam is precisely an unsafe-edit boundary",
                questions: &["Can a held edit survive source movement between prepare and apply?"],
            },
        ],
        &[4usize, 2],
        &[OldPathRow {
            seam: "legacy organize-imports action entry point",
            terminal_disposition: "unreachable",
        }],
        &["stop before admitting any cohort; admission belongs to #8277"],
    )
}

fn node_fr_5108() -> NodeSpec {
    node(
        "fr_5108_navigation_truth_repair",
        &[5108],
        CONTROLLER_FR,
        Domain::Navigation,
        Role::ProductImplementation,
        Disposition::Actionable,
        Profile::CoreSemantic,
        "Preserve definition and references errors as errors instead of returning empty success.",
        &["navigation failures surface as explicit errors, never as clean empty results"],
        &["result ranking quality", "cross-file index completeness"],
        "no blocking prerequisite; the repair is local to navigation providers",
        &[],
        &["global index freshness beyond the provider boundary"],
        "revert restores prior behavior; no persisted state changes",
        &[
            authority("#5108", "navigation truth ruling", AuthorityGroup::MustAlreadyBeCurrent),
            authority(
                "definition-provider",
                "canonical definition provider",
                AuthorityGroup::OwnedByThisNode,
            ),
            authority(
                "references-provider",
                "canonical references provider",
                AuthorityGroup::OwnedByThisNode,
            ),
        ],
        &[op(
            "definition_and_references",
            "LSP navigation providers",
            "current open document plus workspace index at request time",
            "errors are truth: failure of the underlying lookup propagates",
            "providers observe the current document version and live index handle",
            "no fallback masks a failed lookup as empty",
            "failed lookups return an explicit error response",
            "genuinely empty result sets remain empty successes only when the lookup itself succeeded",
            "definition/references provider modules",
            "empty-success masking paths removed",
            "focused provider tests owned by this node",
        )],
        &["navigation provider modules and focused provider tests"],
        FORBIDDEN_SHARED,
        &[
            artifact(
                "art_navigation_error_fixtures",
                "regression fixtures",
                "owned_by_this_node",
                ArtifactMode::Create,
                "no fixture distinguishes failed lookup from legitimate empty",
                "create fixtures for both cells and assert distinct responses",
                XTEST_FOCUS.1,
                "fallback_refusal_legitimate_empty_truth",
                "the first falsifier materializes here",
            ),
            artifact(
                "art_lsp_snapshot_suite",
                "snapshot suite",
                "owning crate test suite",
                ArtifactMode::Update,
                "snapshots encode empty-success on failure",
                "refresh snapshots to the error-bearing responses",
                "cargo test -p perl-lsp-rs --all-targets --locked snapshots",
                "artifact_completeness",
                "prevents silent snapshot acceptance of the old masking",
            ),
        ],
        (
            DurableSpecDisposition::IssuePlanSufficientForThisLeaf,
            "#5108 body",
            "one-sentence truth rule; already normative for navigation",
        ),
        (
            "force the definition lookup backend to fail and observe an empty-success response",
            "provider returns an error response, so the masking test fails red",
            "definition provider focused test",
        ),
        "a successful lookup on a symbol-free document returns empty results without error",
        &[
            control("false_empty", "backend failure coerced into an empty success"),
            control(
                "wrong_subject",
                "test asserted against a mock provider instead of the canonical one",
            ),
            control("mutation", "reintroduce masking; the forced-failure fixture must fail"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&[
                "Does the fixture pin the exact head so an older binary cannot satisfy it?",
            ]),
            LensSpec {
                name: "fallback_refusal_legitimate_empty_truth",
                applicable: true,
                reason: "the entire claim is the empty/error distinction",
                questions: &[
                    "Can instrument failure still become [] or null anywhere in the path?",
                ],
            },
        ],
        &[1usize, 0],
        &[OldPathRow {
            seam: "empty-success masking return path",
            terminal_disposition: "removed",
        }],
        &[],
    )
}

fn node_fr_8944() -> NodeSpec {
    node(
        "fr_8944_signature_semantic_cutover",
        &[8944],
        CONTROLLER_FR,
        Domain::SignatureHelp,
        Role::ProductImplementation,
        Disposition::Actionable,
        Profile::CoreSemantic,
        "Converge signature help on the canonical callable and call-binding facts so every served signature traces to compiler-owned semantics.",
        &["signature help serves only canonical callable/call-binding-derived signatures"],
        &["nested closure heuristics beyond canonical facts"],
        "compiler fact surfaces consumed by this leaf are already current on main",
        &[],
        &["multi-language embedded-call resolution"],
        "revert restores heuristic serving; no persisted state changes",
        &[
            authority(
                "compiler-call-facts",
                "compiler callable fact surface",
                AuthorityGroup::MustBeConsumedNeverReimplemented,
            ),
            authority("#8944", "cutover contract", AuthorityGroup::MustAlreadyBeCurrent),
            authority(
                "signature-help-provider",
                "canonical signature help provider",
                AuthorityGroup::OwnedByThisNode,
            ),
        ],
        &[op(
            "signature_help",
            "LSP signature help provider",
            "call-site text plus compiler call-binding facts at the cursor",
            "signatures derive from canonical callable and call-binding facts",
            "facts are resolved for the current document state per request",
            "unsupported call shapes refuse rather than guess a signature",
            "non-call positions return null explicitly, never a guessed signature",
            "zero candidates is legitimate only when the position is genuinely outside any call",
            "signature help provider module",
            "heuristic string-signature path retired",
            "focused provider tests owned by this node",
        )],
        &["signature help provider module and focused tests"],
        FORBIDDEN_SHARED,
        &[
            artifact(
                "art_signature_fact_fixtures",
                "regression fixtures",
                "owned_by_this_node",
                ArtifactMode::Create,
                "fixtures cover string heuristics, not compiler facts",
                "create call-binding fixtures including shadowed builtins and method calls",
                XTEST_FOCUS.1,
                "semantic_authority",
                "proves cutover to compiler facts",
            ),
            artifact(
                "art_signature_old_path_audit",
                "old-path audit row",
                "owned_by_this_node",
                ArtifactMode::Create,
                "heuristic path still compiled",
                "record removal/unreachable disposition after cutover",
                XTEST_FOCUS.1,
                "old_path_retirement",
                "convergence requires the old path to be terminal",
            ),
        ],
        (
            DurableSpecDisposition::CompileDurableDeltaIntoExistingOwner,
            "the LSP architecture contract surfaced by #9150",
            "the cutover delta compiles into the existing architecture owner rather than a new spec tree",
        ),
        (
            "serve signature help for a sub whose name shadows a builtin and compare against compiler facts",
            "heuristic provider emits the builtin signature, failing the canonical-fact assertion",
            "signature help focused test",
        ),
        "a direct builtin call serves exactly the compiler-declared signature",
        &[
            control("duplicate_authority", "a second signature table beside the compiler facts"),
            control("near_miss_framework", "embedded grammar metadata satisfying the oracle"),
            control("mutation", "feed a stale fact cache; the shadow test must fail"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&[
                "Can the served signature come from an older parse of the same buffer?",
            ]),
            LensSpec {
                name: "semantic_authority",
                applicable: true,
                reason: "cutover means exactly one semantic authority serves signatures",
                questions: &["Can any non-compiler surface still author a served signature?"],
            },
        ],
        &[0usize, 3],
        &[OldPathRow { seam: "string-heuristic signature path", terminal_disposition: "removed" }],
        &[],
    )
}

fn node_fr_1850() -> NodeSpec {
    node(
        "fr_1850_semantic_token_geometry",
        &[1850],
        CONTROLLER_FR,
        Domain::SemanticTokens,
        Role::ProductImplementation,
        Disposition::Actionable,
        Profile::CoreSemantic,
        "Normalize multiline semantic-token spans into valid nonzero line-contained tokens.",
        &["emitted token geometry satisfies the LSP line-containment invariants"],
        &["token classification accuracy", "client-side rendering"],
        "none; geometry normalization is local to the legend/projection boundary",
        &["fr_11250_semantic_token_shadow", "fr_11259_semantic_token_live_cutover"],
        &["client-specific multiline workarounds"],
        "revert restores prior geometry; clients re-render on next sync",
        &[
            authority("#1850", "geometry invariant ruling", AuthorityGroup::MustAlreadyBeCurrent),
            authority(
                "semantic-token-projection",
                "canonical token projection module",
                AuthorityGroup::OwnedByThisNode,
            ),
        ],
        &[op(
            "semantic_tokens_full_and_range",
            "LSP semantic tokens provider",
            "current document parse at request time",
            "multiline matches split into per-line nonzero-length tokens",
            "tokens computed from the current parse, never a cached span set",
            "no fallback emits out-of-range deltas",
            "malformed spans are dropped only when provably unrepresentable, never silently rewritten",
            "empty token arrays are legitimate for token-free documents",
            "semantic token projection module",
            "raw multiline span emission removed",
            "focused geometry tests owned by this node",
        )],
        &["semantic token projection module and focused geometry tests"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_token_geometry_fixtures",
            "geometry fixtures",
            "owned_by_this_node",
            ArtifactMode::Create,
            "no multiline-span fixture exists",
            "create POD blocks/heredocs/multiline comments asserting per-line validity",
            XTEST_FOCUS.1,
            "artifact_completeness",
            "first falsifier materializes here",
        )],
        (
            DurableSpecDisposition::ExistingNormativeContractSufficient,
            "LSP 3.17 semantic token invariants already pinned by check-lsp-318-claims",
            "the existing claims gate owns the invariant; no new durable spec",
        ),
        (
            "emit tokens for a multiline POD block and validate every delta against line containment",
            "raw emission produces a zero-length or cross-line token, failing the validator",
            "focused geometry test",
        ),
        "all tokens for a mixed single/multiline document pass the invariant validator",
        &[
            control(
                "near_miss_artifact_stage",
                "legend-index drift making a valid delta classify wrongly",
            ),
            control("stale", "span set from a previous document version"),
            control("mutation", "allow one cross-line token; the validator must fail"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&[
                "Do emitted deltas reference the parse of the served document version?",
            ]),
            LensSpec {
                name: "artifact_completeness",
                applicable: true,
                reason: "geometry claims fail through missing fixture cells",
                questions: &["Can a required geometry cell be missing while the suite passes?"],
            },
        ],
        &[1usize, 9],
        &[OldPathRow { seam: "raw multiline span emission", terminal_disposition: "removed" }],
        &[],
    )
}

fn node_fr_11250_shadow() -> NodeSpec {
    node(
        "fr_11250_semantic_token_shadow",
        &[11250],
        CONTROLLER_FR,
        Domain::SemanticTokens,
        Role::ProductImplementation,
        Disposition::Actionable,
        Profile::CoreSemantic,
        "Shadow canonical source-role and binding candidates behind instrumentation without changing live classification output.",
        &[
            "canonical candidates exist and are observable in shadow comparisons while live bytes stay identical",
        ],
        &["any live-output change (that is #11259's ceiling)"],
        "fr_1850 geometry normalization landed first",
        &["fr_11259_semantic_token_live_cutover"],
        &["shadow parity across every client theme"],
        "disable the shadow instrumentation; live path untouched",
        &[
            authority("#11250", "shadow contract", AuthorityGroup::MustAlreadyBeCurrent),
            authority("#11259", "successor cutover", AuthorityGroup::ConsumerFanInAfterPr),
            authority(
                "shadow-comparator",
                "existing shadow comparison harness pattern",
                AuthorityGroup::MustBeConsumedNeverReimplemented,
            ),
        ],
        &[op(
            "semantic_tokens_shadow",
            "instrumented provider alongside live provider",
            "same document subjects as the live provider",
            "candidate classification computed but discarded before response assembly",
            "shadow reads identical inputs at the same version as live",
            "instrument failure disables shadow only, never live output",
            "shadow failure is recorded, never surfaced as a diagnostic to users",
            "an absent shadow result for token-free documents is legitimate",
            "shadow candidate modules",
            "none yet; the live heuristic path remains until #11259",
            "shadow parity tests owned by this node",
        )],
        &["shadow candidate modules and parity tests"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_shadow_parity_receipt",
            "parity receipt generator",
            "owned_by_this_node",
            ArtifactMode::Create,
            "no shadow comparison exists",
            "create byte-equality receipt over representative corpus",
            XTEST_FOCUS.1,
            "stage_separation",
            "proves the ceiling: live bytes unchanged",
        )],
        (
            DurableSpecDisposition::IssuePlanSufficientForThisLeaf,
            "#11250 body",
            "shadow scope is fully specified by the issue",
        ),
        (
            "mutate a candidate classifier and confirm the parity receipt still passes because shadow bytes never reach the wire",
            "a naive implementation leaks candidates into live output and fails byte equality",
            "parity receipt test",
        ),
        "representative corpus renders byte-identical live tokens with shadow enabled and disabled",
        &[
            control("near_miss_client", "a client-specific renderer satisfying the parity oracle"),
            control(
                "mutation",
                "flip one candidate class; parity must hold while shadow receipts change",
            ),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&["Is shadow compared against the same document version as live?"]),
            stage_separation_lens(),
        ],
        &[9usize, 1],
        &[],
        &["stop before any live-output flip; that is #11259's claim"],
    )
}

fn node_fr_11259() -> NodeSpec {
    node(
        "fr_11259_semantic_token_live_cutover",
        &[11259],
        CONTROLLER_FR,
        Domain::SemanticTokens,
        Role::ProductImplementation,
        Disposition::Actionable,
        Profile::CoreSemantic,
        "Cut live full-semantic classification over to the canonical candidates validated by #11250's shadow evidence.",
        &["live responses are produced by the canonical candidate path"],
        &["candidate accuracy improvements beyond the validated set"],
        "#11250 shadow parity evidence accepted in review",
        &[],
        &["theme/classifier breadth extensions"],
        "revert restores the pre-cutover live path",
        &[
            authority("#11259", "cutover contract", AuthorityGroup::MustAlreadyBeCurrent),
            authority("#11250", "shadow parity evidence", AuthorityGroup::CandidateMayBeMined),
            authority(
                "semantic-token-projection",
                "canonical candidate modules",
                AuthorityGroup::OwnedByThisNode,
            ),
        ],
        &[op(
            "semantic_tokens_full",
            "LSP semantic tokens provider (live)",
            "current document parse at request time",
            "live classification delegates to canonical candidates",
            "candidates resolve per-request at the served document version",
            "candidate absence refuses the full-semantic layer instead of degrading silently",
            "explicit degradation is reported, never hidden as plain-text-only tokens",
            "empty arrays remain legitimate for token-free documents",
            "canonical candidate modules",
            "pre-cutover live heuristic path removed after cutover",
            "live cutover tests owned by this node",
        )],
        &["canonical candidate modules and live provider tests"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_live_heuristic_retirement",
            "old-path disposition record",
            "owned_by_this_node",
            ArtifactMode::Create,
            "heuristic live path active",
            "remove and record terminal disposition",
            XTEST_FOCUS.1,
            "old_path_retirement",
            "cutover without retirement is not convergence",
        )],
        (
            DurableSpecDisposition::IssuePlanSufficientForThisLeaf,
            "#11259 body",
            "cutover plan fits the issue body",
        ),
        (
            "serve full-semantic tokens and trace each token to a canonical candidate decision",
            "any token sourced from the old heuristic fails the provenance assertion",
            "live cutover test",
        ),
        "live responses equal shadow-validated expectations on the #11250 corpus",
        &[
            control("stale", "cutover judged against pre-shadow-candidate code"),
            control(
                "unexpected_duplicate_blocker",
                "second live classification path left compiled",
            ),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&["Was the parity evidence generated on this head's candidates?"]),
            LensSpec {
                name: "old_path_retirement",
                applicable: true,
                reason: "cutover must retire the replaced seam terminally",
                questions: &["Can the old live path still run after cutover?"],
            },
        ],
        &[2usize, 0],
        &[OldPathRow {
            seam: "pre-cutover live heuristic classification",
            terminal_disposition: "removed",
        }],
        &[],
    )
}

fn node_fr_8277() -> NodeSpec {
    node(
        "fr_8277_import_governed_operations_leaf",
        &[8277],
        8277,
        Domain::Imports,
        Role::ProductImplementation,
        Disposition::Actionable,
        Profile::CoreSemantic,
        "Implement one governed semantic import operation with distinct edit contexts under the #8277 programme controller.",
        &[
            "one governed operation lands with distinct prepare/apply contexts and evidence-backed rollout wiring",
        ],
        &["full governed-operation catalogue", "rollout analytics"],
        "#8305 containment held; controller plan current",
        &["fr_8336_import_claim_proof_row"],
        &["evidence-backed rollout completion"],
        "feature-flag revert restores single-context behavior",
        &[
            authority(
                "#8277",
                "imports programme controller",
                AuthorityGroup::MustAlreadyBeCurrent,
            ),
            authority(
                "#11074",
                "import packet IDs where imported rows exist",
                AuthorityGroup::MustBeConsumedNeverReimplemented,
            ),
            authority(
                "import-operation-registry",
                "governed operation registry",
                AuthorityGroup::OwnedByThisNode,
            ),
        ],
        &[op(
            "governed_import_operation",
            "import edit service with distinct contexts",
            "document plus import analysis at request time",
            "each operation declares its context kind and evidence requirement",
            "analysis runs at the served version before any edit is prepared",
            "missing evidence refuses the operation",
            "refusal carries the missing-evidence reason",
            "operations with nothing to do legitimately return no edits",
            "governed operation registry module",
            "ad-hoc import edit paths outside the registry",
            "focused registry tests owned by this node",
        )],
        &["governed operation registry module and focused tests"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_operation_context_matrix",
            "context matrix fixtures",
            "owned_by_this_node",
            ArtifactMode::Create,
            "contexts conflated in existing tests",
            "create per-context fixtures proving isolation",
            XTEST_FOCUS.1,
            "isolation_boundaries",
            "distinct contexts are the claim",
        )],
        (
            DurableSpecDisposition::IssuePlanSufficientForThisLeaf,
            "#8277 controller plan section",
            "controller already encodes the durable plan",
        ),
        (
            "apply two different operations in one context and show cross-contamination",
            "shared-context implementation lets edits leak across kinds, failing isolation fixtures",
            "registry isolation test",
        ),
        "each operation produces its declared context-scoped edit set",
        &[
            control("unsafe_edit", "prepare from one context applied in another"),
            control("mutation", "drop the context tag; isolation fixtures must fail"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&[
                "Is the import analysis from the same version as the prepared edit?",
            ]),
            LensSpec {
                name: "isolation_boundaries",
                applicable: true,
                reason: "distinct edit contexts are the proposition",
                questions: &["Can another root or instance share a prepared context?"],
            },
        ],
        &[4usize, 3],
        &[],
        &["stop at one operation; the catalogue belongs to successor leaves"],
    )
}

fn node_fr_8336() -> NodeSpec {
    node(
        "fr_8336_import_claim_proof_row",
        &[8336],
        8277,
        Domain::Imports,
        Role::ProofOnly,
        Disposition::Actionable,
        Profile::ProofOnly,
        "Prove the composed import claim (plan, wire, client, artifact, real-project) without repairing product behavior.",
        &["independent proof that the import claim holds end to end"],
        &["any product behavior change"],
        "at least one product child of #8277 landed",
        &[],
        &["installed-client distribution proof (separate installed plane)"],
        "proof artifacts are regenerated; product untouched",
        &[
            authority("#8336", "claim composition", AuthorityGroup::MustAlreadyBeCurrent),
            authority("#8277", "product children", AuthorityGroup::ConsumerFanInAfterPr),
        ],
        &[op(
            "import_claim_composition",
            "proof harness over landed product children",
            "landed product surfaces read-only",
            "proof asserts the composed claim across plan/wire/client/artifact rows",
            "proof runs against current heads of landed children",
            "a missing row marks that cell not-proven, never green",
            "not-proven cells are explicit in the receipt",
            "rows with nothing to prove are legitimately skipped",
            "proof harness module",
            "construction-only evidence reuse",
            "this node's proof suite",
        )],
        &["proof harness module and receipts"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_claim_proof_receipt",
            "proof receipt",
            "owned_by_this_node",
            ArtifactMode::Create,
            "no composed receipt exists",
            "create receipt enumerating each claim row and its outcome",
            XTEST_FOCUS.1,
            "stage_separation",
            "receipt identity is the deliverable",
        )],
        (
            DurableSpecDisposition::IssuePlanSufficientForThisLeaf,
            "#8336 body",
            "proof composition defined by the issue",
        ),
        (
            "delete one landed child's contribution from the receipt input and expect the receipt to go red, not skip",
            "a receipt that tolerates missing rows fails this falsifier",
            "composed receipt test",
        ),
        "every claim row green with independent identities",
        &[
            control(
                "wrong_subject",
                "receipt satisfied by construction logs instead of observed outputs",
            ),
            control("mutation", "mark a red row green; the audit must reject"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&["Does every receipt row bind to the head it proved?"]),
            stage_separation_lens(),
        ],
        &[8usize, 10],
        &[],
        &["stop before using this proof to justify further product repair"],
    )
}

fn node_fr_6997() -> NodeSpec {
    node(
        "fr_6997_critic_product_child",
        &[6997],
        6997,
        Domain::Critic,
        Role::ProductImplementation,
        Disposition::Actionable,
        Profile::CoreSemantic,
        "Converge one native critic product surface into the single current product owner with its compatibility-proof seam intact.",
        &["one critic surface served by the canonical product owner"],
        &["packaged-journey proof (that is #6992)", "critic scoring policy"],
        "#10724-style transition patterns available for reuse",
        &["fr_6992_installed_critic_journey_proof"],
        &["remaining critic surfaces listed in #6997"],
        "revert restores dual surfaces",
        &[
            authority("#6997", "convergence contract", AuthorityGroup::MustAlreadyBeCurrent),
            authority(
                "native-critic-core",
                "canonical critic engine",
                AuthorityGroup::OwnedByThisNode,
            ),
            authority("#6992", "installed journey proof", AuthorityGroup::ConsumerFanInAfterPr),
        ],
        &[op(
            "native_critique",
            "native critic engine CLI/LSP seam",
            "workspace sources at invocation time",
            "single engine owns critique emission",
            "engine reads current files per invocation",
            "engine absence refuses loudly, never fabricates findings",
            "explicit refusal with reason",
            "clean workspaces legitimately produce zero findings",
            "canonical critic engine",
            "secondary critic surface retired",
            "focused engine tests owned by this node",
        )],
        &["canonical critic engine and focused tests"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_critic_surface_parity",
            "parity fixtures",
            "owned_by_this_node",
            ArtifactMode::Create,
            "two surfaces diverge silently",
            "prove single-surface output stability",
            XTEST_FOCUS.1,
            "semantic_authority",
            "one-authority claim",
        )],
        (
            DurableSpecDisposition::IssuePlanSufficientForThisLeaf,
            "#6997 convergence plan",
            "issue plan sufficient for the leaf",
        ),
        (
            "invoke the retired secondary surface and require a hard failure",
            "if the old surface still answers, convergence is false and the test is red",
            "retirement test",
        ),
        "canonical engine answers every catalogued critique class identically across two runs",
        &[
            control("duplicate_authority", "second engine left answering"),
            control("mutation", "re-enable secondary surface; retirement test must fail"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&[
                "Are critiques computed from the current tree, not cached artifacts?",
            ]),
            LensSpec {
                name: "lifecycle_cleanup",
                applicable: true,
                reason: "dual-surface retirement leaves caches and temp state",
                questions: &["Can retired-surface state survive and satisfy later runs?"],
            },
        ],
        &[2usize, 7],
        &[OldPathRow { seam: "secondary critic surface", terminal_disposition: "removed" }],
        &["stop before packaging; the packaged journey belongs to #6992"],
    )
}

fn node_fr_6992() -> NodeSpec {
    node(
        "fr_6992_installed_critic_journey_proof",
        &[6992],
        6992,
        Domain::Critic,
        Role::InstalledClientProof,
        Disposition::Actionable,
        Profile::InstalledClient,
        "Prove the exact packaged native critic journey after runtime cutover using released artifacts only.",
        &["released package performs the documented critic journey on an exact host"],
        &["product behavior repair", "packaging pipeline changes"],
        "#6997 runtime cutover landed",
        &[],
        &["additional host platforms"],
        "re-run with prior released artifacts",
        &[
            authority("#6992", "journey contract", AuthorityGroup::MustAlreadyBeCurrent),
            authority("#6997", "runtime cutover", AuthorityGroup::MustAlreadyBeCurrent),
            authority(
                "release-identity-protocol",
                "install identity verification schema",
                AuthorityGroup::MustBeConsumedNeverReimplemented,
            ),
        ],
        &[op(
            "installed_critic_journey",
            "released perllsp artifact on an exact host",
            "exact released package identity",
            "journey steps execute against the installed artifact only",
            "artifact digests verified before launch",
            "missing artifact aborts the proof, never substitutes a dev build",
            "aborts carry the digest mismatch",
            "journeys with no findings legitimately end clean",
            "hermetic host-run harness",
            "dev-build substitution in proofs",
            "host-run proof suite owned by this node",
        )],
        &["host-run harness configuration and proof receipts"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_installed_journey_receipt",
            "proof receipt",
            "owned_by_this_node",
            ArtifactMode::Create,
            "no installed-journey receipt",
            "create receipt binding artifact digests to journey outcomes",
            XTEST_FOCUS.1,
            "stage_separation",
            "installed-stage claim identity",
        )],
        (
            DurableSpecDisposition::IssuePlanSufficientForThisLeaf,
            "#6992 body",
            "journey steps enumerated by the issue",
        ),
        (
            "swap the released artifact for a dev build and require the harness to abort",
            "digest verification must reject the substitution, else the proof is not installed-stage",
            "harness identity test",
        ),
        "released artifact completes the documented journey with verified identity",
        &[
            control(
                "near_miss_artifact_stage",
                "candidate artifact satisfying the installed oracle",
            ),
            control("stale", "receipt from an earlier release identity"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&["Does the receipt pin the exact released artifact digest?"]),
            stage_separation_lens(),
        ],
        &[9usize, 8],
        &[],
        &["stop before claiming product repair from this proof"],
    )
}

fn node_fr_9349() -> NodeSpec {
    node(
        "fr_9349_formatter_product_child",
        &[9349],
        9349,
        Domain::Formatting,
        Role::ProductImplementation,
        Disposition::Actionable,
        Profile::CoreSemantic,
        "Execute one native formatter product train step toward the single native formatting owner.",
        &["one formatter behavior converges onto the native owner"],
        &["whole-formatter parity", "external perl-tidy bundling"],
        "external perl-tidy availability is optional and never changes the native default",
        &["fr_10724_formatting_currentness_proof"],
        &["remaining #9349 train steps"],
        "revert restores prior formatter step state",
        &[
            authority("#9349", "formatter train controller", AuthorityGroup::MustAlreadyBeCurrent),
            authority(
                "native-formatter",
                "canonical native formatter module",
                AuthorityGroup::OwnedByThisNode,
            ),
            authority("perl-tidy", "optional external engine", AuthorityGroup::ExternalManualOwner),
        ],
        &[op(
            "format_document",
            "native formatter provider",
            "current document text at request time",
            "formatting follows the native owner's canonical rules for this step",
            "formatting applies to the served document version",
            "when the native engine cannot format, it refuses; external engines never mask refusals",
            "explicit refusal with reason",
            "already-canonical documents legitimately produce no edits",
            "native formatter module",
            "per-formatting delegation shortcuts outside the owner",
            "transition tests following #10724's clean-to-broken-to-clean pattern",
        )],
        &["native formatter module and transition tests"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_formatter_transition_fixtures",
            "transition fixtures",
            "owned_by_this_node",
            ArtifactMode::Create,
            "fixtures assume external tidy presence",
            "create native-default fixtures valid without external tools",
            XTEST_FOCUS.1,
            "fallback_refusal_legitimate_empty_truth",
            "native default independence",
        )],
        (
            DurableSpecDisposition::IssuePlanSufficientForThisLeaf,
            "#9349 train step description",
            "step scoped by the controller issue",
        ),
        (
            "run formatting with perl-tidy removed from PATH and compare against the native default",
            "implementations depending on external presence diverge and fail",
            "environment-independence test",
        ),
        "identical formatting with and without external engines present",
        &[
            control("near_miss_platform", "PATH-dependent behavior"),
            control(
                "mutation",
                "delegate to perl-tidy when present; the independence test must fail",
            ),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&[
                "Is formatting computed for the served version, not the last save?",
            ]),
            LensSpec {
                name: "security_trust_boundary",
                applicable: true,
                reason: "external engine invocation crosses a trust boundary",
                questions: &["Can external-engine presence change the trusted native default?"],
            },
        ],
        &[7usize, 1],
        &[],
        &["stop before claiming whole-formatter parity"],
    )
}

fn node_fr_10724() -> NodeSpec {
    node(
        "fr_10724_formatting_currentness_proof",
        &[10724],
        10724,
        Domain::Formatting,
        Role::ProofOnly,
        Disposition::Actionable,
        Profile::ProofOnly,
        "Prove formatting currentness and refusal through clean-to-broken-to-clean transitions without touching product code.",
        &["independent transition evidence that formatting is current and refuses honestly"],
        &["formatter behavior changes"],
        "formatter product child under proof is landed",
        &[],
        &["editor-level UX metrics"],
        "proof reruns are idempotent",
        &[
            authority("#10724", "transition proof contract", AuthorityGroup::MustAlreadyBeCurrent),
            authority("#9349", "formatter product surface", AuthorityGroup::ConsumerFanInAfterPr),
        ],
        &[op(
            "formatting_transition_proof",
            "proof harness driving the landed formatter",
            "landed formatter surface read-only",
            "transitions prove idempotence and honest refusal",
            "transitions run at fixed document versions",
            "broken documents must produce refusal-or-repair evidence, never silence",
            "refusal evidence recorded per transition",
            "clean-to-clean no-op transitions are legitimate outcomes",
            "transition proof harness",
            "manual eyeballing notes",
            "this node's harness suite",
        )],
        &["transition proof harness and receipts"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_transition_evidence",
            "evidence receipt",
            "owned_by_this_node",
            ArtifactMode::Create,
            "none",
            "record each transition leg with expected/actual",
            XTEST_FOCUS.1,
            "artifact_completeness",
            "receipt completeness is the proof",
        )],
        (
            DurableSpecDisposition::IssuePlanSufficientForThisLeaf,
            "#10724 body",
            "protocol defined by the issue",
        ),
        (
            "corrupt the broken-leg input so no refusal can fire and require the receipt to mark not-proven",
            "silence-tolerant receipts fail this falsifier",
            "harness negative control",
        ),
        "all transition legs produce expected evidence",
        &[
            control("false_empty", "broken leg reported as clean success"),
            control("mutation", "skip a leg; completeness audit must reject"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&["Does each leg pin its document version and head?"]),
            stage_separation_lens(),
        ],
        &[1usize, 10],
        &[],
        &["stop before treating this proof as product repair authorization"],
    )
}

fn node_fr_11271() -> NodeSpec {
    node(
        "fr_11271_zydeco_research",
        &[11271],
        11271,
        Domain::ParserResearch,
        Role::ResearchDecision,
        Disposition::Actionable,
        Profile::Research,
        "Determine a truthful parser, fact, highlighting, and support disposition for zydeco and record it for downstream routing.",
        &["a sourced disposition ruling with evidence references"],
        &["any parser/product change", "support registry edits"],
        "none; research is self-contained",
        &["downstream domain trains consume the ruling"],
        &["zydeco upstream evolution after the study window"],
        "discard the research note",
        &[
            authority("#11271", "research mandate", AuthorityGroup::MustAlreadyBeCurrent),
            authority(
                "zydeco-upstream",
                "upstream project sources",
                AuthorityGroup::ExternalManualOwner,
            ),
            authority(
                "support-registry",
                "support claims owner",
                AuthorityGroup::ExplicitlyNotOwned,
            ),
        ],
        &[op(
            "zydeco_support_disposition",
            "research note only",
            "upstream documentation and experiments",
            "disposition states what zydeco support would mean per plane",
            "study pins upstream revision studied",
            "unknowns remain unknown with reasons",
            "not-applicable planes say so",
            "empty findings for a plane are legitimate",
            "research note filed to #11271",
            "no old path",
            "reviewer challenge of sourcing",
        )],
        &["research note content filed back to #11271"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_zydeco_research_note",
            "research note",
            "owned_by_this_node",
            ArtifactMode::Create,
            "no note",
            "file sourced disposition per plane",
            "manual review against pinned upstream revision",
            "public_api_claim_consistency",
            "ruling feeds downstream routing only",
        )],
        (
            DurableSpecDisposition::ReturnToIssueForUnsettledDecision,
            "#11271 discussion",
            "unsettled semantic decisions return to the owning issue",
        ),
        (
            "attempt to cite any product code change in the research packet",
            "packet validation must reject product-implementation steps entirely",
            "role validation",
        ),
        "every plane carries either a sourced disposition or an explicit unknown",
        &[
            control("wrong_subject", "folklore cited without pinned upstream revision"),
            control("mutation", "inject an implementation step; generation must fail"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&["Is the upstream revision pinned so claims stay auditable?"]),
            stage_separation_lens(),
        ],
        &[8usize, 0],
        &[],
        &["stop before translating the ruling into product work; routing belongs to controllers"],
    )
}

fn node_fr_11261() -> NodeSpec {
    node(
        "fr_11261_object_facts_source_anchors",
        &[11261],
        CONTROLLER_FR,
        Domain::SemanticTokens,
        Role::ProductImplementation,
        Disposition::Actionable,
        Profile::OptionalFramework,
        "Project canonical object facts through source anchors within the core semantic-token scope.",
        &["object facts render via source anchors in core scope"],
        &["framework-specific entity projection (that is #11263)"],
        "#11259 live cutover landed so candidates are authoritative",
        &["fr_11263_application_framework_projection"],
        &["framework entity breadth"],
        "revert removes anchor projection",
        &[
            authority("#11261", "projection contract", AuthorityGroup::MustAlreadyBeCurrent),
            authority(
                "fact-projection",
                "canonical object fact projection",
                AuthorityGroup::OwnedByThisNode,
            ),
        ],
        &[op(
            "object_token_projection",
            "semantic token projection",
            "compiler object facts at anchors",
            "anchors map object facts to token spans",
            "facts resolved per request version",
            "anchor-less facts drop with a recorded reason, never misproject",
            "dropped-anchor reasons are queryable",
            "documents without objects project empty",
            "fact projection module",
            "title-inferred projection guesses",
            "focused projection tests",
        )],
        &["fact projection module and focused tests"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_anchor_projection_fixtures",
            "projection fixtures",
            "owned_by_this_node",
            ArtifactMode::Create,
            "none for anchors",
            "create anchor fixtures excluding framework entities",
            XTEST_FOCUS.1,
            "artifact_completeness",
            "scope ceiling visible in fixtures",
        )],
        (
            DurableSpecDisposition::IssuePlanSufficientForThisLeaf,
            "#11261 body",
            "bounded projection plan in the issue",
        ),
        (
            "present a framework-only entity and require it NOT to appear in core-scope output",
            "scope-leaking implementations emit it and fail the exclusion assertion",
            "scope exclusion test",
        ),
        "core objects project; framework-only entities stay excluded",
        &[
            control("near_miss_framework", "framework DSL scanning sneaking into core scope"),
            control("mutation", "enable DSL scan; exclusion test must fail"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&["Do anchors resolve against the served version's facts?"]),
            LensSpec {
                name: "isolation_boundaries",
                applicable: true,
                reason: "optional framework breadth must not leak into narrower packets",
                questions: &["Can framework breadth satisfy a core-scope oracle?"],
            },
        ],
        &[6usize, 3],
        &[],
        &["stop before widening into framework entities; that is #11263"],
    )
}

fn node_fr_11263() -> NodeSpec {
    node(
        "fr_11263_application_framework_projection",
        &[11263],
        CONTROLLER_FR,
        Domain::SemanticTokens,
        Role::ProductImplementation,
        Disposition::Actionable,
        Profile::OptionalFramework,
        "Project canonical application-framework source entities without DSL scanning, as an opt-in breadth layer.",
        &["framework entities project from canonical sources with the layer explicitly opt-in"],
        &["making framework breadth a default or core dependency"],
        "fr_11261 core anchor projection landed",
        &[],
        &["additional frameworks"],
        "disable the opt-in layer",
        &[
            authority("#11263", "breadth contract", AuthorityGroup::MustAlreadyBeCurrent),
            authority("#11261", "core anchor projection", AuthorityGroup::MustAlreadyBeCurrent),
        ],
        &[op(
            "framework_entity_projection",
            "opt-in semantic token breadth layer",
            "declared framework configuration plus canonical entities",
            "entities come from canonical declarations, never DSL heuristics",
            "declarations read at served version",
            "undeclared frameworks simply yield no breadth tokens",
            "absence of configuration is a legitimate empty",
            "projects without frameworks legitimately project nothing extra",
            "breadth layer module",
            "DSL-scanning prototypes",
            "breadth layer tests",
        )],
        &["breadth layer module and tests"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_breadth_opt_in_matrix",
            "opt-in matrix fixtures",
            "owned_by_this_node",
            ArtifactMode::Create,
            "none",
            "prove off-by-default and no-DSL-scan properties",
            XTEST_FOCUS.1,
            "fallback_refusal_legitimate_empty_truth",
            "opt-in honesty",
        )],
        (
            DurableSpecDisposition::IssuePlanSufficientForThisLeaf,
            "#11263 body",
            "breadth bounded by the issue",
        ),
        (
            "scan for DSL files in a project with the layer enabled but no declaration",
            "scanner-based implementations emit tokens; canonical-source implementations emit none",
            "no-scan test",
        ),
        "declared frameworks project; undeclared ones contribute nothing",
        &[
            control(
                "fixture_as_semantic_support",
                "a grammar fixture satisfying framework support claims",
            ),
            control("mutation", "add a scanner fallback; the no-scan test must fail"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&["Are declarations read fresh per projection request?"]),
            LensSpec {
                name: "public_api_claim_consistency",
                applicable: true,
                reason: "opt-in breadth must match advertised capability",
                questions: &["Does advertisement distinguish opt-in breadth from core support?"],
            },
        ],
        &[6usize, 9],
        &[OldPathRow { seam: "DSL-scanning prototype branches", terminal_disposition: "removed" }],
        &["stop before promoting breadth into defaults"],
    )
}

fn node_fr_11267() -> NodeSpec {
    node(
        "fr_11267_installed_vscode_proof",
        &[11267],
        7718,
        Domain::VscodeClient,
        Role::InstalledClientProof,
        Disposition::Actionable,
        Profile::InstalledClient,
        "Prove the installed TextMate baseline and semantic-token augmentation from exact released VS Code artifacts.",
        &["released extension renders baseline TextMate plus augmentation on an exact editor host"],
        &["extension behavior changes", "grammar authoring"],
        "vscode-extension release pipeline produces exact artifacts",
        &[],
        &["other editors' installed proofs"],
        "re-run against a prior released artifact set",
        &[
            authority("#11267", "installed proof contract", AuthorityGroup::MustAlreadyBeCurrent),
            authority("#7718", "VS Code product convergence", AuthorityGroup::MustAlreadyBeCurrent),
            authority(
                "vscode-marketplace-artifact",
                "released VSIX identity",
                AuthorityGroup::ExternalManualOwner,
            ),
        ],
        &[op(
            "installed_vscode_rendering",
            "released VS Code extension on an exact host",
            "exact VSIX plus editor version",
            "baseline grammar then augmentation layers verified separately",
            "artifact digests verified before launch",
            "missing layers abort with the layer name",
            "abort reasons name the missing layer",
            "documents triggering no augmentation legitimately show baseline only",
            "hermetic editor host harness",
            "dev-extension substitution",
            "host proof suite owned by this node",
        )],
        &["editor host harness config and receipts"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_vscode_layer_receipt",
            "layered proof receipt",
            "owned_by_this_node",
            ArtifactMode::Create,
            "none",
            "bind VSIX digest to per-layer rendering outcomes",
            XTEST_FOCUS.1,
            "stage_separation",
            "installed-stage separation",
        )],
        (
            DurableSpecDisposition::IssuePlanSufficientForThisLeaf,
            "#11267 body",
            "layers enumerated by the issue",
        ),
        (
            "replace the VSIX with the dev build and require harness abort",
            "identity verification rejects the substitution",
            "harness identity test",
        ),
        "both layers verified against exact released artifacts",
        &[
            control("near_miss_client", "another editor satisfying the oracle"),
            control("stale", "receipt bound to a superseded VSIX"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&["Is the editor version pinned in the receipt?"]),
            stage_separation_lens(),
        ],
        &[3usize, 9],
        &[],
        &["stop before using this proof to change extension behavior"],
    )
}

fn node_fr_8301() -> NodeSpec {
    node(
        "fr_8301_deferred_npm_distribution",
        &[8301],
        CONTROLLER_FR,
        Domain::Distribution,
        Role::GovernanceSupport,
        Disposition::Deferred,
        Profile::Deferred,
        "Record the deferred npm perllsp binary channel decision for v0.18 and forbid premature distribution work.",
        &["the deferral ruling is preserved with its conditions for revisiting"],
        &["any npm channel implementation"],
        "decision issue #8301 is closed with the ruling recorded",
        &[],
        &["revisit triggers named in the ruling"],
        "nothing to roll back; records only",
        &[
            authority("#8301", "deferral ruling", AuthorityGroup::MustAlreadyBeCurrent),
            authority(
                "npm-channel",
                "future distribution owner",
                AuthorityGroup::ExplicitlyNotOwned,
            ),
        ],
        &[op(
            "distribution_deferral_record",
            "governance record only",
            "closed decision issue text",
            "deferral conditions and revisit triggers are transcribed faithfully",
            "record cites the closed decision at its final state",
            "no execution fallback exists by design",
            "any attempt to execute is refused by role",
            "not applicable",
            "the ruling text itself",
            "none",
            "validation forbidding implementation steps",
        )],
        &["packet and ruling references only; no repository writes"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_deferral_reference",
            "ruling reference row",
            "owned_by_this_node",
            ArtifactMode::Consume,
            "ruling exists in #8301",
            "consume and cite; change nothing",
            "grep the ruling ID in packet output",
            "stage_separation",
            "prevents orphan rulings",
        )],
        (
            DurableSpecDisposition::ExistingNormativeContractSufficient,
            "#8301 ruling text",
            "the closed decision is the durable contract",
        ),
        (
            "generate this packet with an implementation step present",
            "generation must fail: deferred governance nodes cannot emit coding work",
            "role validation",
        ),
        "packet renders with disposition deferred and no execution sequence",
        &[
            control("wrong_subject", "deferred ruling rendered as actionable work"),
            control(
                "mutation",
                "flip disposition to actionable; validation must reject the missing execution contract",
            ),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&["Does the packet cite the ruling's closing state, not drafts?"]),
            stage_separation_lens(),
        ],
        &[8usize],
        &[],
        &["stop before any npm-channel work; revisit triggers own reopening"],
    )
}

fn node_fr_7122() -> NodeSpec {
    node(
        "fr_7122_support_registry_governance_row",
        &[7122],
        7122,
        Domain::SupportRegistry,
        Role::GovernanceSupport,
        Disposition::Actionable,
        Profile::Governance,
        "Maintain the machine-readable client support registry and regenerate derived setup claims through the owned generator.",
        &["registry rows and generated claims stay consistent through the owned check command"],
        &["product capability changes", "editor implementations"],
        "capability manifests feeding the registry are current",
        &[],
        &["new client rows"],
        "restore prior registry generation inputs",
        &[
            authority("#7122", "registry contract", AuthorityGroup::MustAlreadyBeCurrent),
            authority(
                "support-registry-schema",
                "machine-readable registry schema",
                AuthorityGroup::OwnedByThisNode,
            ),
            authority(
                "generated-setup-docs",
                "derived documentation",
                AuthorityGroup::OwnedByThisNode,
            ),
        ],
        &[op(
            "support_claim_generation",
            "registry generator",
            "registry rows plus capability manifests",
            "claims derive only from registry rows",
            "generator reads current manifests at run time",
            "row/manifest mismatch fails generation",
            "failures name the drifted row",
            "clients with no claims legitimately generate nothing",
            "registry generator and its check command",
            "hand-edited setup docs",
            "generator determinism checks",
        )],
        &["registry data files and generated outputs"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_generated_setup_claims",
            "generated documentation",
            "owned_by_this_node",
            ArtifactMode::Update,
            "generated from current rows",
            "regenerate and prove determinism",
            "cargo xtask check-naming-consistency || cargo test -p xtask --all-targets --locked support_registry",
            "artifact_completeness",
            "generated-truth discipline",
        )],
        (
            DurableSpecDisposition::ExistingNormativeContractSufficient,
            "#7122 registry schema",
            "schema already normative",
        ),
        (
            "hand-edit a generated setup doc without regenerating",
            "check command must detect drift and fail",
            "drift check",
        ),
        "two consecutive generations are byte-identical",
        &[
            control("unexpected_duplicate_blocker", "second hand-maintained claim doc"),
            control("mutation", "perturb a row; regeneration must change outputs"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&["Did generation consume the current manifest set?"]),
            LensSpec {
                name: "artifact_completeness",
                applicable: true,
                reason: "governance rows fail through missing generated artifacts",
                questions: &["Can a required generated doc be missing while checks pass?"],
            },
        ],
        &[10usize],
        &[OldPathRow {
            seam: "hand-edited setup documentation",
            terminal_disposition: "historical_generated_presentation_only",
        }],
        &["stop before editing capability manifests; they belong to product owners"],
    )
}

fn node_fr_9415() -> NodeSpec {
    node(
        "fr_9415_dap_reliability_leaf",
        &[9415],
        9415,
        Domain::Dap,
        Role::ProductImplementation,
        Disposition::Actionable,
        Profile::CoreSemantic,
        "Execute one reliability/convergence step of the native perl-dap train under the #9415 controller and #7278 cut-line ruling.",
        &["one DAP reliability behavior converges onto the native adapter owner"],
        &["release cut-line movement", "editor DAP client changes"],
        "#7278 ruling constraints apply to scope",
        &["fr_7278_dap_release_ruling"],
        &["remaining #9415 train steps"],
        "revert restores prior adapter step state",
        &[
            authority("#9415", "DAP train controller", AuthorityGroup::MustAlreadyBeCurrent),
            authority("#7278", "cut-line ruling", AuthorityGroup::MustAlreadyBeCurrent),
            authority(
                "perl-dap-adapter",
                "native DAP adapter crate",
                AuthorityGroup::OwnedByThisNode,
            ),
        ],
        &[op(
            "dap_session_step",
            "native DAP adapter",
            "debug session state at event time",
            "adapter behavior follows the trained step's contract",
            "session events processed in order at current state",
            "adapter failures terminate sessions explicitly, never hang",
            "termination carries the reason",
            "sessions ending cleanly are legitimate",
            "perl-dap adapter crate",
            "workaround paths in clients",
            "adapter-focused tests",
        )],
        &["perl-dap crate focused tests"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_dap_session_fixtures",
            "session fixtures",
            "owned_by_this_node",
            ArtifactMode::Create,
            "step behaviors untested",
            "cover the trained step's session lifecycle",
            "cargo test -p perl-dap --all-targets --locked",
            "artifact_completeness",
            "step-level falsifiability",
        )],
        (
            DurableSpecDisposition::IssuePlanSufficientForThisLeaf,
            "#9415 train step row",
            "step scoped by controller",
        ),
        (
            "deliver a malformed event mid-session and require deterministic termination",
            "hanging or silent-drop implementations fail",
            "adapter robustness test",
        ),
        "session lifecycle completes deterministically for the trained step",
        &[
            control("false_empty", "one lost event hiding others' effects"),
            control("mutation", "drop termination; robustness test must fail"),
        ],
        &[
            ("dap_focused", "cargo test -p perl-dap --all-targets --locked", "focused_proof"),
            XTEST_FOCUS,
        ],
        &[
            currentness_lens(&["Are events ordered against current session state?"]),
            LensSpec {
                name: "lifecycle_cleanup",
                applicable: true,
                reason: "debug sessions leak processes and ports when cleanup is partial",
                questions: &["Can a terminated session leave a listening socket behind?"],
            },
        ],
        &[5usize],
        &[],
        &["stop before release actions; the cut line is #7278"],
    )
}

fn node_fr_7278() -> NodeSpec {
    node(
        "fr_7278_dap_release_ruling",
        &[7278],
        CONTROLLER_FR,
        Domain::Dap,
        Role::GovernanceSupport,
        Disposition::BlockedExternalManual,
        Profile::Governance,
        "Hold the native debugger cut-line ruling as an external/manual governance boundary that cannot emit product coding work.",
        &["cut-line criteria remain explicit and externally owned"],
        &["any release execution", "adapter behavior changes"],
        "ruling issue remains open with external owners",
        &[],
        &["criteria satisfaction evidence from product lanes"],
        "nothing to roll back; boundary declaration only",
        &[
            authority("#7278", "cut-line ruling", AuthorityGroup::ExternalManualOwner),
            authority("#9415", "DAP train", AuthorityGroup::ConsumerFanInAfterPr),
            authority(
                "microsoft-implementor-listing",
                "external listing process",
                AuthorityGroup::ExternalManualOwner,
            ),
        ],
        &[op(
            "cut_line_boundary",
            "governance boundary record",
            "open ruling issue text",
            "criteria and owners transcribed faithfully",
            "cites the ruling's current open state",
            "no execution route exists by design",
            "execution attempts are refused by role",
            "not applicable",
            "the ruling text",
            "none",
            "validation forbidding implementation steps",
        )],
        &["packet references only; repository untouched"],
        FORBIDDEN_SHARED,
        &[artifact(
            "art_cut_line_reference",
            "boundary reference row",
            "owned_by_this_node",
            ArtifactMode::Consume,
            "ruling open",
            "cite criteria and owners",
            "grep the ruling ID in packet output",
            "stage_separation",
            "keeps external ownership visible",
        )],
        (
            DurableSpecDisposition::ReturnToIssueForUnsettledDecision,
            "#7278 ruling",
            "unsettled externally; returns to the ruling issue",
        ),
        (
            "generate this packet with a merge or release action permitted",
            "stop-section validation must reject external action permissions",
            "stop validation",
        ),
        "packet renders blocked-external with forbidden release actions",
        &[
            control("wrong_subject", "external ruling rendered as internal work"),
            control("mutation", "permit release action; stop validation must fail"),
        ],
        &[XTEST_FOCUS],
        &[
            currentness_lens(&["Does the packet preserve the ruling's open-state citation?"]),
            stage_separation_lens(),
        ],
        &[8usize, 3],
        &[],
        &["stop before any release/publication action; owners are external"],
    )
}

/// Canonical registry order (sorted by node id at use sites; this vector's
/// order never affects emitted bytes).
pub fn all_nodes() -> Vec<NodeSpec> {
    vec![
        node_fr_1850(),
        node_fr_5108(),
        node_fr_6992(),
        node_fr_6997(),
        node_fr_7122(),
        node_fr_7278(),
        node_fr_8277(),
        node_fr_8301(),
        node_fr_8305(),
        node_fr_8336(),
        node_fr_8944(),
        node_fr_9349(),
        node_fr_9415(),
        node_fr_10724(),
        node_fr_11250_shadow(),
        node_fr_11259(),
        node_fr_11261(),
        node_fr_11263(),
        node_fr_11267(),
        node_fr_11271(),
    ]
}

/// The packet denominator is derived from the controlling issue contracts,
/// not from `all_nodes()`. Actionable rows are the 18 admitted packet leaves;
/// #8301 remains represented as deferred governance, while the blocked DAP
/// ruling, controller, and observational-plane rows are explicitly excluded
/// from this bounded actionable surface. Duplicate issue/node identities are
/// rejected by the validator.
pub fn denominator() -> &'static [DenominatorEntry] {
    const ENTRIES: &[DenominatorEntry] = &[
        DenominatorEntry {
            issue: 1850,
            packet_node: Some("fr_1850_semantic_token_geometry"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated product leaf",
        },
        DenominatorEntry {
            issue: 5108,
            packet_node: Some("fr_5108_navigation_truth_repair"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated product leaf",
        },
        DenominatorEntry {
            issue: 6992,
            packet_node: Some("fr_6992_installed_critic_journey_proof"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated installed proof row",
        },
        DenominatorEntry {
            issue: 6997,
            packet_node: Some("fr_6997_critic_product_child"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated product child",
        },
        DenominatorEntry {
            issue: 7122,
            packet_node: Some("fr_7122_support_registry_governance_row"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated governance mapping",
        },
        DenominatorEntry {
            issue: 7278,
            packet_node: Some("fr_7278_dap_release_ruling"),
            disposition: DenominatorDisposition::Excluded,
            reason: "external/manual ruling boundary cannot emit actionable coding work",
        },
        DenominatorEntry {
            issue: 8277,
            packet_node: Some("fr_8277_import_governed_operations_leaf"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated controller-child implementation row",
        },
        DenominatorEntry {
            issue: 8301,
            packet_node: Some("fr_8301_deferred_npm_distribution"),
            disposition: DenominatorDisposition::Deferred,
            reason: "release-topology decision remains deferred",
        },
        DenominatorEntry {
            issue: 8305,
            packet_node: Some("fr_8305_import_containment_leaf"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated containment leaf",
        },
        DenominatorEntry {
            issue: 8336,
            packet_node: Some("fr_8336_import_claim_proof_row"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated proof-only row",
        },
        DenominatorEntry {
            issue: 8944,
            packet_node: Some("fr_8944_signature_semantic_cutover"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated product leaf",
        },
        DenominatorEntry {
            issue: 9349,
            packet_node: Some("fr_9349_formatter_product_child"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated product child",
        },
        DenominatorEntry {
            issue: 9415,
            packet_node: Some("fr_9415_dap_reliability_leaf"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated product leaf",
        },
        DenominatorEntry {
            issue: 10724,
            packet_node: Some("fr_10724_formatting_currentness_proof"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated exact-process proof row",
        },
        DenominatorEntry {
            issue: 11250,
            packet_node: Some("fr_11250_semantic_token_shadow"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated shadow row",
        },
        DenominatorEntry {
            issue: 11259,
            packet_node: Some("fr_11259_semantic_token_live_cutover"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated live cutover row",
        },
        DenominatorEntry {
            issue: 11261,
            packet_node: Some("fr_11261_object_facts_source_anchors"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated optional framework row",
        },
        DenominatorEntry {
            issue: 11263,
            packet_node: Some("fr_11263_application_framework_projection"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated optional framework row",
        },
        DenominatorEntry {
            issue: 11267,
            packet_node: Some("fr_11267_installed_vscode_proof"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated installed proof row",
        },
        DenominatorEntry {
            issue: 11271,
            packet_node: Some("fr_11271_zydeco_research"),
            disposition: DenominatorDisposition::Actionable,
            reason: "mandated research/decision row",
        },
        DenominatorEntry {
            issue: 10122,
            packet_node: None,
            disposition: DenominatorDisposition::Excluded,
            reason: "routing controller, not a packet work item",
        },
        DenominatorEntry {
            issue: 11280,
            packet_node: None,
            disposition: DenominatorDisposition::Excluded,
            reason: "current-tree observational plane owned by its successor",
        },
        DenominatorEntry {
            issue: 11281,
            packet_node: None,
            disposition: DenominatorDisposition::Excluded,
            reason: "offline-readiness observational plane owned by its successor",
        },
    ];
    ENTRIES
}
