//! Accepted quote-like lexical matrix rows for current-main observation.

use super::schema::{
    Axis, DelimiterFamily, Disposition, ExpectedKind, MatrixRow, NextOrdinary, OperatorFamily,
    OracleExpectation, PERL_PROFILE, SCHEMA_VERSION, SourceContext, Spelling, TerminalStateClass,
    TokenSpec, spec,
};

pub fn all_rows() -> Vec<MatrixRow> {
    let mut rows = Vec::new();
    rows.extend_from_slice(&POSITIVE_GEOMETRY);
    rows.extend_from_slice(&DELIMITER_FAMILIES);
    rows.extend_from_slice(&COMMENT_AND_HASH);
    rows.extend_from_slice(&TWO_BODY);
    rows.extend(context_rows());
    rows.extend(malformed_rows());
    rows.extend_from_slice(&NEWLINE_UNICODE_MODIFIER);
    rows
}

#[expect(
    clippy::too_many_arguments,
    reason = "test helper packs one matrix-row contract without a second builder type"
)]
const fn row(
    id: &'static str,
    operator: OperatorFamily,
    spelling: Spelling,
    delimiter: DelimiterFamily,
    source_context: SourceContext,
    source: &'static str,
    expected: &'static [TokenSpec],
    next_ordinary: NextOrdinary,
    terminal: TerminalStateClass,
    disposition: Disposition,
    oracle: OracleExpectation,
    limitation: Option<&'static str>,
    axes: &'static [Axis],
) -> MatrixRow {
    MatrixRow {
        id,
        schema_version: SCHEMA_VERSION,
        perl_profile: PERL_PROFILE,
        operator,
        spelling,
        delimiter,
        source_context,
        source,
        expected,
        next_ordinary,
        terminal,
        disposition,
        oracle,
        limitation,
        axes,
    }
}

const AFTER: NextOrdinary = NextOrdinary::Present { kind: ExpectedKind::Identifier, text: "after" };

const POSITIVE_GEOMETRY: [MatrixRow; 18] = [
    row(
        "q.attached.brace.literal",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "q{literal}; after",
        &[
            spec(ExpectedKind::QuoteSingle, "q{literal}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired],
    ),
    row(
        "q.attached.pipe.escaped",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::UnpairedPipe,
        SourceContext::Term,
        "q|literal\\|tail|; after",
        &[
            spec(ExpectedKind::QuoteSingle, "q|literal\\|tail|"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedUnpaired, Axis::EscapedDelimiter],
    ),
    row(
        "qq.attached.bracket.interpolated",
        OperatorFamily::Qq,
        Spelling::Attached,
        DelimiterFamily::PairedBracket,
        SourceContext::Term,
        "qq[hello $name]; after",
        &[
            spec(ExpectedKind::QuoteDouble, "qq[hello $name]"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired],
    ),
    row(
        "qw.attached.paren.words",
        OperatorFamily::Qw,
        Spelling::Attached,
        DelimiterFamily::PairedParen,
        SourceContext::Term,
        "qw(foo bar); after",
        &[
            spec(ExpectedKind::QuoteWords, "qw(foo bar)"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired],
    ),
    row(
        "qx.attached.angle.command",
        OperatorFamily::Qx,
        Spelling::Attached,
        DelimiterFamily::PairedAngle,
        SourceContext::Term,
        "qx<echo hi>; after",
        &[
            spec(ExpectedKind::QuoteCommand, "qx<echo hi>"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired],
    ),
    row(
        "qr.attached.slash.modifiers",
        OperatorFamily::Qr,
        Spelling::Attached,
        DelimiterFamily::UnpairedSlash,
        SourceContext::Term,
        "qr/pat+/imsx; after",
        &[
            spec(ExpectedKind::QuoteRegex, "qr/pat+/imsx"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedUnpaired, Axis::Modifier],
    ),
    row(
        "m.attached.pipe.pattern",
        OperatorFamily::M,
        Spelling::Attached,
        DelimiterFamily::UnpairedPipe,
        SourceContext::Term,
        "m|pat|; after",
        &[
            spec(ExpectedKind::RegexMatch, "m|pat|"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedUnpaired],
    ),
    row(
        "s.attached.slash.replacement",
        OperatorFamily::S,
        Spelling::Attached,
        DelimiterFamily::UnpairedSlash,
        SourceContext::Term,
        "s/a/b/g; after",
        &[
            spec(ExpectedKind::Substitution, "s/a/b/g"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedUnpaired, Axis::Modifier],
    ),
    row(
        "s.attached.squote.replacement",
        OperatorFamily::S,
        Spelling::Attached,
        DelimiterFamily::UnpairedOther,
        SourceContext::Term,
        "s'foo'bar'; after",
        &[
            spec(ExpectedKind::Substitution, "s'foo'bar'"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedUnpaired],
    ),
    row(
        "s.attached.bracket.same_paired",
        OperatorFamily::S,
        Spelling::Attached,
        DelimiterFamily::PairedBracket,
        SourceContext::Term,
        "s[old][new]; after",
        &[
            spec(ExpectedKind::Substitution, "s[old][new]"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired],
    ),
    row(
        "tr.attached.slash.modifiers",
        OperatorFamily::Tr,
        Spelling::Attached,
        DelimiterFamily::UnpairedSlash,
        SourceContext::Term,
        "tr/a-z/A-Z/cd; after",
        &[
            spec(ExpectedKind::Transliteration, "tr/a-z/A-Z/cd"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedUnpaired, Axis::Modifier],
    ),
    row(
        "tr.attached.brace.same_paired",
        OperatorFamily::Tr,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "tr{a-z}{A-Z}; after",
        &[
            spec(ExpectedKind::Transliteration, "tr{a-z}{A-Z}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired],
    ),
    row(
        "y.attached.angle.same_paired",
        OperatorFamily::Y,
        Spelling::Attached,
        DelimiterFamily::PairedAngle,
        SourceContext::Term,
        "y<a-z><A-Z>; after",
        &[
            spec(ExpectedKind::Transliteration, "y<a-z><A-Z>"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired],
    ),
    row(
        "s.attached.brace.nested",
        OperatorFamily::S,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "s{a{b}}{c{d}}g; after",
        &[
            spec(ExpectedKind::Substitution, "s{a{b}}{c{d}}g"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired, Axis::NestedPaired, Axis::Modifier],
    ),
    row(
        "q.whitespace.brace",
        OperatorFamily::Q,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "q {spaced}; after",
        &[
            spec(ExpectedKind::QuoteSingle, "q {spaced}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::WhitespaceSeparated, Axis::AttachedPaired],
    ),
    row(
        "m.whitespace.slash",
        OperatorFamily::M,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::UnpairedSlash,
        SourceContext::Term,
        "m /spaced/; after",
        &[
            spec(ExpectedKind::RegexMatch, "m /spaced/"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::WhitespaceSeparated, Axis::AttachedUnpaired],
    ),
    row(
        "tr.whitespace.bracket",
        OperatorFamily::Tr,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBracket,
        SourceContext::Term,
        "tr [a-z] [A-Z]; after",
        &[
            spec(ExpectedKind::Transliteration, "tr [a-z] [A-Z]"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::WhitespaceSeparated, Axis::AttachedPaired],
    ),
    row(
        "s.whitespace.brace",
        OperatorFamily::S,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "s {old} {new}; after",
        &[
            spec(ExpectedKind::Substitution, "s {old} {new}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::WhitespaceSeparated, Axis::AttachedPaired],
    ),
];

const DELIMITER_FAMILIES: [MatrixRow; 22] = [
    row(
        "q.attached.paren.empty",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::PairedParen,
        SourceContext::Term,
        "q(); after",
        &[
            spec(ExpectedKind::QuoteSingle, "q()"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired, Axis::EmptyBody],
    ),
    row(
        "q.attached.bracket.empty",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::PairedBracket,
        SourceContext::Term,
        "q[]; after",
        &[
            spec(ExpectedKind::QuoteSingle, "q[]"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired, Axis::EmptyBody],
    ),
    row(
        "q.attached.angle.empty",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::PairedAngle,
        SourceContext::Term,
        "q<>; after",
        &[
            spec(ExpectedKind::QuoteSingle, "q<>"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired, Axis::EmptyBody],
    ),
    row(
        "qq.attached.paren.empty",
        OperatorFamily::Qq,
        Spelling::Attached,
        DelimiterFamily::PairedParen,
        SourceContext::Term,
        "qq(); after",
        &[
            spec(ExpectedKind::QuoteDouble, "qq()"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired, Axis::EmptyBody],
    ),
    row(
        "qw.attached.slash.empty",
        OperatorFamily::Qw,
        Spelling::Attached,
        DelimiterFamily::UnpairedSlash,
        SourceContext::Term,
        "qw//; after",
        &[
            spec(ExpectedKind::QuoteWords, "qw//"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedUnpaired, Axis::EmptyBody],
    ),
    row(
        "m.attached.brace.empty",
        OperatorFamily::M,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "m{}; after",
        &[
            spec(ExpectedKind::RegexMatch, "m{}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired, Axis::EmptyBody],
    ),
    row(
        "s.attached.brace.empty",
        OperatorFamily::S,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "s{}{}; after",
        &[
            spec(ExpectedKind::Substitution, "s{}{}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired, Axis::EmptyBody],
    ),
    row(
        "tr.attached.brace.empty",
        OperatorFamily::Tr,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "tr{}{}; after",
        &[
            spec(ExpectedKind::Transliteration, "tr{}{}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired, Axis::EmptyBody],
    ),
    row(
        "y.attached.brace.empty",
        OperatorFamily::Y,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "y{}{}; after",
        &[
            spec(ExpectedKind::Transliteration, "y{}{}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired, Axis::EmptyBody],
    ),
    row(
        "qq.attached.slash.body",
        OperatorFamily::Qq,
        Spelling::Attached,
        DelimiterFamily::UnpairedSlash,
        SourceContext::Term,
        "qq/hello/; after",
        &[
            spec(ExpectedKind::QuoteDouble, "qq/hello/"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedUnpaired],
    ),
    row(
        "qx.attached.slash.body",
        OperatorFamily::Qx,
        Spelling::Attached,
        DelimiterFamily::UnpairedSlash,
        SourceContext::Term,
        "qx/echo hi/; after",
        &[
            spec(ExpectedKind::QuoteCommand, "qx/echo hi/"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedUnpaired],
    ),
    row(
        "qr.attached.brace.pattern",
        OperatorFamily::Qr,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "qr{pat+}; after",
        &[
            spec(ExpectedKind::QuoteRegex, "qr{pat+}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedPaired],
    ),
    row(
        "y.attached.slash.body",
        OperatorFamily::Y,
        Spelling::Attached,
        DelimiterFamily::UnpairedSlash,
        SourceContext::Term,
        "y/a-z/A-Z/; after",
        &[
            spec(ExpectedKind::Transliteration, "y/a-z/A-Z/"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::AttachedUnpaired],
    ),
    row(
        "qq.whitespace.brace",
        OperatorFamily::Qq,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "qq {hello}; after",
        &[
            spec(ExpectedKind::QuoteDouble, "qq {hello}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::WhitespaceSeparated],
    ),
    row(
        "qw.whitespace.brace",
        OperatorFamily::Qw,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "qw {foo bar}; after",
        &[
            spec(ExpectedKind::QuoteWords, "qw {foo bar}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::WhitespaceSeparated],
    ),
    row(
        "qx.whitespace.brace",
        OperatorFamily::Qx,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "qx {echo hi}; after",
        &[
            spec(ExpectedKind::QuoteCommand, "qx {echo hi}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::WhitespaceSeparated],
    ),
    row(
        "qr.whitespace.brace",
        OperatorFamily::Qr,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "qr {pat+}; after",
        &[
            spec(ExpectedKind::QuoteRegex, "qr {pat+}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::WhitespaceSeparated],
    ),
    row(
        "y.whitespace.brace",
        OperatorFamily::Y,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "y {a-z} {A-Z}; after",
        &[
            spec(ExpectedKind::Transliteration, "y {a-z} {A-Z}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::WhitespaceSeparated],
    ),
    row(
        "q.attached.brace.nested",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "q{a{b}}; after",
        &[
            spec(ExpectedKind::QuoteSingle, "q{a{b}}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::NestedPaired],
    ),
    row(
        "q.attached.brace.escaped_closer",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "q{foo\\}bar}; after",
        &[
            spec(ExpectedKind::QuoteSingle, "q{foo\\}bar}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::EscapedDelimiter],
    ),
    row(
        "q.attached.brace.escaped_backslash",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "q{foo\\\\bar}; after",
        &[
            spec(ExpectedKind::QuoteSingle, "q{foo\\\\bar}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::EscapedDelimiter],
    ),
    row(
        "qw.hash_slice.enabled",
        OperatorFamily::Qw,
        Spelling::Attached,
        DelimiterFamily::UnpairedSlash,
        SourceContext::HashSlice,
        "@h{qw/a b c/};",
        &[
            spec(ExpectedKind::Identifier, "@h"),
            spec(ExpectedKind::LeftBrace, "{"),
            spec(ExpectedKind::QuoteWords, "qw/a b c/"),
            spec(ExpectedKind::RightBrace, "}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Eof, ""),
        ],
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectTerm,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::HashSlice],
    ),
];

const COMMENT_AND_HASH: [MatrixRow; 22] = [
    row(
        "q.comment_gap.before_paired",
        OperatorFamily::Q,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "q # comment\n {body}; after",
        &[
            spec(ExpectedKind::QuoteSingle, "q # comment\n {body}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::CommentGapBeforePaired],
    ),
    row(
        "qq.comment_gap.before_paired",
        OperatorFamily::Qq,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "qq # comment\n {body}; after",
        &[
            spec(ExpectedKind::QuoteDouble, "qq # comment\n {body}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::CommentGapBeforePaired],
    ),
    row(
        "qw.comment_gap.before_paired",
        OperatorFamily::Qw,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "qw # comment\n {body}; after",
        &[
            spec(ExpectedKind::QuoteWords, "qw # comment\n {body}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::CommentGapBeforePaired],
    ),
    row(
        "qx.comment_gap.before_paired",
        OperatorFamily::Qx,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "qx # comment\n {body}; after",
        &[
            spec(ExpectedKind::QuoteCommand, "qx # comment\n {body}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::CommentGapBeforePaired],
    ),
    row(
        "qr.comment_gap.before_paired",
        OperatorFamily::Qr,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "qr # comment\n {body}; after",
        &[
            spec(ExpectedKind::QuoteRegex, "qr # comment\n {body}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::CommentGapBeforePaired],
    ),
    row(
        "m.comment_gap.before_paired",
        OperatorFamily::M,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "m # comment\n {body}; after",
        &[
            spec(ExpectedKind::RegexMatch, "m # comment\n {body}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::CommentGapBeforePaired],
    ),
    row(
        "s.comment_gap.before_paired",
        OperatorFamily::S,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "s # comment\n {a} {b}; after",
        &[
            spec(ExpectedKind::Substitution, "s # comment\n {a} {b}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::CommentGapBeforePaired],
    ),
    row(
        "tr.comment_gap.before_paired",
        OperatorFamily::Tr,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "tr # comment\n {a} {b}; after",
        &[
            spec(ExpectedKind::Transliteration, "tr # comment\n {a} {b}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::CommentGapBeforePaired],
    ),
    row(
        "y.comment_gap.before_paired",
        OperatorFamily::Y,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "y # comment\n {a} {b}; after",
        &[
            spec(ExpectedKind::Transliteration, "y # comment\n {a} {b}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::CommentGapBeforePaired],
    ),
    row(
        "m.comment_gap.consecutive",
        OperatorFamily::M,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::UnpairedSlash,
        SourceContext::Term,
        "m # c1\n # c2\n /body/; after",
        &[
            spec(ExpectedKind::RegexMatch, "m # c1\n # c2\n /body/"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::ConsecutiveCommentGap, Axis::CommentGapBeforePaired],
    ),
    row(
        "q.immediate_hash.delimiter",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::UnpairedHash,
        SourceContext::Term,
        "q#body#; after",
        &[
            spec(ExpectedKind::QuoteSingle, "q#body#"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::ImmediateHash],
    ),
    row(
        "qq.immediate_hash.delimiter",
        OperatorFamily::Qq,
        Spelling::Attached,
        DelimiterFamily::UnpairedHash,
        SourceContext::Term,
        "qq#body#; after",
        &[
            spec(ExpectedKind::QuoteDouble, "qq#body#"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::ImmediateHash],
    ),
    row(
        "qw.immediate_hash.delimiter",
        OperatorFamily::Qw,
        Spelling::Attached,
        DelimiterFamily::UnpairedHash,
        SourceContext::Term,
        "qw#a b#; after",
        &[
            spec(ExpectedKind::QuoteWords, "qw#a b#"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::ImmediateHash],
    ),
    row(
        "qx.immediate_hash.delimiter",
        OperatorFamily::Qx,
        Spelling::Attached,
        DelimiterFamily::UnpairedHash,
        SourceContext::Term,
        "qx#echo#; after",
        &[
            spec(ExpectedKind::QuoteCommand, "qx#echo#"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::ImmediateHash],
    ),
    row(
        "qr.immediate_hash.delimiter",
        OperatorFamily::Qr,
        Spelling::Attached,
        DelimiterFamily::UnpairedHash,
        SourceContext::Term,
        "qr#pat#; after",
        &[
            spec(ExpectedKind::QuoteRegex, "qr#pat#"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::ImmediateHash],
    ),
    row(
        "m.immediate_hash.delimiter",
        OperatorFamily::M,
        Spelling::Attached,
        DelimiterFamily::UnpairedHash,
        SourceContext::Term,
        "m#pat#; after",
        &[
            spec(ExpectedKind::RegexMatch, "m#pat#"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::ImmediateHash],
    ),
    row(
        "s.immediate_hash.delimiter",
        OperatorFamily::S,
        Spelling::Attached,
        DelimiterFamily::UnpairedHash,
        SourceContext::Term,
        "s#a#b#; after",
        &[
            spec(ExpectedKind::Substitution, "s#a#b#"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::ImmediateHash],
    ),
    row(
        "tr.immediate_hash.delimiter",
        OperatorFamily::Tr,
        Spelling::Attached,
        DelimiterFamily::UnpairedHash,
        SourceContext::Term,
        "tr#a#b#; after",
        &[
            spec(ExpectedKind::Transliteration, "tr#a#b#"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::ImmediateHash],
    ),
    row(
        "y.immediate_hash.delimiter",
        OperatorFamily::Y,
        Spelling::Attached,
        DelimiterFamily::UnpairedHash,
        SourceContext::Term,
        "y#a#b#; after",
        &[
            spec(ExpectedKind::Transliteration, "y#a#b#"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::ImmediateHash],
    ),
    row(
        "q.whitespace_hash.comment_not_delimiter",
        OperatorFamily::Q,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::UnpairedHash,
        SourceContext::Term,
        "q # comment\n #body#; after",
        &[spec(ExpectedKind::Identifier, "q"), spec(ExpectedKind::Eof, "")],
        NextOrdinary::EatenByComment,
        TerminalStateClass::ExpectOperator,
        Disposition::Rejected,
        OracleExpectation::CompileReject,
        Some("whitespace then # is a comment, not a delimiter; following code is comment-eaten"),
        &[Axis::ImmediateHash],
    ),
    row(
        "s.whitespace_hash.comment_not_delimiter",
        OperatorFamily::S,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::UnpairedHash,
        SourceContext::Term,
        "s # comment\n #a#b#; after",
        &[spec(ExpectedKind::Identifier, "s"), spec(ExpectedKind::Eof, "")],
        NextOrdinary::EatenByComment,
        TerminalStateClass::ExpectOperator,
        Disposition::Rejected,
        OracleExpectation::CompileReject,
        Some("whitespace then # is a comment, not a delimiter; following code is comment-eaten"),
        &[Axis::ImmediateHash],
    ),
    row(
        "q.whitespace.brace.hash_in_body",
        OperatorFamily::Q,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "q { # not comment}; after",
        &[
            spec(ExpectedKind::QuoteSingle, "q { # not comment}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::WhitespaceSeparated],
    ),
];

const TWO_BODY: [MatrixRow; 10] = [
    row(
        "s.mixed.brace_to_slash",
        OperatorFamily::S,
        Spelling::Attached,
        DelimiterFamily::MixedPairedToUnpaired,
        SourceContext::Term,
        "s{a}/b/; after",
        &[
            spec(ExpectedKind::Substitution, "s{a}/b/"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::MixedSecondDelimiter],
    ),
    row(
        "s.mixed.bracket_to_brace",
        OperatorFamily::S,
        Spelling::Attached,
        DelimiterFamily::MixedDifferentPaired,
        SourceContext::Term,
        "s[a]{b}; after",
        &[
            spec(ExpectedKind::Substitution, "s[a]{b}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::MixedSecondDelimiter],
    ),
    row(
        "s.mixed.brace_to_bracket",
        OperatorFamily::S,
        Spelling::Attached,
        DelimiterFamily::MixedDifferentPaired,
        SourceContext::Term,
        "s{a}[b]; after",
        &[
            spec(ExpectedKind::Substitution, "s{a}[b]"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::MixedSecondDelimiter],
    ),
    row(
        "tr.mixed.brace_to_slash",
        OperatorFamily::Tr,
        Spelling::Attached,
        DelimiterFamily::MixedPairedToUnpaired,
        SourceContext::Term,
        "tr{a-z}/A-Z/; after",
        &[
            spec(ExpectedKind::Transliteration, "tr{a-z}/A-Z/"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::MixedSecondDelimiter],
    ),
    row(
        "y.mixed.bracket_to_slash",
        OperatorFamily::Y,
        Spelling::Attached,
        DelimiterFamily::MixedPairedToUnpaired,
        SourceContext::Term,
        "y[a-z]/A-Z/; after",
        &[
            spec(ExpectedKind::Transliteration, "y[a-z]/A-Z/"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::MixedSecondDelimiter],
    ),
    row(
        "tr.mixed.brace_space_slash",
        OperatorFamily::Tr,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::MixedPairedToUnpaired,
        SourceContext::Term,
        "tr{a} /b/; after",
        &[
            spec(ExpectedKind::Transliteration, "tr{a} /b/"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::MixedSecondDelimiter],
    ),
    row(
        "y.mixed.brace_to_pipe",
        OperatorFamily::Y,
        Spelling::Attached,
        DelimiterFamily::MixedPairedToUnpaired,
        SourceContext::Term,
        "y{a} |b|; after",
        &[
            spec(ExpectedKind::Transliteration, "y{a} |b|"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::MixedSecondDelimiter],
    ),
    row(
        "s.comment_between.brace_bodies",
        OperatorFamily::S,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "s{a} # comment\n {b}; after",
        &[
            spec(ExpectedKind::Substitution, "s{a} # comment\n {b}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::CommentBetweenBodies],
    ),
    row(
        "tr.comment_between.brace_bodies",
        OperatorFamily::Tr,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "tr{a} # comment\n {b}; after",
        &[
            spec(ExpectedKind::Transliteration, "tr{a} # comment\n {b}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::CommentBetweenBodies],
    ),
    row(
        "y.comment_between.brace_bodies",
        OperatorFamily::Y,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "y{a} # comment\n {b}; after",
        &[
            spec(ExpectedKind::Transliteration, "y{a} # comment\n {b}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::CommentBetweenBodies],
    ),
];

fn context_rows() -> Vec<MatrixRow> {
    let mut rows = vec![
        hash_key("q.hash_key", OperatorFamily::Q, "$h{q} + 1;", "q", ExpectedKind::Identifier),
        hash_key("qq.hash_key", OperatorFamily::Qq, "$h{qq} + 1;", "qq", ExpectedKind::Identifier),
        hash_key("qw.hash_key", OperatorFamily::Qw, "$h{qw} + 1;", "qw", ExpectedKind::Identifier),
        hash_key("qx.hash_key", OperatorFamily::Qx, "$h{qx} + 1;", "qx", ExpectedKind::Identifier),
        hash_key("qr.hash_key", OperatorFamily::Qr, "$h{qr} + 1;", "qr", ExpectedKind::Identifier),
        hash_key("m.hash_key", OperatorFamily::M, "$h{m} + 1;", "m", ExpectedKind::Keyword),
        hash_key("s.hash_key", OperatorFamily::S, "$h{s} + 1;", "s", ExpectedKind::Keyword),
        hash_key("tr.hash_key", OperatorFamily::Tr, "$h{tr} + 1;", "tr", ExpectedKind::Keyword),
        hash_key("y.hash_key", OperatorFamily::Y, "$h{y} + 1;", "y", ExpectedKind::Keyword),
        method("q.method", OperatorFamily::Q, "$obj->q();", "q"),
        method("qq.method", OperatorFamily::Qq, "$obj->qq();", "qq"),
        method("qw.method", OperatorFamily::Qw, "$obj->qw();", "qw"),
        method("qx.method", OperatorFamily::Qx, "$obj->qx();", "qx"),
        method("qr.method", OperatorFamily::Qr, "$obj->qr();", "qr"),
        method("m.method", OperatorFamily::M, "$obj->m();", "m"),
        method("s.method", OperatorFamily::S, "$obj->s();", "s"),
        method("tr.method", OperatorFamily::Tr, "$obj->tr();", "tr"),
        method("y.method", OperatorFamily::Y, "$obj->y();", "y"),
        fat_arrow("q.fat_arrow", OperatorFamily::Q, "q => 1;", "q"),
        fat_arrow("qq.fat_arrow", OperatorFamily::Qq, "qq => 1;", "qq"),
        fat_arrow("qw.fat_arrow", OperatorFamily::Qw, "qw => 1;", "qw"),
        fat_arrow("qx.fat_arrow", OperatorFamily::Qx, "qx => 1;", "qx"),
        fat_arrow("qr.fat_arrow", OperatorFamily::Qr, "qr => 1;", "qr"),
        fat_arrow("m.fat_arrow", OperatorFamily::M, "m => 1;", "m"),
        fat_arrow("s.fat_arrow", OperatorFamily::S, "s => 1;", "s"),
        fat_arrow("tr.fat_arrow", OperatorFamily::Tr, "tr => 1;", "tr"),
        fat_arrow("y.fat_arrow", OperatorFamily::Y, "y => 1;", "y"),
    ];
    rows.extend_from_slice(&EXTRA_CONTEXT);
    rows.push(row(
        "q.attribute_looks_like_quote",
        OperatorFamily::Q,
        Spelling::WhitespaceSeparated,
        DelimiterFamily::PairedBrace,
        SourceContext::Attribute,
        "sub foo :q { }",
        static_specs(&[
            spec(ExpectedKind::Keyword, "sub"),
            spec(ExpectedKind::Identifier, "foo"),
            spec(ExpectedKind::Operator, ":"),
            spec(ExpectedKind::QuoteSingle, "q { }"),
            spec(ExpectedKind::Eof, ""),
        ]),
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::Skip,
        Some("current-main lexes an attribute-looking `q` as quote-like; attribute semantics are not this matrix's claim"),
        &[Axis::SubroutineName],
    ));
    rows.push(row(
        "q.prototype_unclosed_quote",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::PairedParen,
        SourceContext::Prototype,
        "sub foo (q) { }",
        static_specs(&[
            spec(ExpectedKind::Keyword, "sub"),
            spec(ExpectedKind::Identifier, "foo"),
            spec(ExpectedKind::LeftParen, "("),
            spec(ExpectedKind::Error, "q) { }"),
            spec(ExpectedKind::Eof, ""),
        ]),
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectOperator,
        Disposition::Rejected,
        OracleExpectation::Skip,
        Some("prototype `q` currently starts an unclosed quote-like Error"),
        &[Axis::SubroutineName],
    ));
    rows.push(row(
        "q.signature_scalar_not_quote",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::NotApplicable,
        SourceContext::Signature,
        "sub foo ($q) { }",
        static_specs(&[
            spec(ExpectedKind::Keyword, "sub"),
            spec(ExpectedKind::Identifier, "foo"),
            spec(ExpectedKind::LeftParen, "("),
            spec(ExpectedKind::Identifier, "$q"),
            spec(ExpectedKind::RightParen, ")"),
            spec(ExpectedKind::LeftBrace, "{"),
            spec(ExpectedKind::RightBrace, "}"),
            spec(ExpectedKind::Eof, ""),
        ]),
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::Skip,
        Some("signature `$q` is an identifier, not a quote-like operator"),
        &[Axis::SubroutineName],
    ));
    rows
}

fn static_specs(tokens: &[TokenSpec]) -> &'static [TokenSpec] {
    Box::leak(tokens.to_vec().into_boxed_slice())
}

fn hash_key(
    id: &'static str,
    operator: OperatorFamily,
    source: &'static str,
    name: &'static str,
    kind: ExpectedKind,
) -> MatrixRow {
    row(
        id,
        operator,
        Spelling::Attached,
        DelimiterFamily::NotApplicable,
        SourceContext::HashKey,
        source,
        static_specs(&[
            spec(ExpectedKind::Identifier, "$h"),
            spec(ExpectedKind::LeftBrace, "{"),
            spec(kind, name),
            spec(ExpectedKind::RightBrace, "}"),
            spec(ExpectedKind::Operator, "+"),
            spec(ExpectedKind::Number, "1"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Eof, ""),
        ]),
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectTerm,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::HashKey],
    )
}

fn method(
    id: &'static str,
    operator: OperatorFamily,
    source: &'static str,
    name: &'static str,
) -> MatrixRow {
    row(
        id,
        operator,
        Spelling::Attached,
        DelimiterFamily::NotApplicable,
        SourceContext::Method,
        source,
        static_specs(&[
            spec(ExpectedKind::Identifier, "$obj"),
            spec(ExpectedKind::Operator, "->"),
            spec(ExpectedKind::Keyword, name),
            spec(ExpectedKind::LeftParen, "("),
            spec(ExpectedKind::RightParen, ")"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Eof, ""),
        ]),
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectTerm,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::Method],
    )
}

fn fat_arrow(
    id: &'static str,
    operator: OperatorFamily,
    source: &'static str,
    name: &'static str,
) -> MatrixRow {
    row(
        id,
        operator,
        Spelling::Attached,
        DelimiterFamily::NotApplicable,
        SourceContext::FatArrow,
        source,
        static_specs(&[
            spec(ExpectedKind::Identifier, name),
            spec(ExpectedKind::Operator, "=>"),
            spec(ExpectedKind::Number, "1"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Eof, ""),
        ]),
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectTerm,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::FatArrow],
    )
}

const EXTRA_CONTEXT: [MatrixRow; 8] = [
    row(
        "q.subroutine_name",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::NotApplicable,
        SourceContext::SubroutineName,
        "sub q { }",
        &[
            spec(ExpectedKind::Keyword, "sub"),
            spec(ExpectedKind::Keyword, "q"),
            spec(ExpectedKind::LeftBrace, "{"),
            spec(ExpectedKind::RightBrace, "}"),
            spec(ExpectedKind::Eof, ""),
        ],
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::SubroutineName],
    ),
    row(
        "tr.subroutine_name",
        OperatorFamily::Tr,
        Spelling::Attached,
        DelimiterFamily::NotApplicable,
        SourceContext::SubroutineName,
        "sub tr { 1 }",
        &[
            spec(ExpectedKind::Keyword, "sub"),
            spec(ExpectedKind::Keyword, "tr"),
            spec(ExpectedKind::LeftBrace, "{"),
            spec(ExpectedKind::Number, "1"),
            spec(ExpectedKind::RightBrace, "}"),
            spec(ExpectedKind::Eof, ""),
        ],
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::SubroutineName],
    ),
    row(
        "y.subroutine_name",
        OperatorFamily::Y,
        Spelling::Attached,
        DelimiterFamily::NotApplicable,
        SourceContext::SubroutineName,
        "sub y { 1 }",
        &[
            spec(ExpectedKind::Keyword, "sub"),
            spec(ExpectedKind::Keyword, "y"),
            spec(ExpectedKind::LeftBrace, "{"),
            spec(ExpectedKind::Number, "1"),
            spec(ExpectedKind::RightBrace, "}"),
            spec(ExpectedKind::Eof, ""),
        ],
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::SubroutineName],
    ),
    row(
        "q.package_name",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::NotApplicable,
        SourceContext::PackageName,
        "package q::x;",
        &[
            spec(ExpectedKind::Keyword, "package"),
            spec(ExpectedKind::Identifier, "q::x"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Eof, ""),
        ],
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectTerm,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::PackageName],
    ),
    row(
        "q.label_then_quote",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Label,
        "label: q{x};",
        &[
            spec(ExpectedKind::Identifier, "label"),
            spec(ExpectedKind::Operator, ":"),
            spec(ExpectedKind::QuoteSingle, "q{x}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Eof, ""),
        ],
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectTerm,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::Label],
    ),
    row(
        "q.division_operand",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::DivisionOperand,
        "1 / q{x};",
        &[
            spec(ExpectedKind::Number, "1"),
            spec(ExpectedKind::Division, "/"),
            spec(ExpectedKind::QuoteSingle, "q{x}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Eof, ""),
        ],
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectTerm,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::Division],
    ),
    row(
        "q.defined_or_operand",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::DefinedOrOperand,
        "undef // q{x};",
        &[
            spec(ExpectedKind::Keyword, "undef"),
            spec(ExpectedKind::Operator, "//"),
            spec(ExpectedKind::QuoteSingle, "q{x}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Eof, ""),
        ],
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectTerm,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::DefinedOr],
    ),
    row(
        "s.file_test_suppressed",
        OperatorFamily::S,
        Spelling::Attached,
        DelimiterFamily::NotApplicable,
        SourceContext::FileTest,
        "-s 'path';",
        &[
            spec(ExpectedKind::Operator, "-"),
            spec(ExpectedKind::Identifier, "s"),
            spec(ExpectedKind::StringLiteral, "'path'"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Eof, ""),
        ],
        NextOrdinary::NoneAtEof,
        TerminalStateClass::ExpectTerm,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::FileTest],
    ),
];

fn malformed_rows() -> Vec<MatrixRow> {
    vec![
        error_eats(
            "q.malformed.unclosed_brace_follower",
            OperatorFamily::Q,
            DelimiterFamily::PairedBrace,
            "q{unterminated\n; after",
            OracleExpectation::CompileReject,
        ),
        error_eats(
            "qq.malformed.unclosed_slash_follower",
            OperatorFamily::Qq,
            DelimiterFamily::UnpairedSlash,
            "qq/unclosed; after",
            OracleExpectation::CompileReject,
        ),
        error_eats(
            "qw.malformed.unclosed_slash_follower",
            OperatorFamily::Qw,
            DelimiterFamily::UnpairedSlash,
            "qw/unclosed; after",
            OracleExpectation::CompileReject,
        ),
        error_eats(
            "qx.malformed.unclosed_slash_follower",
            OperatorFamily::Qx,
            DelimiterFamily::UnpairedSlash,
            "qx/unclosed; after",
            OracleExpectation::CompileReject,
        ),
        error_eats(
            "qr.malformed.unclosed_slash_follower",
            OperatorFamily::Qr,
            DelimiterFamily::UnpairedSlash,
            "qr/unclosed; after",
            OracleExpectation::CompileReject,
        ),
        error_eats(
            "m.malformed.unclosed_slash_follower",
            OperatorFamily::M,
            DelimiterFamily::UnpairedSlash,
            "m/pat; after extra",
            OracleExpectation::CompileReject,
        ),
        error_eats(
            "s.malformed.missing_replacement_follower",
            OperatorFamily::S,
            DelimiterFamily::UnpairedSlash,
            "s/a/; after",
            OracleExpectation::CompileReject,
        ),
        error_eats(
            "tr.malformed.missing_replacement_follower",
            OperatorFamily::Tr,
            DelimiterFamily::UnpairedSlash,
            "tr/a-z/; after",
            OracleExpectation::CompileReject,
        ),
        error_eats(
            "y.malformed.unclosed_second_bracket_follower",
            OperatorFamily::Y,
            DelimiterFamily::PairedBracket,
            "y[a-z][A-Z; after",
            OracleExpectation::CompileReject,
        ),
    ]
}

fn error_eats(
    id: &'static str,
    operator: OperatorFamily,
    delimiter: DelimiterFamily,
    source: &'static str,
    oracle: OracleExpectation,
) -> MatrixRow {
    row(
        id,
        operator,
        Spelling::Attached,
        delimiter,
        SourceContext::Term,
        source,
        static_specs(&[spec(ExpectedKind::Error, source), spec(ExpectedKind::Eof, "")]),
        NextOrdinary::EatenByError,
        TerminalStateClass::ExpectOperator,
        Disposition::Rejected,
        oracle,
        Some("current-main Error token over-consumes named following code"),
        &[Axis::MalformedFollower],
    )
}

const NEWLINE_UNICODE_MODIFIER: [MatrixRow; 8] = [
    row(
        "qq.multiline.lf",
        OperatorFamily::Qq,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "qq{\n café $name\n}; after",
        &[
            spec(ExpectedKind::QuoteDouble, "qq{\n café $name\n}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::MultilineLf, Axis::Unicode],
    ),
    row(
        "qq.multiline.crlf",
        OperatorFamily::Qq,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "qq{\r\n café $name\r\n}; after",
        &[
            spec(ExpectedKind::QuoteDouble, "qq{\r\n café $name\r\n}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::MultilineCrlf, Axis::Unicode],
    ),
    row(
        "qq.multiline.cr",
        OperatorFamily::Qq,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "qq{\r café $name\r}; after",
        &[
            spec(ExpectedKind::QuoteDouble, "qq{\r café $name\r}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::Skip,
        Some(
            "bare CR line endings are recorded from the lexer; perl -c line discipline is not this row's subject",
        ),
        &[Axis::MultilineCr, Axis::Unicode],
    ),
    row(
        "q.unicode.body",
        OperatorFamily::Q,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "q{ユニコード}; after",
        &[
            spec(ExpectedKind::QuoteSingle, "q{ユニコード}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::Unicode],
    ),
    row(
        "qw.unicode.body",
        OperatorFamily::Qw,
        Spelling::Attached,
        DelimiterFamily::PairedBrace,
        SourceContext::Term,
        "qw{α β}; after",
        &[
            spec(ExpectedKind::QuoteWords, "qw{α β}"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::Unicode],
    ),
    row(
        "qr.modifier.next_tokens",
        OperatorFamily::Qr,
        Spelling::Attached,
        DelimiterFamily::UnpairedSlash,
        SourceContext::Term,
        "qr/pat+/i; after extra",
        &[
            spec(ExpectedKind::QuoteRegex, "qr/pat+/i"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Identifier, "extra"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::Modifier],
    ),
    row(
        "s.modifier.e_extent",
        OperatorFamily::S,
        Spelling::Attached,
        DelimiterFamily::UnpairedSlash,
        SourceContext::Term,
        "s/a/b/e; after",
        &[
            spec(ExpectedKind::Substitution, "s/a/b/e"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::Modifier],
    ),
    row(
        "y.modifier.d_extent",
        OperatorFamily::Y,
        Spelling::Attached,
        DelimiterFamily::UnpairedSlash,
        SourceContext::Term,
        "y/a/b/d; after",
        &[
            spec(ExpectedKind::Transliteration, "y/a/b/d"),
            spec(ExpectedKind::Semicolon, ";"),
            spec(ExpectedKind::Identifier, "after"),
            spec(ExpectedKind::Eof, ""),
        ],
        AFTER,
        TerminalStateClass::ExpectOperator,
        Disposition::Clean,
        OracleExpectation::CompileAccept,
        None,
        &[Axis::Modifier],
    ),
];
