//! Deterministic generated coverage view for the reachability fixture
//! manifest (#10998). The manifest stays canonical; this projection is always
//! regenerated from it and never hand-edited.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use super::model::{FixtureRole, Manifest, Row, SupportClass, TerminalOutcome};

/// Renders the canonical coverage view. Output depends only on manifest
/// content: rows are visited in `row_id` order and all aggregates use ordered
/// maps, so insertion order cannot change bytes.
pub fn render(manifest: &Manifest) -> String {
    let mut rows_by_id = manifest.rows.clone();
    rows_by_id.sort_by(|left, right| left.row_id.cmp(&right.row_id));

    let mut families: BTreeMap<&str, Vec<&Row>> = BTreeMap::new();
    for row in &rows_by_id {
        families.entry(row.train.family.as_str()).or_default().push(row);
    }

    let mut out = String::new();
    let _ = writeln!(out, "# Reachability fixture denominator coverage view");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Generated from `{}` by `cargo xtask check-reachability-fixture-manifest`.",
        super::model::MANIFEST_RELATIVE_PATH
    );
    let _ = writeln!(out, "Canonical source: the manifest. Do not edit this file.");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "| family | rows | positives | opposite controls | near-neighbour controls | falsifiers | not-proven instruments | deferred slots |",
    );
    let _ = writeln!(out, "| --- | --- | --- | --- | --- | --- | --- | --- |");

    let mut total_rows = 0usize;
    let mut total_not_proven = 0usize;
    for family in super::model::FAMILIES {
        let family_rows = families.get(*family).cloned().unwrap_or_default();
        let positives = count_role(&family_rows, FixtureRole::Positive);
        let opposite = count_role(&family_rows, FixtureRole::ControlOpposite);
        let near_neighbour = count_role(&family_rows, FixtureRole::ControlNearNeighbour);
        let falsifiers = count_role(&family_rows, FixtureRole::Falsifier);
        let not_proven = family_rows.iter().filter(|row| is_not_proven(row)).count();
        let deferred = manifest
            .denominator
            .iter()
            .find(|entry| entry.family == *family)
            .map(|entry| entry.deferred_coverage.len())
            .unwrap_or(0);
        total_rows += family_rows.len();
        total_not_proven += not_proven;
        let _ = writeln!(
            out,
            "| {family} | {} | {positives} | {opposite} | {near_neighbour} | {falsifiers} | {not_proven} | {deferred} |",
            family_rows.len(),
        );
    }

    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Total: {total_rows} rows across {} families; {total_not_proven} rows carry missing instruments (explicitly NOT_PROVEN, never clean coverage).",
        super::model::FAMILIES.len(),
    );

    let _ = writeln!(out);
    let _ = writeln!(out, "## Terminal outcome profile");
    let _ = writeln!(out);
    let mut terminals: BTreeMap<TerminalOutcome, usize> = BTreeMap::new();
    for row in &rows_by_id {
        *terminals.entry(row.terminal).or_default() += 1;
    }
    for (terminal, count) in terminals {
        let _ = writeln!(out, "- {terminal:?}: {count}");
    }

    let _ = writeln!(out);
    let _ = writeln!(out, "## Open deferrals (declared, not yet instantiated)");
    let _ = writeln!(out);
    let mut any_deferral = false;
    for entry in &manifest.denominator {
        for slot in &entry.deferred_coverage {
            any_deferral = true;
            let _ = writeln!(
                out,
                "- {}: {} → #{} ({})",
                entry.family, slot.coverage, slot.owner_issue, slot.reason,
            );
        }
    }
    if !any_deferral {
        let _ = writeln!(out, "- none");
    }

    let _ = writeln!(out);
    let _ = writeln!(out, "## Rows with unsupported or partial limitations");
    let _ = writeln!(out);
    let mut any_limitation = false;
    for row in &rows_by_id {
        if !matches!(row.limitation.support_class, SupportClass::Supported) {
            any_limitation = true;
            let owner = row
                .limitation
                .exit_owner_issue
                .map(|issue| format!("#{issue}"))
                .unwrap_or_else(|| "missing-exit-owner".to_string());
            let _ = writeln!(out, "- {}: {:?} → {owner}", row.row_id, row.limitation.support_class);
        }
    }
    if !any_limitation {
        let _ = writeln!(out, "- none");
    }

    out
}

fn count_role(rows: &[&Row], role: FixtureRole) -> usize {
    rows.iter().filter(|row| row.fixture.role == role).count()
}

fn is_not_proven(row: &Row) -> bool {
    row.instrument.as_ref().is_some_and(|instrument| {
        matches!(instrument.status, super::model::InstrumentStatusKind::Missing)
    })
}
