//! `.ptkdbrc` bootstrap/fallback rendering for `Devel::ptkdb`.
//!
//! This is the **secondary**, compatibility surface (decision D8/DF): it lets a
//! user drive ptkdb today — before any live peer protocol exists in ptkdb — by
//! generating a `.ptkdbrc` startup file, the `perl -d:ptkdb` launch command, and
//! the environment (`PTKDB_DISPLAY`). It is a bootstrap, not the long-term live
//! bridge (that is [`crate::backend::external_peer`]).
//!
//! `.ptkdbrc` is eval'd as Perl by ptkdb before the first debugger stop, so the
//! generated file must be valid Perl. All interpolated user data (paths,
//! conditions, expressions) is emitted as **single-quoted Perl literals** with
//! `\` and `'` escaped, so a crafted path/condition cannot inject code.
//!
//! The precise ptkdb startup API is documented in
//! `docs/reference/PTKDB_PEER_INTEGRATION_TARGET.md`; the call shapes are
//! centralized in [`api`] so they track a single source of truth.

use crate::model::DebugSessionPacket;

/// The ptkdb startup-file API call shapes, kept in one place so they can be
/// tuned to match the installed ptkdb version.
mod api {
    /// Variable that suppresses stopping at program entry.
    pub const NO_STOP_AT_START: &str = "$DB::no_stop_at_start";
}

/// Escape a string for embedding inside a single-quoted Perl literal.
///
/// In single-quoted Perl strings only `\` and `'` are special, so escaping just
/// those two is both necessary and sufficient. This prevents a path or
/// expression containing `'` from terminating the literal (code injection).
#[must_use]
pub fn escape_perl_single_quoted(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    for ch in s.chars() {
        if ch == '\\' || ch == '\'' {
            out.push('\\');
        }
        out.push(ch);
    }
    out
}

/// Wrap a string as a complete single-quoted Perl literal (`'...'`).
#[must_use]
pub fn perl_single_quoted(s: &str) -> String {
    format!("'{}'", escape_perl_single_quoted(s))
}

/// Render a `.ptkdbrc` file from a session packet.
///
/// The file:
/// - documents its provenance,
/// - optionally suppresses the initial stop (when `stop_on_entry` is false),
/// - registers line and conditional breakpoints,
/// - registers subroutine and regex subroutine breakpoints,
/// - seeds the watch/expression list.
///
/// Breakpoint registration uses the documented ptkdb startup subroutines; see
/// [`api`] and the integration-target doc. Because exact method availability can
/// vary by ptkdb version, each registration is wrapped in `eval { ... };` so a
/// single unsupported call degrades gracefully instead of aborting the whole
/// startup file.
#[must_use]
pub fn render_ptkdbrc(packet: &DebugSessionPacket, stop_on_entry: bool) -> String {
    let mut out = String::new();
    out.push_str("# Generated by perl-dap (perl-lsp) — Devel::ptkdb bootstrap.\n");
    out.push_str("# This file is eval'd as Perl by ptkdb before the first stop.\n");
    out.push_str(&format!("# schema: {}\n", packet.schema));
    out.push_str(&format!("# program: {}\n", packet.program.display()));
    out.push('\n');

    if !stop_on_entry {
        out.push_str("# Do not halt immediately at program entry.\n");
        out.push_str(&format!("{} = 1;\n\n", api::NO_STOP_AT_START));
    }

    if !packet.breakpoints.is_empty() {
        out.push_str("# Line breakpoints.\n");
        for bp in &packet.breakpoints {
            let file = perl_single_quoted(&bp.source.path.to_string_lossy());
            match &bp.condition {
                Some(cond) => {
                    out.push_str(&format!(
                        "eval {{ condbrkpt({file}, {line}, {cond}); }};\n",
                        line = bp.line,
                        cond = perl_single_quoted(cond),
                    ));
                }
                None => {
                    out.push_str(&format!("eval {{ brkpt({file}, {line}); }};\n", line = bp.line));
                }
            }
        }
        out.push('\n');
    }

    if !packet.function_breakpoints.is_empty() {
        out.push_str("# Subroutine breakpoints.\n");
        for name in &packet.function_breakpoints {
            out.push_str(&format!("eval {{ brkonsub({}); }};\n", perl_single_quoted(name)));
        }
        out.push('\n');
    }

    if !packet.function_breakpoint_regexes.is_empty() {
        out.push_str("# Subroutine regex breakpoints.\n");
        for re in &packet.function_breakpoint_regexes {
            out.push_str(&format!("eval {{ brkonsub_regex({}); }};\n", perl_single_quoted(re)));
        }
        out.push('\n');
    }

    if !packet.watch_expressions.is_empty() {
        out.push_str("# Watch / expression list.\n");
        let exprs: Vec<String> =
            packet.watch_expressions.iter().map(|e| perl_single_quoted(e)).collect();
        out.push_str(&format!("eval {{ add_exprs({}); }};\n\n", exprs.join(", ")));
    }

    out.push_str("1;\n");
    out
}

/// Render the `perl -d:ptkdb` launch command for a program.
///
/// Returns the argv vector (excluding the leading interpreter, which is
/// `perl_path` or `perl`), so callers can spawn it directly. `@INC` additions
/// are passed as `-I` flags.
#[must_use]
pub fn render_launch_command(packet: &DebugSessionPacket) -> Vec<String> {
    let mut argv = Vec::new();
    argv.push("-d:ptkdb".to_string());
    for inc in &packet.include_paths {
        argv.push(format!("-I{}", inc.display()));
    }
    argv.push(packet.program.to_string_lossy().into_owned());
    argv
}

/// Render the environment variables ptkdb honors.
///
/// `PTKDB_DISPLAY` points ptkdb's Tk GUI at an X display (useful for remote /
/// headless debugging). Only variables with values are returned.
#[must_use]
pub fn render_env(display: Option<&str>) -> Vec<(String, String)> {
    let mut env = Vec::new();
    if let Some(d) = display {
        env.push(("PTKDB_DISPLAY".to_string(), d.to_string()));
    }
    env
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{DebugBreakpoint, DebugSource};

    fn packet() -> DebugSessionPacket {
        let mut p = DebugSessionPacket::new("/work/script.pl");
        p.include_paths.push("lib".into());
        p.breakpoints.push(DebugBreakpoint {
            id: None,
            source: DebugSource::from_path("/work/script.pl"),
            line: 42,
            column: None,
            condition: Some("$x > 10".to_string()),
            hit_condition: None,
            log_message: None,
        });
        p.breakpoints.push(DebugBreakpoint {
            id: None,
            source: DebugSource::from_path("/work/script.pl"),
            line: 7,
            column: None,
            condition: None,
            hit_condition: None,
            log_message: None,
        });
        p.function_breakpoints.push("main::run".to_string());
        p.function_breakpoint_regexes.push("^My::App::".to_string());
        p.watch_expressions.push("$self".to_string());
        p
    }

    #[test]
    fn escape_neutralizes_quote_injection() {
        // A path with an embedded quote + code must not break out of the literal.
        let malicious = "/tmp/a'; system('rm -rf /'); '";
        let escaped = escape_perl_single_quoted(malicious);
        // Invariant: no single quote appears unescaped — every `'` is preceded
        // by a `\`, so it cannot terminate the surrounding single-quoted literal.
        let chars: Vec<char> = escaped.chars().collect();
        for (i, &c) in chars.iter().enumerate() {
            if c == '\'' {
                assert!(
                    i > 0 && chars[i - 1] == '\\',
                    "quote at index {i} is not backslash-escaped: {escaped}"
                );
            }
        }
        // Every original quote produced exactly one escaped quote.
        assert_eq!(escaped.matches("\\'").count(), malicious.matches('\'').count());
    }

    #[test]
    fn escape_handles_backslashes() {
        assert_eq!(escape_perl_single_quoted(r"a\b"), r"a\\b");
        assert_eq!(perl_single_quoted(r"a\b'c"), r"'a\\b\'c'");
    }

    #[test]
    fn rc_registers_all_breakpoint_kinds() {
        let rc = render_ptkdbrc(&packet(), false);
        assert!(rc.contains("$DB::no_stop_at_start = 1;"));
        assert!(rc.contains("condbrkpt('/work/script.pl', 42, '$x > 10');"));
        assert!(rc.contains("brkpt('/work/script.pl', 7);"));
        assert!(rc.contains("brkonsub('main::run');"));
        assert!(rc.contains("brkonsub_regex('^My::App::');"));
        assert!(rc.contains("add_exprs('$self');"));
        assert!(rc.trim_end().ends_with("1;"), "rc must return true");
    }

    #[test]
    fn rc_omits_no_stop_when_stop_on_entry() {
        let rc = render_ptkdbrc(&packet(), true);
        assert!(!rc.contains("no_stop_at_start"));
    }

    #[test]
    fn launch_command_uses_ptkdb_and_includes() {
        let argv = render_launch_command(&packet());
        assert_eq!(argv[0], "-d:ptkdb");
        assert!(argv.iter().any(|a| a == "-Ilib"));
        assert!(argv.last().expect("program").ends_with("script.pl"));
    }

    #[test]
    fn env_only_present_when_display_set() {
        assert!(render_env(None).is_empty());
        let env = render_env(Some(":0"));
        assert_eq!(env, vec![("PTKDB_DISPLAY".to_string(), ":0".to_string())]);
    }
}
