use super::{
    ConfigConsumer as Consumer, ConfigOwner as Owner, ConfigScope as Scope,
    ConfigSensitivity as Sensitivity, ConfigSource as Source, ConfigValidation as Validation,
    ConfigValueKind as Kind, EvidencePolicy as Evidence, FieldAuthority,
    InvalidValueFallback as Fallback, InvalidationClass as Invalidation,
};

const CLIENT_GLOBAL: &[Source] = &[
    Source::CompiledDefault,
    Source::InitializationOptions,
    Source::ProjectFile,
    Source::GlobalClientSettings,
];
/// Arm/select AI fields (#4997): only compiled defaults plus a trusted
/// user/operator observation may write these. Every current client channel
/// (`initializationOptions`, `didChangeConfiguration`, generic
/// workspace/configuration results) is rejected by `update_from_value`, so
/// production values stay at their defaults until the server-owned operator
/// adapter lands (#10817). `.perl-lsp.toml` never had arm/select authority
/// (issues #4955, #4997).
const AI_TRUSTED_OPERATOR_CHANNEL: &[Source] =
    &[Source::CompiledDefault, Source::TrustedUserSettings];
/// Envelope fields remain genuinely client-settable through
/// `initializationOptions`/global client settings via `update_from_value`
/// (issue #4955 review): they shape requests but can neither arm egress nor
/// select its destination or identity.
const AI_CLIENT_ENVELOPE_CHANNEL: &[Source] =
    &[Source::CompiledDefault, Source::InitializationOptions, Source::GlobalClientSettings];
/// Sources of the DERIVED `ai.effective_enabled` value: trusted user/operator
/// enablement reduced by the project file, because `.perl-lsp.toml enabled =
/// false` feeds `project_opt_out` and recomputes
/// `enabled = user_enabled && !project_opt_out`. The project file contributes
/// here only as a reducer into that derivation; it still has no arm/select
/// authority over any direct AI activation row (issues #4955, #4997).
const AI_EFFECTIVE_ENABLED_SOURCES: &[Source] =
    &[Source::CompiledDefault, Source::ProjectFile, Source::TrustedUserSettings];
const CLIENT_FOLDER: &[Source] = &[
    Source::CompiledDefault,
    Source::InitializationOptions,
    Source::ProjectFile,
    Source::GlobalClientSettings,
    Source::WorkspaceConfiguration,
];
const PROJECT_ONLY: &[Source] = &[Source::CompiledDefault, Source::ProjectFile];
const TRUSTED_USER_PROJECT: &[Source] =
    &[Source::CompiledDefault, Source::ProjectFile, Source::TrustedUserSettings];
const MACHINE_PATH: &[Source] = &[Source::CompiledDefault, Source::TrustedUserSettings];
const WORKSPACE_ENVIRONMENT: &[Source] = &[
    Source::CompiledDefault,
    Source::InitializationOptions,
    Source::ProjectFile,
    Source::GlobalClientSettings,
    Source::WorkspaceConfiguration,
    Source::Environment,
];
const WORKSPACE_SYSTEM: &[Source] = &[
    Source::CompiledDefault,
    Source::InitializationOptions,
    Source::ProjectFile,
    Source::GlobalClientSettings,
    Source::WorkspaceConfiguration,
    Source::SystemProbe,
];
const PROJECT_METADATA: &[Source] = &[Source::CompiledDefault, Source::ProjectMetadata];

const AI: &[Consumer] = &[Consumer::InlineCompletion, Consumer::AiTransport];
const AI_SCHEDULER: &[Consumer] = &[Consumer::InlineCompletion, Consumer::AiScheduler];
const CRITIC: &[Consumer] =
    &[Consumer::NativeCritic, Consumer::LegacyCritic, Consumer::DiagnosticCache];
const NATIVE_CRITIC: &[Consumer] = &[Consumer::NativeCritic, Consumer::DiagnosticCache];
const FORMATTER: &[Consumer] = &[Consumer::NativeFormatter, Consumer::ExternalFormatter];
const FORMATTER_SAVE: &[Consumer] =
    &[Consumer::NativeFormatter, Consumer::ExternalFormatter, Consumer::SaveFormatting];
const RESOLUTION: &[Consumer] =
    &[Consumer::ModuleResolver, Consumer::WorkspaceIndex, Consumer::DependencyGraph];
const DISCOVERY: &[Consumer] =
    &[Consumer::WorkspaceDiscovery, Consumer::WorkspaceIndex, Consumer::DependencyGraph];

macro_rules! authority {
    (
        $id:literal, $owner:ident.$field:ident, $scope:ident, $kind:ident,
        $sources:expr, $validation:expr, $fallback:ident,
        $sensitivity:ident, $evidence:ident, $invalidation:ident,
        $consumers:expr, [$($marker:literal),+ $(,)?]
    ) => {
        FieldAuthority {
            id: $id,
            owner: Owner::$owner,
            rust_field: stringify!($field),
            scope: Scope::$scope,
            value_kind: Kind::$kind,
            sources: $sources,
            validation: $validation,
            invalid_fallback: Fallback::$fallback,
            sensitivity: Sensitivity::$sensitivity,
            evidence_policy: Evidence::$evidence,
            invalidation: Invalidation::$invalidation,
            consumers: $consumers,
            source_markers: &[$($marker),+],
        }
    };
}

/// Canonical effective-field authority, sorted by stable ID.
pub(crate) static CONFIGURATION_AUTHORITY: &[FieldAuthority] = &[
    authority!(
        "ai.activation_authority",
        AiCompletion.activation_authority,
        Global,
        Enum,
        AI_TRUSTED_OPERATOR_CHANNEL,
        Validation::KnownEnum,
        RejectSource,
        Ordinary,
        SafeValue,
        InlineCompletion,
        AI,
        ["activation_authority"]
    ),
    authority!(
        "ai.api_key_env",
        AiCompletion.api_key_env,
        Global,
        String,
        MACHINE_PATH,
        Validation::NonEmptyString,
        KeepLastValid,
        CredentialLocator,
        Redacted,
        InlineCompletion,
        AI,
        ["aiCompletion.apiKeyEnv"]
    ),
    authority!(
        "ai.api_key_header",
        AiCompletion.api_key_header,
        Global,
        String,
        MACHINE_PATH,
        Validation::HttpHeaderName,
        KeepLastValid,
        HeaderMaterial,
        Redacted,
        InlineCompletion,
        AI,
        ["aiCompletion.apiKeyHeader"]
    ),
    authority!(
        "ai.api_key_prefix",
        AiCompletion.api_key_prefix,
        Global,
        OptionalString,
        MACHINE_PATH,
        Validation::SafeHeaderPrefix,
        KeepLastValid,
        HeaderMaterial,
        Redacted,
        InlineCompletion,
        AI,
        ["aiCompletion.apiKeyPrefix"]
    ),
    authority!(
        "ai.effective_enabled",
        AiCompletion.enabled,
        DerivedGlobal,
        Boolean,
        AI_EFFECTIVE_ENABLED_SOURCES,
        Validation::Derived,
        RecomputeDerived,
        Ordinary,
        DerivedDigestOnly,
        InlineCompletion,
        AI,
        ["aiCompletion.enabled", "project_opt_out"]
    ),
    authority!(
        "ai.endpoint",
        AiCompletion.endpoint,
        Global,
        String,
        MACHINE_PATH,
        Validation::HttpsOrLoopbackEndpoint,
        RejectSource,
        NetworkEndpoint,
        Redacted,
        InlineCompletion,
        AI,
        ["aiCompletion.endpoint"]
    ),
    authority!(
        "ai.fallback",
        AiCompletion.fallback,
        Global,
        Boolean,
        AI_CLIENT_ENVELOPE_CHANNEL,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        InlineCompletion,
        AI,
        ["aiCompletion.fallback"]
    ),
    authority!(
        "ai.local_model_mode",
        AiCompletion.local_model_mode,
        Global,
        Boolean,
        AI_CLIENT_ENVELOPE_CHANNEL,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        InlineCompletion,
        AI,
        ["aiCompletion.localModelMode"]
    ),
    authority!(
        "ai.max_inflight",
        AiCompletion.max_inflight,
        Global,
        Unsigned,
        AI_CLIENT_ENVELOPE_CHANNEL,
        Validation::UnsignedRange { minimum: 1, maximum: 64 },
        KeepLastValid,
        Ordinary,
        SafeValue,
        RuntimeScheduling,
        AI_SCHEDULER,
        ["aiCompletion.maxInflight"]
    ),
    authority!(
        "ai.max_output_tokens",
        AiCompletion.max_output_tokens,
        Global,
        Unsigned,
        AI_CLIENT_ENVELOPE_CHANNEL,
        Validation::UnsignedRange { minimum: 1, maximum: 4096 },
        KeepLastValid,
        Ordinary,
        SafeValue,
        InlineCompletion,
        AI,
        ["aiCompletion.maxOutputTokens"]
    ),
    authority!(
        "ai.model",
        AiCompletion.model,
        Global,
        String,
        AI_TRUSTED_OPERATOR_CHANNEL,
        Validation::NonEmptyString,
        KeepLastValid,
        Ordinary,
        BoundedValue,
        InlineCompletion,
        AI,
        ["aiCompletion.model"]
    ),
    authority!(
        "ai.project_opt_out",
        AiCompletion.project_opt_out,
        Global,
        Boolean,
        PROJECT_ONLY,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        InlineCompletion,
        AI,
        ["project_opt_out"]
    ),
    authority!(
        "ai.provider",
        AiCompletion.provider,
        Global,
        String,
        AI_TRUSTED_OPERATOR_CHANNEL,
        Validation::KnownEnum,
        KeepLastValid,
        Ordinary,
        BoundedValue,
        InlineCompletion,
        AI,
        ["aiCompletion.provider"]
    ),
    authority!(
        "ai.rate_limit_rps",
        AiCompletion.rate_limit_rps,
        Global,
        Float,
        AI_CLIENT_ENVELOPE_CHANNEL,
        Validation::PositiveFloat,
        KeepLastValid,
        Ordinary,
        SafeValue,
        RuntimeScheduling,
        AI_SCHEDULER,
        ["aiCompletion.rateLimitRps"]
    ),
    authority!(
        "ai.streaming.effective_enabled",
        AiStreaming.enabled,
        DerivedGlobal,
        Boolean,
        AI_TRUSTED_OPERATOR_CHANNEL,
        Validation::Derived,
        RecomputeDerived,
        Ordinary,
        DerivedDigestOnly,
        InlineCompletion,
        AI,
        ["streaming.enabled", "user_enabled"]
    ),
    authority!(
        "ai.streaming.update_debounce_ms",
        AiStreaming.update_debounce_ms,
        Global,
        Unsigned,
        AI_CLIENT_ENVELOPE_CHANNEL,
        Validation::UnsignedRange { minimum: 0, maximum: 10_000 },
        KeepLastValid,
        Ordinary,
        SafeValue,
        RuntimeScheduling,
        AI_SCHEDULER,
        ["streaming.updateDebounceMs"]
    ),
    authority!(
        "ai.streaming.user_enabled",
        AiStreaming.user_enabled,
        Global,
        Boolean,
        AI_TRUSTED_OPERATOR_CHANNEL,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        InlineCompletion,
        AI,
        ["streaming.enabled"]
    ),
    authority!(
        "ai.timeout_ms",
        AiCompletion.timeout_ms,
        Global,
        Unsigned,
        AI_CLIENT_ENVELOPE_CHANNEL,
        Validation::UnsignedRange { minimum: 1, maximum: 120_000 },
        KeepLastValid,
        Ordinary,
        SafeValue,
        RuntimeScheduling,
        AI_SCHEDULER,
        ["aiCompletion.timeoutMs"]
    ),
    authority!(
        "ai.user_enabled",
        AiCompletion.user_enabled,
        Global,
        Boolean,
        AI_TRUSTED_OPERATOR_CHANNEL,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        InlineCompletion,
        AI,
        ["aiCompletion.enabled"]
    ),
    authority!(
        "critic.effective_enabled",
        Server.perlcritic_enabled,
        Global,
        Boolean,
        CLIENT_FOLDER,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        Diagnostics,
        CRITIC,
        ["critic.enabled", "perlcritic.enabled"]
    ),
    authority!(
        "critic.engine",
        Server.critic_engine,
        Global,
        Enum,
        CLIENT_FOLDER,
        Validation::KnownEnum,
        KeepLastValid,
        Ordinary,
        SafeValue,
        Diagnostics,
        CRITIC,
        ["critic.engine"]
    ),
    authority!(
        "critic.exclude",
        Server.native_critic_exclude,
        Global,
        StringList,
        CLIENT_FOLDER,
        Validation::StringList,
        KeepLastValid,
        Ordinary,
        BoundedValue,
        Diagnostics,
        NATIVE_CRITIC,
        ["critic.exclude"]
    ),
    authority!(
        "critic.include",
        Server.native_critic_include,
        Global,
        StringList,
        CLIENT_FOLDER,
        Validation::StringList,
        KeepLastValid,
        Ordinary,
        BoundedValue,
        Diagnostics,
        NATIVE_CRITIC,
        ["critic.include"]
    ),
    authority!(
        "critic.legacy_profile",
        Server.perlcritic_profile,
        Global,
        OptionalString,
        PROJECT_ONLY,
        Validation::OptionalNonEmptyString,
        RejectSource,
        Path,
        PathIdentityOnly,
        Diagnostics,
        CRITIC,
        ["perlcritic.profile"]
    ),
    authority!(
        "critic.legacy_theme",
        Server.perlcritic_theme,
        Global,
        OptionalString,
        PROJECT_ONLY,
        Validation::OptionalNonEmptyString,
        RejectSource,
        Ordinary,
        BoundedValue,
        Diagnostics,
        CRITIC,
        ["perlcritic.theme"]
    ),
    authority!(
        "critic.profile",
        Server.native_critic_profile,
        Global,
        String,
        CLIENT_FOLDER,
        Validation::KnownEnum,
        KeepLastValid,
        Ordinary,
        SafeValue,
        Diagnostics,
        NATIVE_CRITIC,
        ["critic.profile"]
    ),
    authority!(
        "critic.severity",
        Server.perlcritic_severity,
        Global,
        Unsigned,
        CLIENT_FOLDER,
        Validation::UnsignedRange { minimum: 1, maximum: 5 },
        ClampToRange,
        Ordinary,
        SafeValue,
        Diagnostics,
        CRITIC,
        ["critic.severity", "perlcritic.severity"]
    ),
    authority!(
        "formatting.add_trailing_commas",
        Server.perltidy_add_trailing_commas,
        Global,
        Boolean,
        CLIENT_FOLDER,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        Formatting,
        FORMATTER,
        ["formatting.addTrailingCommas"]
    ),
    authority!(
        "formatting.block_comment_indentation",
        Server.perltidy_block_comment_indentation,
        Global,
        Unsigned,
        CLIENT_FOLDER,
        Validation::UnsignedRange { minimum: 0, maximum: 32 },
        KeepLastValid,
        Ordinary,
        SafeValue,
        Formatting,
        FORMATTER,
        ["formatting.blockCommentIndentation"]
    ),
    authority!(
        "formatting.cuddled_else",
        Server.perltidy_cuddled_else,
        Global,
        Boolean,
        CLIENT_FOLDER,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        Formatting,
        FORMATTER,
        ["formatting.cuddledElse"]
    ),
    authority!(
        "formatting.enabled",
        Server.perltidy_enabled,
        Global,
        Boolean,
        CLIENT_FOLDER,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        Formatting,
        FORMATTER,
        ["formatting.enabled"]
    ),
    authority!(
        "formatting.engine",
        Server.formatting_engine,
        Global,
        Enum,
        CLIENT_GLOBAL,
        Validation::KnownEnum,
        KeepLastValid,
        Ordinary,
        SafeValue,
        Formatting,
        FORMATTER,
        ["formatting.engine"]
    ),
    authority!(
        "formatting.extra_args",
        Server.perltidy_extra_args,
        Global,
        StringList,
        PROJECT_ONLY,
        Validation::StringList,
        RejectSource,
        Executable,
        Redacted,
        Formatting,
        FORMATTER,
        ["formatting.extraArgs"]
    ),
    authority!(
        "formatting.format_on_save",
        Server.format_on_save,
        Global,
        Boolean,
        CLIENT_FOLDER,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        Formatting,
        FORMATTER_SAVE,
        ["formatting.formatOnSave"]
    ),
    authority!(
        "formatting.indent_columns",
        Server.perltidy_indent_columns,
        Global,
        Unsigned,
        CLIENT_FOLDER,
        Validation::UnsignedRange { minimum: 1, maximum: 32 },
        KeepLastValid,
        Ordinary,
        SafeValue,
        Formatting,
        FORMATTER,
        ["formatting.indentColumns"]
    ),
    authority!(
        "formatting.maximum_line_length",
        Server.perltidy_maximum_line_length,
        Global,
        Unsigned,
        CLIENT_FOLDER,
        Validation::UnsignedRange { minimum: 20, maximum: 1000 },
        KeepLastValid,
        Ordinary,
        SafeValue,
        Formatting,
        FORMATTER,
        ["formatting.maximumLineLength"]
    ),
    authority!(
        "formatting.opening_brace_on_new_line",
        Server.perltidy_opening_brace_on_new_line,
        Global,
        Boolean,
        CLIENT_FOLDER,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        Formatting,
        FORMATTER,
        ["formatting.openingBraceOnNewLine"]
    ),
    authority!(
        "formatting.profile",
        Server.perltidy_profile,
        Global,
        OptionalString,
        PROJECT_ONLY,
        Validation::OptionalNonEmptyString,
        RejectSource,
        Path,
        PathIdentityOnly,
        Formatting,
        FORMATTER,
        ["formatting.profile"]
    ),
    authority!(
        "formatting.space_after_keyword",
        Server.perltidy_space_after_keyword,
        Global,
        Boolean,
        CLIENT_FOLDER,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        Formatting,
        FORMATTER,
        ["formatting.spaceAfterKeyword"]
    ),
    authority!(
        "formatting.tabs",
        Server.perltidy_tabs,
        Global,
        Boolean,
        CLIENT_FOLDER,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        Formatting,
        FORMATTER,
        ["formatting.tabs"]
    ),
    authority!(
        "formatting.timeout_secs",
        Server.perltidy_timeout_secs,
        Global,
        Unsigned,
        CLIENT_FOLDER,
        Validation::UnsignedRange { minimum: 1, maximum: 300 },
        KeepLastValid,
        Ordinary,
        SafeValue,
        RuntimeScheduling,
        FORMATTER,
        ["formatting.timeoutSecs"]
    ),
    authority!(
        "formatting.vertical_alignment",
        Server.perltidy_vertical_alignment,
        Global,
        Boolean,
        CLIENT_FOLDER,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        Formatting,
        FORMATTER,
        ["formatting.verticalAlignment"]
    ),
    authority!(
        "inlay.chained_hints",
        Server.inlay_hints_chained_hints,
        Global,
        Boolean,
        CLIENT_FOLDER,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        InlayHints,
        &[Consumer::InlayHintProvider],
        ["inlayHints.chainedHints"]
    ),
    authority!(
        "inlay.enabled",
        Server.inlay_hints_enabled,
        Global,
        Boolean,
        CLIENT_FOLDER,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        InlayHints,
        &[Consumer::InlayHintProvider],
        ["inlayHints.enabled"]
    ),
    authority!(
        "inlay.max_length",
        Server.inlay_hints_max_length,
        Global,
        Unsigned,
        CLIENT_FOLDER,
        Validation::UnsignedRange { minimum: 1, maximum: 512 },
        KeepLastValid,
        Ordinary,
        SafeValue,
        InlayHints,
        &[Consumer::InlayHintProvider],
        ["inlayHints.maxLength"]
    ),
    authority!(
        "inlay.parameter_hints",
        Server.inlay_hints_parameter_hints,
        Global,
        Boolean,
        CLIENT_FOLDER,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        InlayHints,
        &[Consumer::InlayHintProvider],
        ["inlayHints.parameterHints"]
    ),
    authority!(
        "inlay.type_hints",
        Server.inlay_hints_type_hints,
        Global,
        Boolean,
        CLIENT_FOLDER,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        InlayHints,
        &[Consumer::InlayHintProvider],
        ["inlayHints.typeHints"]
    ),
    authority!(
        "next_edit.enabled",
        NextEdit.enabled,
        Global,
        Boolean,
        CLIENT_GLOBAL,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        None,
        &[Consumer::NextEditGate],
        ["nextEdit.enabled"]
    ),
    authority!(
        "telemetry.enabled",
        Server.telemetry_enabled,
        Global,
        Boolean,
        CLIENT_GLOBAL,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        Telemetry,
        &[Consumer::Telemetry],
        ["telemetry.enabled"]
    ),
    authority!(
        "workspace.declared_dependencies",
        Workspace.declared_dependencies,
        DerivedWorkspaceFolder,
        DerivedList,
        PROJECT_METADATA,
        Validation::Derived,
        RecomputeDerived,
        Ordinary,
        DerivedDigestOnly,
        WorkspaceDiscovery,
        DISCOVERY,
        ["declared_dependencies", "META.json", "cpanfile"]
    ),
    authority!(
        "workspace.discovery_extra_extensions",
        Workspace.discovery_extra_extensions,
        WorkspaceFolder,
        StringList,
        CLIENT_FOLDER,
        Validation::StringList,
        KeepLastValid,
        Ordinary,
        BoundedValue,
        WorkspaceDiscovery,
        DISCOVERY,
        ["workspace.discoveryExtensions", "perl.discovery_extensions"]
    ),
    authority!(
        "workspace.discovery_extra_skipped_dirs",
        Workspace.discovery_extra_skipped_dirs,
        WorkspaceFolder,
        StringList,
        CLIENT_FOLDER,
        Validation::StringList,
        KeepLastValid,
        Ordinary,
        BoundedValue,
        WorkspaceDiscovery,
        DISCOVERY,
        ["workspace.discoverySkippedDirs", "perl.discovery_skipped_dirs"]
    ),
    authority!(
        "workspace.external_include_paths",
        Workspace.external_include_paths,
        Global,
        StringList,
        MACHINE_PATH,
        Validation::AbsoluteExternalPathList,
        RejectSource,
        Path,
        PathIdentityOnly,
        ModuleResolution,
        RESOLUTION,
        ["workspace.externalIncludePaths"]
    ),
    authority!(
        "workspace.include_paths",
        Workspace.include_paths,
        WorkspaceFolder,
        StringList,
        CLIENT_FOLDER,
        Validation::RelativeWorkspacePathList,
        RejectSource,
        Path,
        PathIdentityOnly,
        ModuleResolution,
        RESOLUTION,
        ["workspace.includePaths"]
    ),
    authority!(
        "workspace.native_build_hints",
        Workspace.native_build_hints,
        DerivedWorkspaceFolder,
        DerivedList,
        PROJECT_METADATA,
        Validation::Derived,
        RecomputeDerived,
        Ordinary,
        DerivedDigestOnly,
        WorkspaceDiscovery,
        DISCOVERY,
        ["native_build_hints", "Makefile.PL", "Build.PL"]
    ),
    authority!(
        "workspace.perl5lib_precedence",
        Workspace.perl5lib_precedence,
        WorkspaceFolder,
        Enum,
        WORKSPACE_ENVIRONMENT,
        Validation::KnownEnum,
        KeepLastValid,
        Ordinary,
        SafeValue,
        ModuleResolution,
        RESOLUTION,
        ["workspace.perl5libPrecedence", "PERL5LIB"]
    ),
    authority!(
        "workspace.perl_args",
        Workspace.perl_args,
        Global,
        StringList,
        TRUSTED_USER_PROJECT,
        Validation::ExecutableAndArgs,
        RejectSource,
        Executable,
        Redacted,
        ModuleResolution,
        &[Consumer::PerlToolchain, Consumer::ModuleResolver],
        ["workspace.perlArgs"]
    ),
    authority!(
        "workspace.perl_path",
        Workspace.perl_path,
        Global,
        OptionalString,
        TRUSTED_USER_PROJECT,
        Validation::ExecutableAndArgs,
        RejectSource,
        Executable,
        PathIdentityOnly,
        ModuleResolution,
        &[Consumer::PerlToolchain, Consumer::ModuleResolver],
        ["workspace.perlPath"]
    ),
    authority!(
        "workspace.resolution_timeout_ms",
        Workspace.resolution_timeout_ms,
        WorkspaceFolder,
        Unsigned,
        CLIENT_FOLDER,
        Validation::UnsignedRange { minimum: 1, maximum: 60_000 },
        KeepLastValid,
        Ordinary,
        SafeValue,
        RuntimeScheduling,
        &[Consumer::ModuleResolver],
        ["workspace.resolutionTimeout"]
    ),
    authority!(
        "workspace.use_perl5lib",
        Workspace.use_perl5lib,
        WorkspaceFolder,
        Boolean,
        WORKSPACE_ENVIRONMENT,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        ModuleResolution,
        RESOLUTION,
        ["workspace.usePerl5lib", "PERL5LIB", "PERLLIB"]
    ),
    authority!(
        "workspace.use_system_inc",
        Workspace.use_system_inc,
        WorkspaceFolder,
        Boolean,
        WORKSPACE_SYSTEM,
        Validation::Boolean,
        KeepLastValid,
        Ordinary,
        SafeValue,
        ModuleResolution,
        &[Consumer::PerlToolchain, Consumer::ModuleResolver],
        ["workspace.useSystemInc", "@INC"]
    ),
];
