//! Deterministic JSON, Markdown, and human-report projections.
//!
//! Same tree in, byte-identical artifacts out: rows are canonically sorted,
//! every aggregate iterates a `BTreeMap`, and no timestamp, hostname, or
//! absolute path enters the output.

use std::collections::BTreeMap;

use super::model::{CandidateProfileV1, ProofRoleV1, TestTopologyInventoryV1};

/// Serializes the inventory as pretty JSON with a trailing newline.
pub fn render_json(inventory: &TestTopologyInventoryV1) -> anyhow::Result<String> {
    let mut payload = serde_json::to_string_pretty(inventory)
        .map_err(|error| anyhow::Error::new(error).context("serializing topology inventory"))?;
    payload.push('\n');
    Ok(payload)
}

/// Renders the Markdown projection of the inventory.
///
/// Opens with an AUTO-GENERATED marker so generated-artifact scanners see the
/// file's provenance; the body is a summary section plus one table row per
/// topology row in canonical order.
pub fn render_markdown(inventory: &TestTopologyInventoryV1) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "<!-- AUTO-GENERATED by `{}`. Do not edit by hand. -->\n",
        inventory.regenerate_command
    ));
    out.push_str("# Compiler-Critical Test Topology Inventory\n\n");
    out.push_str(&format!(
        "Schema: `{}` v{} | cohort: `{}` | feature authorities: {} | controllers: {}\n\n",
        inventory.schema_id,
        inventory.schema_version,
        inventory.cohort,
        inventory.feature_authorities.join(" / "),
        inventory.controllers.join(" "),
    ));
    out.push_str(
        "Existence of a target proves nothing about passing; compile obligations \
                  and execution claims are represented separately and this inventory claims \
                  no execution.\n\n",
    );
    out.push_str("## Summary\n\n");
    let per_package = count_by(inventory.rows.iter().map(|row| row.package_id.as_str()));
    let per_role = count_by(inventory.rows.iter().map(|row| row.proof_role.as_token()));
    out.push_str("| Metric | Count |\n|---|---|\n");
    out.push_str(&format!("| Governed subjects | {} |\n", inventory.rows.len()));
    for (package, count) in &per_package {
        out.push_str(&format!("| Package `{package}` | {count} |\n"));
    }
    for (role, count) in &per_role {
        out.push_str(&format!("| Proof role `{role}` | {count} |\n"));
    }
    let mut gated_zero = 0usize;
    for row in &inventory.rows {
        if matches!(
            row.feature_subject.default_profile_state,
            super::model::DefaultProfileStateV1::FeatureGated
        ) {
            gated_zero += 1;
        }
    }
    out.push_str(&format!(
        "| Feature-gated (zero under default profile, explicit) | {gated_zero} |\n\n"
    ));
    out.push_str("## Rows\n\n");
    out.push_str(
        "| target_id | kind | harness | doctest | required features | default profile | \
         proof role | controllers | profiles | compile obligation | path |\n",
    );
    out.push_str("|---|---|---|---|---|---|---|---|---|---|---|\n");
    for row in &inventory.rows {
        let profiles: Vec<&str> =
            row.candidate_profiles.iter().map(|profile| profile.as_token()).collect();
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {:?} | {} | {} | {} | {:?} | {} |\n",
            row.target_id,
            row.target_kind.as_token(),
            row.harness,
            match row.doctest {
                Some(value) => value.to_string(),
                None => "-".to_string(),
            },
            if row.feature_subject.required.is_empty() {
                "-".to_string()
            } else {
                escape_table(&row.feature_subject.required.join(", "))
            },
            row.feature_subject.default_profile_state,
            row.proof_role.as_token(),
            row.controller_refs.join(" "),
            profiles.join(","),
            row.compile_obligation,
            escape_table(&row.path),
        ));
    }
    out
}

/// Renders the deterministic human report (counts per package, proof role,
/// candidate profile).
pub fn render_report(inventory: &TestTopologyInventoryV1) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "test-topology report: cohort={} schema={} rows={}\n",
        inventory.cohort,
        inventory.schema_id,
        inventory.rows.len(),
    ));
    out.push_str("counts per package:\n");
    for (package, count) in count_by(inventory.rows.iter().map(|row| row.package_id.as_str())) {
        out.push_str(&format!("  {package}: {count}\n"));
    }
    out.push_str("counts per proof role:\n");
    for (role, count) in count_by(inventory.rows.iter().map(|row| role_label(row.proof_role))) {
        out.push_str(&format!("  {role}: {count}\n"));
    }
    out.push_str("counts per candidate profile:\n");
    let mut per_profile: BTreeMap<String, usize> = BTreeMap::new();
    for row in &inventory.rows {
        for profile in &row.candidate_profiles {
            *per_profile.entry(profile_token(*profile).to_string()).or_default() += 1;
        }
    }
    for (profile, count) in &per_profile {
        out.push_str(&format!("  {profile}: {count}\n"));
    }
    out
}

fn role_label(role: ProofRoleV1) -> &'static str {
    role.as_token()
}

fn profile_token(profile: CandidateProfileV1) -> &'static str {
    profile.as_token()
}

fn count_by<'a, Key: Ord + Clone + 'a>(keys: impl Iterator<Item = Key>) -> BTreeMap<Key, usize> {
    let mut counts: BTreeMap<Key, usize> = BTreeMap::new();
    for key in keys {
        *counts.entry(key).or_default() += 1;
    }
    counts
}

fn escape_table(value: &str) -> String {
    value.replace('|', "\\|")
}
